/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal_Administrador.java
 *
 * Created on 16-mar-2011, 18:27:18
 */

package centro_medico;


/**
 *
 * @author fran_gestion
 */
public class Principal_Administrador extends javax.swing.JFrame {

    /** Creates new form Principal_Administrador */
    public Principal_Administrador() {
        initComponents();
        
    }

    public Principal_Administrador(String nombreUsuario, String tipoUsuario){
        initComponents();
        jLabelNombreUsuario.setText(nombreUsuario);
        jLabelTipoUsuario.setText(tipoUsuario);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabelCentroMedico = new javax.swing.JLabel();
        jPanelIcono = new javax.swing.JPanel();
        jLabelIcono = new javax.swing.JLabel();
        jPanelBotones = new javax.swing.JPanel();
        jToggleButtonGestionUsuarios = new javax.swing.JToggleButton();
        jToggleButtonGestionCitas = new javax.swing.JToggleButton();
        jToggleButtonGestionPersonal = new javax.swing.JToggleButton();
        jToggleButtonGestionPacientes = new javax.swing.JToggleButton();
        jToggleButtonGestionEstadisticas = new javax.swing.JToggleButton();
        jToggleButtonGestionHorarios = new javax.swing.JToggleButton();
        jLabelIconoInicio = new javax.swing.JLabel();
        jLabelInicio = new javax.swing.JLabel();
        jLabelIconoAyuda = new javax.swing.JLabel();
        jLabelIconoSalir = new javax.swing.JLabel();
        jLabelAyuda = new javax.swing.JLabel();
        jLabelSalir = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelTipoUsuario = new javax.swing.JLabel();
        jLabelNombreUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 102));
        setLocation(new java.awt.Point(320, 150));

        jTabbedPane1.setAutoscrolls(true);

        jLabelCentroMedico.setText("Centro médico");

        jPanelIcono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesIntro/Logo-Centro-Medico.png"))); // NOI18N

        org.jdesktop.layout.GroupLayout jPanelIconoLayout = new org.jdesktop.layout.GroupLayout(jPanelIcono);
        jPanelIcono.setLayout(jPanelIconoLayout);
        jPanelIconoLayout.setHorizontalGroup(
            jPanelIconoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabelIcono, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );
        jPanelIconoLayout.setVerticalGroup(
            jPanelIconoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelIconoLayout.createSequentialGroup()
                .add(jLabelIcono, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );

        jToggleButtonGestionUsuarios.setText("Gestión Usuarios");
        jToggleButtonGestionUsuarios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButtonGestionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonGestionUsuariosActionPerformed(evt);
            }
        });

        jToggleButtonGestionCitas.setText("Gestión Citas");
        jToggleButtonGestionCitas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButtonGestionCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonGestionCitasActionPerformed(evt);
            }
        });

        jToggleButtonGestionPersonal.setText("Gestión Personal");
        jToggleButtonGestionPersonal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButtonGestionPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonGestionPersonalActionPerformed(evt);
            }
        });

        jToggleButtonGestionPacientes.setText("Gestión Pacientes");
        jToggleButtonGestionPacientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButtonGestionPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonGestionPacientesActionPerformed(evt);
            }
        });

        jToggleButtonGestionEstadisticas.setText("Gestión Estadísticas");
        jToggleButtonGestionEstadisticas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButtonGestionEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonGestionEstadisticasActionPerformed(evt);
            }
        });

        jToggleButtonGestionHorarios.setText("Gestión Horarios");
        jToggleButtonGestionHorarios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButtonGestionHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonGestionHorariosActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelBotonesLayout = new org.jdesktop.layout.GroupLayout(jPanelBotones);
        jPanelBotones.setLayout(jPanelBotonesLayout);
        jPanelBotonesLayout.setHorizontalGroup(
            jPanelBotonesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 267, Short.MAX_VALUE)
            .add(jPanelBotonesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanelBotonesLayout.createSequentialGroup()
                    .addContainerGap()
                    .add(jPanelBotonesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jToggleButtonGestionUsuarios, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jToggleButtonGestionPacientes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                        .add(jToggleButtonGestionPersonal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jToggleButtonGestionCitas, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jToggleButtonGestionEstadisticas, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jToggleButtonGestionHorarios, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanelBotonesLayout.setVerticalGroup(
            jPanelBotonesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 334, Short.MAX_VALUE)
            .add(jPanelBotonesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanelBotonesLayout.createSequentialGroup()
                    .addContainerGap()
                    .add(jToggleButtonGestionUsuarios, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                    .add(jToggleButtonGestionPacientes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                    .add(jToggleButtonGestionPersonal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                    .add(jToggleButtonGestionCitas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                    .add(jToggleButtonGestionHorarios, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                    .add(jToggleButtonGestionEstadisticas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabelIconoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPrincipal/Inicio-Desactivado.png"))); // NOI18N
        jLabelIconoInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIconoInicioMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIconoInicioMouseEntered(evt);
            }
        });

        jLabelInicio.setText("Inicio");

        jLabelIconoAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPrincipal/Ayuda-Desactivado.png"))); // NOI18N
        jLabelIconoAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconoAyudaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIconoAyudaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIconoAyudaMouseEntered(evt);
            }
        });

        jLabelIconoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPrincipal/Salir-Desactivado.png"))); // NOI18N
        jLabelIconoSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconoSalirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIconoSalirMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIconoSalirMouseEntered(evt);
            }
        });

        jLabelAyuda.setText("Ayuda");

        jLabelSalir.setText("Salir");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabelUsuario.setText("Usuario:");

        jLabelTipoUsuario.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelTipoUsuario.setText("Tipo Usuario");

        jLabelNombreUsuario.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelNombreUsuario.setText("Nombre");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelUsuario)
                    .add(jLabelTipoUsuario)
                    .add(jLabelNombreUsuario))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jLabelUsuario)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelTipoUsuario)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelNombreUsuario)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(jPanelIcono, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(79, 79, 79))
                            .add(layout.createSequentialGroup()
                                .add(jPanelBotones, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))))
                    .add(layout.createSequentialGroup()
                        .add(88, 88, 88)
                        .add(jLabelCentroMedico)))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(59, 59, 59)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelIconoInicio)
                            .add(jLabelInicio))
                        .add(36, 36, 36)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabelAyuda)
                            .add(jLabelIconoAyuda))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(31, 31, 31)
                                .add(jLabelIconoSalir))
                            .add(layout.createSequentialGroup()
                                .add(39, 39, 39)
                                .add(jLabelSalir)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 65, Short.MAX_VALUE)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabelCentroMedico)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanelIcono, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanelBotones, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jLabelIconoAyuda)
                                    .add(jLabelIconoInicio))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabelInicio)
                                    .add(jLabelAyuda)
                                    .add(jLabelSalir)))
                            .add(jLabelIconoSalir)
                            .add(jPanel1, 0, 71, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 457, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonGestionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonGestionUsuariosActionPerformed
        // TODO add your handling code here:

        /////////////////Cambio de tamaño del texto de los botones//////////////////
        jToggleButtonGestionUsuarios.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jToggleButtonGestionPacientes.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionPersonal.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionCitas.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionHorarios.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionEstadisticas.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N


        /////////////////Cambio del color del texto de los botones//////////////////
        jToggleButtonGestionUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionPacientes.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionPersonal.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionCitas.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionHorarios.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionEstadisticas.setForeground(new java.awt.Color(0, 0, 0));



        jTabbedPane1.removeAll();
        jTabbedPane1.addTab("Alta Médico", new AltaMedico());
        jTabbedPane1.addTab("Modificar Médico", new ModificarMedico());

    }//GEN-LAST:event_jToggleButtonGestionUsuariosActionPerformed
    
    private void jToggleButtonGestionCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonGestionCitasActionPerformed
        // TODO add your handling code here:
        /////////////////Cambio de tamaño del texto de los botones//////////////////
        jToggleButtonGestionUsuarios.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionPacientes.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionPersonal.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionCitas.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jToggleButtonGestionHorarios.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionEstadisticas.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N


        /////////////////Cambio del color del texto de los botones//////////////////
        jToggleButtonGestionUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionPacientes.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionPersonal.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionCitas.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionHorarios.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionEstadisticas.setForeground(new java.awt.Color(0, 0, 0));



        jTabbedPane1.removeAll();

    }//GEN-LAST:event_jToggleButtonGestionCitasActionPerformed

    private void jToggleButtonGestionPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonGestionPersonalActionPerformed
        // TODO add your handling code here:
        /////////////////Cambio de tamaño del texto de los botones//////////////////
        jToggleButtonGestionUsuarios.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionPacientes.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionPersonal.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jToggleButtonGestionCitas.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionHorarios.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionEstadisticas.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N


        /////////////////Cambio del color del texto de los botones//////////////////
        jToggleButtonGestionUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionPacientes.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionPersonal.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionCitas.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionHorarios.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionEstadisticas.setForeground(new java.awt.Color(0, 0, 0));



        jTabbedPane1.removeAll();

    }//GEN-LAST:event_jToggleButtonGestionPersonalActionPerformed

    private void jToggleButtonGestionPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonGestionPacientesActionPerformed
        // TODO add your handling code here:
        /////////////////Cambio de tamaño del texto de los botones//////////////////
        jToggleButtonGestionUsuarios.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionPacientes.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jToggleButtonGestionPersonal.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionCitas.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionHorarios.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionEstadisticas.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N


        /////////////////Cambio del color del texto de los botones//////////////////
        jToggleButtonGestionUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionPacientes.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionPersonal.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionCitas.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionHorarios.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionEstadisticas.setForeground(new java.awt.Color(0, 0, 0));



        jTabbedPane1.removeAll();
        jTabbedPane1.addTab("Alta Paciente", new AltaPaciente());
        jTabbedPane1.addTab("Modificar Paciente", new ModificarPaciente());

    }//GEN-LAST:event_jToggleButtonGestionPacientesActionPerformed

    private void jToggleButtonGestionEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonGestionEstadisticasActionPerformed
        // TODO add your handling code here:
        /////////////////Cambio de tamaño del texto de los botones//////////////////
        jToggleButtonGestionUsuarios.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionPacientes.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionPersonal.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionCitas.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionHorarios.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionEstadisticas.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N


        /////////////////Cambio del color del texto de los botones//////////////////
        jToggleButtonGestionUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionPacientes.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionPersonal.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionCitas.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionHorarios.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionEstadisticas.setForeground(new java.awt.Color(0, 0, 0));



        jTabbedPane1.removeAll();
    }//GEN-LAST:event_jToggleButtonGestionEstadisticasActionPerformed

    private void jToggleButtonGestionHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonGestionHorariosActionPerformed
        // TODO add your handling code here:
        /////////////////Cambio de tamaño del texto de los botones//////////////////
        jToggleButtonGestionUsuarios.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionPacientes.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionPersonal.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionCitas.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jToggleButtonGestionHorarios.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jToggleButtonGestionEstadisticas.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N


        /////////////////Cambio del color del texto de los botones//////////////////
        jToggleButtonGestionUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionPacientes.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionPersonal.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionCitas.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionHorarios.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonGestionEstadisticas.setForeground(new java.awt.Color(0, 0, 0));



        jTabbedPane1.removeAll();
    }//GEN-LAST:event_jToggleButtonGestionHorariosActionPerformed

    private void jLabelIconoInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoInicioMouseEntered
        // TODO add your handling code here:
        jLabelIconoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPrincipal/Inicio-Activado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoInicioMouseEntered

    private void jLabelIconoInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoInicioMouseExited
        // TODO add your handling code here:
        jLabelIconoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPrincipal/Inicio-Desactivado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoInicioMouseExited

    private void jLabelIconoAyudaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoAyudaMouseExited
        // TODO add your handling code here:
        jLabelIconoAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPrincipal/Ayuda-Desactivado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoAyudaMouseExited

    private void jLabelIconoAyudaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoAyudaMouseEntered
        // TODO add your handling code here:
        jLabelIconoAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPrincipal/Ayuda-Activado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoAyudaMouseEntered

    private void jLabelIconoSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoSalirMouseExited
        // TODO add your handling code here:
        jLabelIconoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPrincipal/Salir-Desactivado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoSalirMouseExited

    private void jLabelIconoSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoSalirMouseEntered
        // TODO add your handling code here:
        jLabelIconoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPrincipal/Salir-Activado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoSalirMouseEntered

    private void jLabelIconoSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelIconoSalirMouseClicked

    private void jLabelIconoAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoAyudaMouseClicked
        // TODO add your handling code here:
        new Ayuda().setVisible(true);
    }//GEN-LAST:event_jLabelIconoAyudaMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAyuda;
    private javax.swing.JLabel jLabelCentroMedico;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JLabel jLabelIconoAyuda;
    private javax.swing.JLabel jLabelIconoInicio;
    private javax.swing.JLabel jLabelIconoSalir;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JLabel jLabelSalir;
    private javax.swing.JLabel jLabelTipoUsuario;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelIcono;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButtonGestionCitas;
    private javax.swing.JToggleButton jToggleButtonGestionEstadisticas;
    private javax.swing.JToggleButton jToggleButtonGestionHorarios;
    private javax.swing.JToggleButton jToggleButtonGestionPacientes;
    private javax.swing.JToggleButton jToggleButtonGestionPersonal;
    private javax.swing.JToggleButton jToggleButtonGestionUsuarios;
    // End of variables declaration//GEN-END:variables

}
