/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal_Administrador.java
 *
 * Created on 16-mar-2011, 18:27:18
 */

package Interfaz;

import Interfaz.Ayuda;
import java.awt.Image;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;


/**
 *
 * @author fran_gestion
 */
public class UI_Paciente extends javax.swing.JFrame {

    /** Creates new form Principal_Administrador */
    public UI_Paciente() {
        initComponents();
    }

    public UI_Paciente(String nombreUsuario, String tipoUsuario){
        initComponents();

        /**Ponemos las etiquetas del usuario que ha entrado*/
        jLabelNombreUsuario.setText(nombreUsuario);
        jLabelTipoUsuario.setText(tipoUsuario);

        /**Mostramos el panel Principal*/
        mostrarPanel("Principal");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelCentroMedico = new javax.swing.JLabel();
        jLabelIconoInicio = new javax.swing.JLabel();
        jLabelInicio = new javax.swing.JLabel();
        jLabelIconoAyuda = new javax.swing.JLabel();
        jLabelIconoSalir = new javax.swing.JLabel();
        jLabelAyuda = new javax.swing.JLabel();
        jLabelSalir = new javax.swing.JLabel();
        jPanelUsuario = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelTipoUsuario = new javax.swing.JLabel();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jLabelIcono = new javax.swing.JLabel();
        ZonaTrabajo = new javax.swing.JLayeredPane();
        jPanelPrincipal = new javax.swing.JPanel();
        jButtonGestionarPaciente = new javax.swing.JButton();
        jLabelGestionarPaciente3 = new javax.swing.JLabel();
        jLabelGestionarCita1 = new javax.swing.JLabel();
        jButtonGestionarCita = new javax.swing.JButton();
        jPanelGestionarPaciente = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelGestionarPaciente4 = new javax.swing.JLabel();
        jTextFieldNombrePaciente = new javax.swing.JTextField();
        jLabelFotoPaciente = new javax.swing.JLabel();
        jTextFieldTelefonoPaciente = new javax.swing.JTextField();
        jLabelContraseniaPaciente = new javax.swing.JLabel();
        jTextFieldDNIPaciente = new javax.swing.JTextField();
        jLabelNombrePaciente = new javax.swing.JLabel();
        jButtonFotoPaciente = new javax.swing.JButton();
        jLabelFotografiaPaciente = new javax.swing.JLabel();
        jLabelDNIPaciente = new javax.swing.JLabel();
        jTextFieldLugarNacimientoPaciente = new javax.swing.JTextField();
        jLabelTelefonoPaciente = new javax.swing.JLabel();
        jTextFieldFechaNacimientoMesPaciente = new javax.swing.JTextField();
        jLabelLugarNacimientoPaciente = new javax.swing.JLabel();
        jLabelDireccionPaciente = new javax.swing.JLabel();
        jButtonMenosAnioPaciente = new javax.swing.JButton();
        jLabelApellidosPaciente = new javax.swing.JLabel();
        jTextFieldApellidosPaciente = new javax.swing.JTextField();
        jButtonAltaPaciente = new javax.swing.JButton();
        jButtonMasDiaPaciente = new javax.swing.JButton();
        jButtonMenosMesPaciente = new javax.swing.JButton();
        jButtonMenosDiaPaciente = new javax.swing.JButton();
        jLabelEmailPaciente = new javax.swing.JLabel();
        jTextFieldDireccionPaciente = new javax.swing.JTextField();
        jTextFieldFechaNacimientoDiaPaciente = new javax.swing.JTextField();
        jButtonMasAnioPaciente = new javax.swing.JButton();
        jLabelInfoFotoPaciente = new javax.swing.JLabel();
        jTextFieldEmailPaciente = new javax.swing.JTextField();
        jTextFieldFechaNacimientoAnioPaciente = new javax.swing.JTextField();
        jTextFieldContraseniaPaciente = new javax.swing.JTextField();
        jButtonMasMesPaciente = new javax.swing.JButton();
        jLabelFechaNacimientoPaciente = new javax.swing.JLabel();
        jButtonConsultarPaciente = new javax.swing.JButton();
        jButtonLimpiarPaciente = new javax.swing.JButton();
        jPanelGestionarCitaOnline = new javax.swing.JPanel();
        jTextFieldMesCita = new javax.swing.JTextField();
        jButtonMenosAnioPersonal = new javax.swing.JButton();
        jButtonMasAnioFecha = new javax.swing.JButton();
        jTextFieldAnioCita = new javax.swing.JTextField();
        jLabelFecha = new javax.swing.JLabel();
        jTextFieldDiaCita = new javax.swing.JTextField();
        jButtonMasMesFecha = new javax.swing.JButton();
        jButtonMasDiaFecha = new javax.swing.JButton();
        jButtonAltaPersonal = new javax.swing.JButton();
        jButtonMenosDiaFecha = new javax.swing.JButton();
        jButtonMenosMesFecha = new javax.swing.JButton();
        jTextFieldDNIPacienteCita = new javax.swing.JTextField();
        jLabelDNIPacienteCita = new javax.swing.JLabel();
        jLabelGestionarPaciente2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonLimpiarPersonal = new javax.swing.JButton();
        jButtonConsultarPersonal = new javax.swing.JButton();
        jButtonMasHora = new javax.swing.JButton();
        jButtonMasMinuto = new javax.swing.JButton();
        jTextFieldHoraCita = new javax.swing.JTextField();
        jTextFieldMinutoCita = new javax.swing.JTextField();
        jButtonMenosHora = new javax.swing.JButton();
        jButtonMenosMinuto = new javax.swing.JButton();
        jLabelHoraCita = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 102));
        setLocation(new java.awt.Point(150, 22));
        setMinimumSize(new java.awt.Dimension(931, 715));
        setResizable(false);

        jLabelCentroMedico.setText("Centro médico");

        jLabelIconoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CentroMedico/Imagenes/Principal/Inicio-Desactivado.png"))); // NOI18N
        jLabelIconoInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconoInicioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIconoInicioMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIconoInicioMouseEntered(evt);
            }
        });

        jLabelInicio.setText("Inicio");

        jLabelIconoAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CentroMedico/Imagenes/Principal/Ayuda-Desactivado.png"))); // NOI18N
        jLabelIconoAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconoAyudaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIconoAyudaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIconoAyudaMouseEntered(evt);
            }
        });

        jLabelIconoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CentroMedico/Imagenes/Principal/Salir-Desactivado.png"))); // NOI18N
        jLabelIconoSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconoSalirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIconoSalirMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIconoSalirMouseEntered(evt);
            }
        });

        jLabelAyuda.setText("Ayuda");

        jLabelSalir.setText("Salir");

        jPanelUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabelUsuario.setText("Usuario:");

        jLabelTipoUsuario.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabelTipoUsuario.setText("Tipo Usuario");

        jLabelNombreUsuario.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabelNombreUsuario.setText("Nombre");

        org.jdesktop.layout.GroupLayout jPanelUsuarioLayout = new org.jdesktop.layout.GroupLayout(jPanelUsuario);
        jPanelUsuario.setLayout(jPanelUsuarioLayout);
        jPanelUsuarioLayout.setHorizontalGroup(
            jPanelUsuarioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelUsuarioLayout.createSequentialGroup()
                .add(jPanelUsuarioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelUsuario)
                    .add(jLabelTipoUsuario)
                    .add(jLabelNombreUsuario))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanelUsuarioLayout.setVerticalGroup(
            jPanelUsuarioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelUsuarioLayout.createSequentialGroup()
                .add(jLabelUsuario)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelTipoUsuario)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelNombreUsuario)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CentroMedico/Imagenes/Intro/Logo-Centro-Medico.png"))); // NOI18N

        ZonaTrabajo.setMinimumSize(new java.awt.Dimension(902, 520));
        ZonaTrabajo.setPreferredSize(new java.awt.Dimension(912, 530));

        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(901, 531));

        jButtonGestionarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CentroMedico/Imagenes/Principal/Paciente.png"))); // NOI18N
        jButtonGestionarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGestionarPacienteMouseClicked(evt);
            }
        });
        jButtonGestionarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionarPacienteActionPerformed(evt);
            }
        });

        jLabelGestionarPaciente3.setText("Gestionar Paciente");

        jLabelGestionarCita1.setText("Gestionar Cita Online");

        jButtonGestionarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CentroMedico/Imagenes/Principal/Cita.png"))); // NOI18N
        jButtonGestionarCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGestionarCitaMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelPrincipalLayout = new org.jdesktop.layout.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelPrincipalLayout.createSequentialGroup()
                .add(jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelPrincipalLayout.createSequentialGroup()
                        .add(47, 47, 47)
                        .add(jButtonGestionarPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 194, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanelPrincipalLayout.createSequentialGroup()
                        .add(89, 89, 89)
                        .add(jLabelGestionarPaciente3)))
                .add(jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelPrincipalLayout.createSequentialGroup()
                        .add(53, 53, 53)
                        .add(jButtonGestionarCita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 194, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanelPrincipalLayout.createSequentialGroup()
                        .add(84, 84, 84)
                        .add(jLabelGestionarCita1)))
                .addContainerGap(412, Short.MAX_VALUE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelPrincipalLayout.createSequentialGroup()
                .add(29, 29, 29)
                .add(jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButtonGestionarCita, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButtonGestionarPaciente, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelGestionarPaciente3)
                    .add(jLabelGestionarCita1))
                .add(315, 315, 315))
        );

        jPanelPrincipal.setBounds(1, 0, 900, 530);
        ZonaTrabajo.add(jPanelPrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanelGestionarPaciente.setPreferredSize(new java.awt.Dimension(901, 531));

        jLabel3.setText("___________________________________________________________________");

        jLabelGestionarPaciente4.setFont(new java.awt.Font("Lucida Grande", 1, 48));
        jLabelGestionarPaciente4.setText("Gestionar Paciente");

        jLabelFotoPaciente.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFotoPaciente.setForeground(new java.awt.Color(255, 255, 255));

        jLabelContraseniaPaciente.setText("Contraseña");

        jLabelNombrePaciente.setText("Nombre");

        jButtonFotoPaciente.setText("Añadir foto");
        jButtonFotoPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFotoPacienteMouseClicked(evt);
            }
        });
        jButtonFotoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFotoPacienteActionPerformed(evt);
            }
        });

        jLabelFotografiaPaciente.setText("Fotografía");

        jLabelDNIPaciente.setText("DNI");

        jLabelTelefonoPaciente.setText("Teléfono");

        jTextFieldFechaNacimientoMesPaciente.setEditable(false);
        jTextFieldFechaNacimientoMesPaciente.setText("1");
        jTextFieldFechaNacimientoMesPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaNacimientoMesPacienteActionPerformed(evt);
            }
        });

        jLabelLugarNacimientoPaciente.setText("Lugar nacimiento");

        jLabelDireccionPaciente.setText("Dirección");

        jButtonMenosAnioPaciente.setText("-");
        jButtonMenosAnioPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosAnioPacienteMouseClicked(evt);
            }
        });
        jButtonMenosAnioPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosAnioPacienteActionPerformed(evt);
            }
        });

        jLabelApellidosPaciente.setText("Apellidos");

        jButtonAltaPaciente.setText("Alta");

        jButtonMasDiaPaciente.setText("+");
        jButtonMasDiaPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasDiaPacienteMouseClicked(evt);
            }
        });
        jButtonMasDiaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasDiaPacienteActionPerformed(evt);
            }
        });

        jButtonMenosMesPaciente.setText("-");
        jButtonMenosMesPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosMesPacienteMouseClicked(evt);
            }
        });
        jButtonMenosMesPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosMesPacienteActionPerformed(evt);
            }
        });

        jButtonMenosDiaPaciente.setText("-");
        jButtonMenosDiaPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosDiaPacienteMouseClicked(evt);
            }
        });
        jButtonMenosDiaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosDiaPacienteActionPerformed(evt);
            }
        });

        jLabelEmailPaciente.setText("Email");

        jTextFieldFechaNacimientoDiaPaciente.setEditable(false);
        jTextFieldFechaNacimientoDiaPaciente.setText("1");

        jButtonMasAnioPaciente.setText("+");
        jButtonMasAnioPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasAnioPacienteMouseClicked(evt);
            }
        });
        jButtonMasAnioPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasAnioPacienteActionPerformed(evt);
            }
        });

        jLabelInfoFotoPaciente.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabelInfoFotoPaciente.setText("Tam max 130x150 pix");

        jTextFieldFechaNacimientoAnioPaciente.setText("1950");

        jTextFieldContraseniaPaciente.setColumns(8);

        jButtonMasMesPaciente.setText("+");
        jButtonMasMesPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasMesPacienteMouseClicked(evt);
            }
        });
        jButtonMasMesPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasMesPacienteActionPerformed(evt);
            }
        });

        jLabelFechaNacimientoPaciente.setText("Fecha nacimiento");

        jButtonConsultarPaciente.setText("Consultar");

        jButtonLimpiarPaciente.setText("Limpiar");
        jButtonLimpiarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLimpiarPacienteMouseClicked(evt);
            }
        });
        jButtonLimpiarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarPacienteActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelGestionarPacienteLayout = new org.jdesktop.layout.GroupLayout(jPanelGestionarPaciente);
        jPanelGestionarPaciente.setLayout(jPanelGestionarPacienteLayout);
        jPanelGestionarPacienteLayout.setHorizontalGroup(
            jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelGestionarPacienteLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                        .add(99, 99, 99)
                        .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                                .add(1, 1, 1)
                                .add(jLabelGestionarPaciente4))))
                    .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                        .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelFechaNacimientoPaciente)
                            .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                                .add(jButtonMasDiaPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jButtonMasMesPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jButtonMasAnioPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(jTextFieldFechaNacimientoDiaPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(17, 17, 17)
                                .add(jTextFieldFechaNacimientoMesPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(7, 7, 7)
                                .add(jTextFieldFechaNacimientoAnioPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                                .add(jButtonMenosDiaPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jButtonMenosMesPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jButtonMenosAnioPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(205, 205, 205)
                        .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(jLabelFotografiaPaciente))
                            .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(jLabelInfoFotoPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jButtonFotoPaciente))
                        .add(50, 50, 50)
                        .add(jLabelFotoPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                        .add(jLabelTelefonoPaciente)
                        .add(165, 165, 165)
                        .add(jLabelContraseniaPaciente)
                        .add(109, 109, 109)
                        .add(jLabelLugarNacimientoPaciente))
                    .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                        .add(jTextFieldTelefonoPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(90, 90, 90)
                        .add(jTextFieldContraseniaPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(70, 70, 70)
                        .add(jTextFieldLugarNacimientoPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 300, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                        .add(jTextFieldDireccionPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 370, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(40, 40, 40)
                        .add(jTextFieldEmailPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 289, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                        .add(jLabelDireccionPaciente)
                        .add(350, 350, 350)
                        .add(jLabelEmailPaciente)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 256, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                        .add(jLabelNombrePaciente)
                        .add(200, 200, 200)
                        .add(jLabelApellidosPaciente)
                        .add(291, 291, 291)
                        .add(jLabelDNIPaciente))
                    .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                        .add(jTextFieldNombrePaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 210, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(40, 40, 40)
                        .add(jTextFieldApellidosPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 290, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(60, 60, 60)
                        .add(jTextFieldDNIPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelGestionarPacienteLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 210, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButtonLimpiarPaciente)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonAltaPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonConsultarPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(214, 214, 214)))
                .add(89, 89, 89))
        );
        jPanelGestionarPacienteLayout.setVerticalGroup(
            jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                        .add(39, 39, 39)
                        .add(jLabel3))
                    .add(jLabelGestionarPaciente4))
                .add(18, 18, 18)
                .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelNombrePaciente)
                    .add(jLabelApellidosPaciente)
                    .add(jLabelDNIPaciente))
                .add(14, 14, 14)
                .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextFieldNombrePaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldApellidosPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldDNIPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelDireccionPaciente)
                    .add(jLabelEmailPaciente))
                .add(4, 4, 4)
                .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextFieldDireccionPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldEmailPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(26, 26, 26)
                .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelTelefonoPaciente)
                    .add(jLabelContraseniaPaciente)
                    .add(jLabelLugarNacimientoPaciente))
                .add(4, 4, 4)
                .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextFieldTelefonoPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldContraseniaPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldLugarNacimientoPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                        .add(19, 19, 19)
                        .add(jLabelFechaNacimientoPaciente)
                        .add(4, 4, 4)
                        .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jButtonMasDiaPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonMasMesPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonMasAnioPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTextFieldFechaNacimientoDiaPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextFieldFechaNacimientoMesPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextFieldFechaNacimientoAnioPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(2, 2, 2)
                        .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jButtonMenosDiaPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonMenosMesPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonMenosAnioPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                        .add(30, 30, 30)
                        .add(jLabelFotografiaPaciente)
                        .add(4, 4, 4)
                        .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                                .add(12, 12, 12)
                                .add(jLabelInfoFotoPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jButtonFotoPaciente)))
                    .add(jLabelFotoPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(3, 3, 3)
                .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonLimpiarPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonAltaPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonConsultarPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanelGestionarPaciente.setBounds(1, 0, 900, 530);
        ZonaTrabajo.add(jPanelGestionarPaciente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanelGestionarCitaOnline.setMinimumSize(new java.awt.Dimension(901, 510));
        jPanelGestionarCitaOnline.setPreferredSize(new java.awt.Dimension(901, 531));
        jPanelGestionarCitaOnline.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldMesCita.setEditable(false);
        jTextFieldMesCita.setText("1");
        jTextFieldMesCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMesCitaActionPerformed(evt);
            }
        });
        jPanelGestionarCitaOnline.add(jTextFieldMesCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 372, 33, -1));

        jButtonMenosAnioPersonal.setText("-");
        jButtonMenosAnioPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosAnioPersonalMouseClicked(evt);
            }
        });
        jButtonMenosAnioPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosAnioPersonalActionPerformed(evt);
            }
        });
        jPanelGestionarCitaOnline.add(jButtonMenosAnioPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 402, 50, 40));

        jButtonMasAnioFecha.setText("+");
        jButtonMasAnioFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasAnioFechaMouseClicked(evt);
            }
        });
        jButtonMasAnioFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasAnioFechaActionPerformed(evt);
            }
        });
        jPanelGestionarCitaOnline.add(jButtonMasAnioFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 332, 50, 40));

        jTextFieldAnioCita.setEditable(false);
        jTextFieldAnioCita.setText("1950");
        jTextFieldAnioCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnioCitaActionPerformed(evt);
            }
        });
        jPanelGestionarCitaOnline.add(jTextFieldAnioCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 372, 50, -1));

        jLabelFecha.setText("Fecha cita");
        jPanelGestionarCitaOnline.add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 309, -1, -1));

        jTextFieldDiaCita.setEditable(false);
        jTextFieldDiaCita.setText("1");
        jPanelGestionarCitaOnline.add(jTextFieldDiaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 372, 33, -1));

        jButtonMasMesFecha.setText("+");
        jButtonMasMesFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasMesFechaMouseClicked(evt);
            }
        });
        jButtonMasMesFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasMesFechaActionPerformed(evt);
            }
        });
        jPanelGestionarCitaOnline.add(jButtonMasMesFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 332, 50, 40));

        jButtonMasDiaFecha.setText("+");
        jButtonMasDiaFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasDiaFechaMouseClicked(evt);
            }
        });
        jButtonMasDiaFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasDiaFechaActionPerformed(evt);
            }
        });
        jPanelGestionarCitaOnline.add(jButtonMasDiaFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 332, 50, 40));

        jButtonAltaPersonal.setText("Alta");
        jPanelGestionarCitaOnline.add(jButtonAltaPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 490, 93, 39));

        jButtonMenosDiaFecha.setText("-");
        jButtonMenosDiaFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosDiaFechaMouseClicked(evt);
            }
        });
        jButtonMenosDiaFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosDiaFechaActionPerformed(evt);
            }
        });
        jPanelGestionarCitaOnline.add(jButtonMenosDiaFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 402, 50, 40));

        jButtonMenosMesFecha.setText("-");
        jButtonMenosMesFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosMesFechaMouseClicked(evt);
            }
        });
        jButtonMenosMesFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosMesFechaActionPerformed(evt);
            }
        });
        jPanelGestionarCitaOnline.add(jButtonMenosMesFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 402, 50, 40));
        jPanelGestionarCitaOnline.add(jTextFieldDNIPacienteCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 261, 95, -1));

        jLabelDNIPacienteCita.setText("DNI");
        jPanelGestionarCitaOnline.add(jLabelDNIPacienteCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 267, -1, -1));

        jLabelGestionarPaciente2.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        jLabelGestionarPaciente2.setText("Gestionar Cita");
        jPanelGestionarCitaOnline.add(jLabelGestionarPaciente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel2.setText("_____________________________________________________");
        jPanelGestionarCitaOnline.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jButtonLimpiarPersonal.setText("Limpiar");
        jButtonLimpiarPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLimpiarPersonalMouseClicked(evt);
            }
        });
        jButtonLimpiarPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarPersonalActionPerformed(evt);
            }
        });
        jPanelGestionarCitaOnline.add(jButtonLimpiarPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, -1, 39));

        jButtonConsultarPersonal.setText("Consultar");
        jPanelGestionarCitaOnline.add(jButtonConsultarPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 490, 93, 39));

        jButtonMasHora.setText("+");
        jButtonMasHora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasHoraMouseClicked(evt);
            }
        });
        jButtonMasHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasHoraActionPerformed(evt);
            }
        });
        jPanelGestionarCitaOnline.add(jButtonMasHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 332, 50, 40));

        jButtonMasMinuto.setText("+");
        jButtonMasMinuto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasMinutoMouseClicked(evt);
            }
        });
        jButtonMasMinuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasMinutoActionPerformed(evt);
            }
        });
        jPanelGestionarCitaOnline.add(jButtonMasMinuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 332, 50, 40));

        jTextFieldHoraCita.setEditable(false);
        jTextFieldHoraCita.setText("1");
        jPanelGestionarCitaOnline.add(jTextFieldHoraCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 372, 33, -1));

        jTextFieldMinutoCita.setEditable(false);
        jTextFieldMinutoCita.setText("1");
        jTextFieldMinutoCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMinutoCitaActionPerformed(evt);
            }
        });
        jPanelGestionarCitaOnline.add(jTextFieldMinutoCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 372, 33, -1));

        jButtonMenosHora.setText("-");
        jButtonMenosHora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosHoraMouseClicked(evt);
            }
        });
        jButtonMenosHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosHoraActionPerformed(evt);
            }
        });
        jPanelGestionarCitaOnline.add(jButtonMenosHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 402, 50, 40));

        jButtonMenosMinuto.setText("-");
        jButtonMenosMinuto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosMinutoMouseClicked(evt);
            }
        });
        jButtonMenosMinuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosMinutoActionPerformed(evt);
            }
        });
        jPanelGestionarCitaOnline.add(jButtonMenosMinuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 402, 50, 40));

        jLabelHoraCita.setText("Hora cita");
        jPanelGestionarCitaOnline.add(jLabelHoraCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 309, -1, -1));

        jTextAreaInfo.setBackground(new java.awt.Color(255, 204, 102));
        jTextAreaInfo.setColumns(17);
        jTextAreaInfo.setEditable(false);
        jTextAreaInfo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jTextAreaInfo.setRows(3);
        jTextAreaInfo.setText("Introduce el DNI del paciente, la fecha y una hora para solicitar una cita al paciente \nen el botón \"Alta\". En cambio, si quieres consultar una cita, introduce solamente el \nDNI y dale al botón \"Consultar\".");
        jScrollPane1.setViewportView(jTextAreaInfo);

        jPanelGestionarCitaOnline.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 780, 120));

        jPanelGestionarCitaOnline.setBounds(0, 0, 901, 531);
        ZonaTrabajo.add(jPanelGestionarCitaOnline, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jLabelIcono, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(17, 17, 17)
                .add(jLabelCentroMedico)
                .add(148, 148, 148)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelIconoInicio)
                    .add(jLabelInicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(40, 40, 40)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelIconoAyuda)
                    .add(jLabelAyuda, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(35, 35, 35)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelIconoSalir)
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jLabelSalir)))
                .add(103, 103, 103)
                .add(jPanelUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(13, 13, 13)
                .add(ZonaTrabajo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 920, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(17, 17, 17)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelIcono, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(51, 51, 51)
                        .add(jLabelCentroMedico))
                    .add(layout.createSequentialGroup()
                        .add(58, 58, 58)
                        .add(jLabelIconoInicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(8, 8, 8)
                        .add(jLabelInicio))
                    .add(layout.createSequentialGroup()
                        .add(55, 55, 55)
                        .add(jLabelIconoAyuda, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(8, 8, 8)
                        .add(jLabelAyuda))
                    .add(layout.createSequentialGroup()
                        .add(58, 58, 58)
                        .add(jLabelIconoSalir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(8, 8, 8)
                        .add(jLabelSalir))
                    .add(layout.createSequentialGroup()
                        .add(30, 30, 30)
                        .add(jPanelUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(18, 18, 18)
                .add(ZonaTrabajo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 550, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jLabelIconoInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoInicioMouseEntered
        // TODO add your handling code here:
        jLabelIconoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CentroMedico/Imagenes/Principal/Inicio-Activado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoInicioMouseEntered

    private void jLabelIconoInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoInicioMouseExited
        // TODO add your handling code here:
        jLabelIconoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CentroMedico/Imagenes/Principal/Inicio-Desactivado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoInicioMouseExited

    private void jLabelIconoAyudaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoAyudaMouseExited
        // TODO add your handling code here:
        jLabelIconoAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CentroMedico/Imagenes/Principal/Ayuda-Desactivado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoAyudaMouseExited

    private void jLabelIconoAyudaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoAyudaMouseEntered
        // TODO add your handling code here:
        jLabelIconoAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CentroMedico/Imagenes/Principal/Ayuda-Activado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoAyudaMouseEntered

    private void jLabelIconoSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoSalirMouseExited
        // TODO add your handling code here:
        jLabelIconoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CentroMedico/Imagenes/Principal/Salir-Desactivado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoSalirMouseExited

    private void jLabelIconoSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoSalirMouseEntered
        // TODO add your handling code here:
        jLabelIconoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CentroMedico/Imagenes/Principal/Salir-Activado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoSalirMouseEntered

    private void jLabelIconoSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelIconoSalirMouseClicked

    private void jLabelIconoAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoAyudaMouseClicked
        // TODO add your handling code here:
        new Ayuda().setVisible(true);
    }//GEN-LAST:event_jLabelIconoAyudaMouseClicked

    private void jButtonGestionarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGestionarPacienteMouseClicked
        // TODO add your handling code here:
        mostrarPanel("GestionarPaciente");
    }//GEN-LAST:event_jButtonGestionarPacienteMouseClicked

    private void jButtonGestionarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGestionarPacienteActionPerformed

    private void jLabelIconoInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoInicioMouseClicked
        // TODO add your handling code here:
        mostrarPanel("Principal");
    }//GEN-LAST:event_jLabelIconoInicioMouseClicked

    private void jButtonLimpiarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarPersonalActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonLimpiarPersonalActionPerformed

    private void jButtonMasMesFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasMesFechaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonMasMesFechaActionPerformed

    private void jButtonMasAnioFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasAnioFechaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonMasAnioFechaActionPerformed

    private void jButtonMenosDiaFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosDiaFechaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonMenosDiaFechaActionPerformed

    private void jButtonMenosMesFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosMesFechaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonMenosMesFechaActionPerformed

    private void jButtonMasDiaFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasDiaFechaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonMasDiaFechaActionPerformed

    private void jButtonMenosAnioPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosAnioPersonalActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonMenosAnioPersonalActionPerformed

    private void jTextFieldMesCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMesCitaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldMesCitaActionPerformed

    private void jButtonFotoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFotoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFotoPacienteActionPerformed

    private void jTextFieldFechaNacimientoMesPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaNacimientoMesPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaNacimientoMesPacienteActionPerformed

    private void jButtonMenosAnioPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosAnioPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenosAnioPacienteActionPerformed

    private void jButtonMasDiaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasDiaPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMasDiaPacienteActionPerformed

    private void jButtonMenosMesPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosMesPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenosMesPacienteActionPerformed

    private void jButtonMenosDiaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosDiaPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenosDiaPacienteActionPerformed

    private void jButtonMasAnioPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasAnioPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMasAnioPacienteActionPerformed

    private void jButtonMasMesPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasMesPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMasMesPacienteActionPerformed

    private void jButtonLimpiarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimpiarPacienteActionPerformed

    private void jButtonLimpiarPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLimpiarPersonalMouseClicked
        // TODO add your handling code here:
        limpiarFormulario("GestionarCitaOnline");
    }//GEN-LAST:event_jButtonLimpiarPersonalMouseClicked

    private void jButtonFotoPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFotoPacienteMouseClicked
        // TODO add your handling code here:
        cargarFoto("GestionarPaciente");
    }//GEN-LAST:event_jButtonFotoPacienteMouseClicked

    private void jButtonLimpiarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLimpiarPacienteMouseClicked
        // TODO add your handling code here:
        limpiarFormulario("GestionarPaciente");
    }//GEN-LAST:event_jButtonLimpiarPacienteMouseClicked

    private void jButtonMasDiaPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasDiaPacienteMouseClicked
        // TODO add your handling code here:
        int num = 0;
        
        num = Integer.parseInt(jTextFieldFechaNacimientoDiaPaciente.getText());

        if(num < 31)
            num ++;
        
        String numString;
        numString = String.valueOf(num);
        jTextFieldFechaNacimientoDiaPaciente.setText(numString);
    }//GEN-LAST:event_jButtonMasDiaPacienteMouseClicked

    private void jButtonMenosDiaPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosDiaPacienteMouseClicked
        // TODO add your handling code here:
        int num = 0;

        num = Integer.parseInt(jTextFieldFechaNacimientoDiaPaciente.getText());

        if(num > 1)
            num --;

        String numString;
        numString = String.valueOf(num);
        jTextFieldFechaNacimientoDiaPaciente.setText(numString);
    }//GEN-LAST:event_jButtonMenosDiaPacienteMouseClicked

    private void jButtonMasMesPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasMesPacienteMouseClicked
        // TODO add your handling code here:
        int num = 0;

        num = Integer.parseInt(jTextFieldFechaNacimientoMesPaciente.getText());

        if(num < 12)
            num ++;

        String numString;
        numString = String.valueOf(num);
        jTextFieldFechaNacimientoMesPaciente.setText(numString);
    }//GEN-LAST:event_jButtonMasMesPacienteMouseClicked

    private void jButtonMenosMesPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosMesPacienteMouseClicked
        // TODO add your handling code here:
        int num = 0;

        num = Integer.parseInt(jTextFieldFechaNacimientoMesPaciente.getText());

        if(num > 1)
            num --;

        String numString;
        numString = String.valueOf(num);
        jTextFieldFechaNacimientoMesPaciente.setText(numString);
    }//GEN-LAST:event_jButtonMenosMesPacienteMouseClicked

    private void jButtonMasAnioPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasAnioPacienteMouseClicked
        // TODO add your handling code here:
        int num = 0;
        int anioActual = 0;

        num = Integer.parseInt(jTextFieldFechaNacimientoAnioPaciente.getText());

        Calendar fechaActual = Calendar.getInstance();
        anioActual = fechaActual.get(Calendar.YEAR);

        if(num < anioActual)
            num ++;

        String numString;
        numString = String.valueOf(num);
        jTextFieldFechaNacimientoAnioPaciente.setText(numString);
    }//GEN-LAST:event_jButtonMasAnioPacienteMouseClicked

    private void jButtonMenosAnioPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosAnioPacienteMouseClicked
        // TODO add your handling code here:
        int num = 0;

        num = Integer.parseInt(jTextFieldFechaNacimientoAnioPaciente.getText());

        if(num > 1900)
            num --;

        String numString;
        numString = String.valueOf(num);
        jTextFieldFechaNacimientoAnioPaciente.setText(numString);
    }//GEN-LAST:event_jButtonMenosAnioPacienteMouseClicked

    private void jButtonMasDiaFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasDiaFechaMouseClicked
        // TODO add your handling code here:
        int num = 0;

        num = Integer.parseInt(jTextFieldDiaCita.getText());

        if(num < 31)
            num ++;

        String numString;
        numString = String.valueOf(num);
        jTextFieldDiaCita.setText(numString);
    }//GEN-LAST:event_jButtonMasDiaFechaMouseClicked

    private void jButtonMenosDiaFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosDiaFechaMouseClicked
        // TODO add your handling code here:
        int num = 0;

        num = Integer.parseInt(jTextFieldDiaCita.getText());

        if(num > 1)
            num --;

        String numString;
        numString = String.valueOf(num);
        jTextFieldDiaCita.setText(numString);
    }//GEN-LAST:event_jButtonMenosDiaFechaMouseClicked

    private void jButtonMasMesFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasMesFechaMouseClicked
        // TODO add your handling code here:
        int num = 0;

        num = Integer.parseInt(jTextFieldMesCita.getText());

        if(num < 12)
            num ++;

        String numString;
        numString = String.valueOf(num);
        jTextFieldMesCita.setText(numString);
    }//GEN-LAST:event_jButtonMasMesFechaMouseClicked

    private void jButtonMenosMesFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosMesFechaMouseClicked
        // TODO add your handling code here:
        int num = 0;

        num = Integer.parseInt(jTextFieldMesCita.getText());

        if(num > 1)
            num --;

        String numString;
        numString = String.valueOf(num);
        jTextFieldMesCita.setText(numString);
    }//GEN-LAST:event_jButtonMenosMesFechaMouseClicked

    private void jButtonMasAnioFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasAnioFechaMouseClicked
        // TODO add your handling code here:
        int num = 0;
        int anioActual = 0;

        num = Integer.parseInt(jTextFieldAnioCita.getText());

        Calendar fechaActual = Calendar.getInstance();
        anioActual = fechaActual.get(Calendar.YEAR);

        if(num < anioActual)
            num ++;

        String numString;
        numString = String.valueOf(num);
        jTextFieldAnioCita.setText(numString);
    }//GEN-LAST:event_jButtonMasAnioFechaMouseClicked

    private void jButtonMenosAnioPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosAnioPersonalMouseClicked
        // TODO add your handling code here:
        int num = 0;
        num = Integer.parseInt(jTextFieldAnioCita.getText());

        if(num > 1900)
            num --;

        String numString;
        numString = String.valueOf(num);
        jTextFieldAnioCita.setText(numString);
    }//GEN-LAST:event_jButtonMenosAnioPersonalMouseClicked

    private void jButtonGestionarCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGestionarCitaMouseClicked
        // TODO add your handling code here:
        mostrarPanel("GestionarCitaOnline");
    }//GEN-LAST:event_jButtonGestionarCitaMouseClicked

    private void jButtonMasHoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasHoraMouseClicked
        // TODO add your handling code here:
        int hora = 0;

        hora = Integer.parseInt(jTextFieldHoraCita.getText());

        if(hora < 24){
            hora ++;
            }else{
                hora = 0;
            }

        String numString;
        numString = String.valueOf(hora);
        jTextFieldHoraCita.setText(numString);
    }//GEN-LAST:event_jButtonMasHoraMouseClicked

    private void jButtonMasHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMasHoraActionPerformed

    private void jButtonMasMinutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasMinutoMouseClicked
        // TODO add your handling code here:
        int minuto = 0;

        minuto = Integer.parseInt(jTextFieldMinutoCita.getText());

        if(minuto < 60)
            minuto ++;

        String numString;
        numString = String.valueOf(minuto);
        jTextFieldMinutoCita.setText(numString);
    }//GEN-LAST:event_jButtonMasMinutoMouseClicked

    private void jButtonMasMinutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasMinutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMasMinutoActionPerformed

    private void jTextFieldMinutoCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMinutoCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMinutoCitaActionPerformed

    private void jButtonMenosHoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosHoraMouseClicked
        // TODO add your handling code here:
        int hora = 0;

        hora = Integer.parseInt(jTextFieldHoraCita.getText());

        if(hora > 0){
            hora --;
            }else{
                hora = 24;
            }

        String numString;
        numString = String.valueOf(hora);
        jTextFieldHoraCita.setText(numString);
    }//GEN-LAST:event_jButtonMenosHoraMouseClicked

    private void jButtonMenosHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenosHoraActionPerformed

    private void jButtonMenosMinutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosMinutoMouseClicked
        // TODO add your handling code here:
        int minuto = 0;

        minuto = Integer.parseInt(jTextFieldMinutoCita.getText());

        if(minuto > 0)
            minuto --;

        String numString;
        numString = String.valueOf(minuto);
        jTextFieldMinutoCita.setText(numString);
    }//GEN-LAST:event_jButtonMenosMinutoMouseClicked

    private void jButtonMenosMinutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosMinutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenosMinutoActionPerformed

    private void jTextFieldAnioCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnioCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAnioCitaActionPerformed


    /*Comprueba que la fecha introducida es correcta
     * 
     *@param persona, string que indica si se trata del formulario de Paciente o Personal
     *@return booleano diciendo si es válido o no
     */
    private boolean compruebaFecha(String persona){
        
        int dia = 0;
        int mes = 0;
        int anio = 0;
        int diaActual;
        int mesActual;
        int anioActual;

        if(persona.equals("GestionarPaciente")){
            dia = Integer.parseInt(jTextFieldFechaNacimientoDiaPaciente.getText());
            mes = Integer.parseInt(jTextFieldFechaNacimientoMesPaciente.getText());
            anio = Integer.parseInt(jTextFieldFechaNacimientoAnioPaciente.getText());
        }

        if(persona.equals("GestionarCitaOnline")){
            dia = Integer.parseInt(jTextFieldDiaCita.getText());
            mes = Integer.parseInt(jTextFieldMesCita.getText());
            anio = Integer.parseInt(jTextFieldAnioCita.getText());
        }

        Calendar fechaActual = Calendar.getInstance();
        diaActual = fechaActual.get(Calendar.DATE);
        mesActual = fechaActual.get(Calendar.MONTH);
        anioActual = fechaActual.get(Calendar.YEAR);


        /**Si se sale de los rangos*/
        if((dia <= 0)
                || (dia > 31)
                || (mes <= 0)
                || (mes > 12)
                || (anio < 1900)
                || (anio > anioActual) ){
            return false;
        }

        /**Si ha nacido en el año actual, hay que ver que el mes no sea mayor que el actual*/
        /**Si ha nacido en el año y mes actual, hay que comprobar que el dia sea menor que el actual*/
        if(anio == anioActual){
            if(mes > mesActual){
                return false;
            } else{
                if(dia > diaActual){
                    return false;
                }
            }
        }

        /**Si estamos en un mes que tiene 30 días o 29 en el caso de febrero, hay que comprobar que no se pase*/
        if(mes%2 == 0){
            if((mes == 2) && (dia >29)){
                return false;
            }else{
                if(dia > 30){
                    return false;
                }
            }
        }

        return true;

    }


     /*Borra el formulario elegido
     *
     *@param persona, string que indica si se trata del formulario de Paciente o Personal
     */
    private void limpiarFormulario(String persona){

        String diaActual;
        String mesActual;
        String anioActual;
        String horaActual;
        String minutoActual;

        Calendar fechaActual = Calendar.getInstance();
        diaActual = Integer.toString(fechaActual.get(Calendar.DATE));
        mesActual = Integer.toString(fechaActual.get(Calendar.MONTH));
        anioActual = Integer.toString(fechaActual.get(Calendar.YEAR));
        horaActual = Integer.toString(fechaActual.get(Calendar.HOUR_OF_DAY));
        minutoActual = Integer.toString(fechaActual.get(Calendar.MINUTE));


        if(persona.equals("GestionarPaciente")){
            jTextFieldNombrePaciente.setText("");
            jTextFieldApellidosPaciente.setText("");
            jTextFieldDNIPaciente.setText("");
            jTextFieldDireccionPaciente.setText("");
            jTextFieldEmailPaciente.setText("");
            jTextFieldTelefonoPaciente.setText("");
            jTextFieldContraseniaPaciente.setText("");
            jTextFieldLugarNacimientoPaciente.setText("");
            jTextFieldFechaNacimientoDiaPaciente.setText(diaActual);
            jTextFieldFechaNacimientoMesPaciente.setText(mesActual);
            jTextFieldFechaNacimientoAnioPaciente.setText(anioActual);
            jLabelFotoPaciente.setIcon(null);
        }

        if(persona.equals("GestionarCitaOnline")){
            jTextFieldDNIPacienteCita.setText("");
            jTextFieldDiaCita.setText(diaActual);
            jTextFieldMesCita.setText(mesActual);
            jTextFieldAnioCita.setText(anioActual);
            jTextFieldHoraCita.setText(horaActual);
            jTextFieldMinutoCita.setText(minutoActual);
        }
    }

  
    /*Muestra el panel elegido en ZonaTrabajo
     *
     *@param panel, string que indica el panel a mostrar
     */
    private void mostrarPanel(String panel){

        if(panel.equals("Principal")){
            /**Hacemos visible el panel seleccionado*/
            jPanelPrincipal.setVisible(true);
            jPanelGestionarPaciente.setVisible(false);
            jPanelGestionarCitaOnline.setVisible(false);


            /**Activamos el marco*/
            jPanelPrincipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
            jPanelGestionarPaciente.setBorder(null);
            jPanelGestionarCitaOnline.setBorder(null);
        }

        if(panel.equals("GestionarPaciente")){
            
            /**Limpiamos posibles datos introducidos anteriormente*/
            limpiarFormulario("GestionarPaciente");

            /**Hacemos visible el panel seleccionado*/
            jPanelPrincipal.setVisible(false);
            jPanelGestionarPaciente.setVisible(true);
            jPanelGestionarCitaOnline.setVisible(false);

            /**Activamos el marco*/
            jPanelPrincipal.setBorder(null);
            jPanelGestionarPaciente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
            jPanelGestionarCitaOnline.setBorder(null);
        }

        if(panel.equals("GestionarCitaOnline")){

            /**Limpiamos posibles datos introducidos anteriormente*/
            limpiarFormulario("GestionarCitaOnline");

            /**Hacemos visible el panel seleccionado*/
            jPanelPrincipal.setVisible(false);
            jPanelGestionarPaciente.setVisible(false);
            jPanelGestionarCitaOnline.setVisible(true);


            /**Activamos el marco*/
            jPanelPrincipal.setBorder(null);
            jPanelGestionarPaciente.setBorder(null);
            jPanelGestionarCitaOnline.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        }



    }


     /*Carga la foto en el formulario pasado por parámetro
     *
     *@param formulario, string que indica el formulario donde cargar la foto
     */
    private void cargarFoto(String formulario){

        if(formulario.equals("GestionarPaciente")){
            JFileChooser dlg = new JFileChooser();
            int resp = dlg.showOpenDialog(this);
            if (resp == JFileChooser.APPROVE_OPTION){
                try{
                    ImageIcon icono = new ImageIcon(dlg.getSelectedFile().getCanonicalPath());
                    Image imagen = icono.getImage();
                    ImageIcon aescala = new ImageIcon(imagen.getScaledInstance(130,150,Image.SCALE_SMOOTH));
                    jLabelFotoPaciente.setIcon(aescala); // NOI18N
                }
                catch(Exception ex){
                    System.err.print("Error al leer el archivo");
                }
            }
        }

    }


    
    // @param args the command line arguments
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Paciente("Paciente", "paciente").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane ZonaTrabajo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAltaPaciente;
    private javax.swing.JButton jButtonAltaPersonal;
    private javax.swing.JButton jButtonConsultarPaciente;
    private javax.swing.JButton jButtonConsultarPersonal;
    private javax.swing.JButton jButtonFotoPaciente;
    private javax.swing.JButton jButtonGestionarCita;
    private javax.swing.JButton jButtonGestionarPaciente;
    private javax.swing.JButton jButtonLimpiarPaciente;
    private javax.swing.JButton jButtonLimpiarPersonal;
    private javax.swing.JButton jButtonMasAnioFecha;
    private javax.swing.JButton jButtonMasAnioPaciente;
    private javax.swing.JButton jButtonMasDiaFecha;
    private javax.swing.JButton jButtonMasDiaPaciente;
    private javax.swing.JButton jButtonMasHora;
    private javax.swing.JButton jButtonMasMesFecha;
    private javax.swing.JButton jButtonMasMesPaciente;
    private javax.swing.JButton jButtonMasMinuto;
    private javax.swing.JButton jButtonMenosAnioPaciente;
    private javax.swing.JButton jButtonMenosAnioPersonal;
    private javax.swing.JButton jButtonMenosDiaFecha;
    private javax.swing.JButton jButtonMenosDiaPaciente;
    private javax.swing.JButton jButtonMenosHora;
    private javax.swing.JButton jButtonMenosMesFecha;
    private javax.swing.JButton jButtonMenosMesPaciente;
    private javax.swing.JButton jButtonMenosMinuto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelApellidosPaciente;
    private javax.swing.JLabel jLabelAyuda;
    private javax.swing.JLabel jLabelCentroMedico;
    private javax.swing.JLabel jLabelContraseniaPaciente;
    private javax.swing.JLabel jLabelDNIPaciente;
    private javax.swing.JLabel jLabelDNIPacienteCita;
    private javax.swing.JLabel jLabelDireccionPaciente;
    private javax.swing.JLabel jLabelEmailPaciente;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelFechaNacimientoPaciente;
    private javax.swing.JLabel jLabelFotoPaciente;
    private javax.swing.JLabel jLabelFotografiaPaciente;
    private javax.swing.JLabel jLabelGestionarCita1;
    private javax.swing.JLabel jLabelGestionarPaciente2;
    private javax.swing.JLabel jLabelGestionarPaciente3;
    private javax.swing.JLabel jLabelGestionarPaciente4;
    private javax.swing.JLabel jLabelHoraCita;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JLabel jLabelIconoAyuda;
    private javax.swing.JLabel jLabelIconoInicio;
    private javax.swing.JLabel jLabelIconoSalir;
    private javax.swing.JLabel jLabelInfoFotoPaciente;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelLugarNacimientoPaciente;
    private javax.swing.JLabel jLabelNombrePaciente;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JLabel jLabelSalir;
    private javax.swing.JLabel jLabelTelefonoPaciente;
    private javax.swing.JLabel jLabelTipoUsuario;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanelGestionarCitaOnline;
    private javax.swing.JPanel jPanelGestionarPaciente;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaInfo;
    private javax.swing.JTextField jTextFieldAnioCita;
    private javax.swing.JTextField jTextFieldApellidosPaciente;
    private javax.swing.JTextField jTextFieldContraseniaPaciente;
    private javax.swing.JTextField jTextFieldDNIPaciente;
    private javax.swing.JTextField jTextFieldDNIPacienteCita;
    private javax.swing.JTextField jTextFieldDiaCita;
    private javax.swing.JTextField jTextFieldDireccionPaciente;
    private javax.swing.JTextField jTextFieldEmailPaciente;
    private javax.swing.JTextField jTextFieldFechaNacimientoAnioPaciente;
    private javax.swing.JTextField jTextFieldFechaNacimientoDiaPaciente;
    private javax.swing.JTextField jTextFieldFechaNacimientoMesPaciente;
    private javax.swing.JTextField jTextFieldHoraCita;
    private javax.swing.JTextField jTextFieldLugarNacimientoPaciente;
    private javax.swing.JTextField jTextFieldMesCita;
    private javax.swing.JTextField jTextFieldMinutoCita;
    private javax.swing.JTextField jTextFieldNombrePaciente;
    private javax.swing.JTextField jTextFieldTelefonoPaciente;
    // End of variables declaration//GEN-END:variables

}
