/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal_Administrador.java
 *
 * Created on 16-mar-2011, 18:27:18
 */

package Interfaz;

import java.awt.Image;
import CentroMedico.*;
import BaseDatos.*;
import Controlador.GestorPersonal;
import Controlador.GestorPruebas;
import java.util.Calendar.*;
import java.util.Calendar;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;



/**
 *
 * @author Adrian
 *
 */
public class UI_Radiologo extends javax.swing.JFrame {

    GestorPruebas gp = new GestorPruebas();
    GestorPersonal gesPer = new GestorPersonal();
    /** Creates new form Principal_Administrador */
    public UI_Radiologo() {
        initComponents();
    }

    public UI_Radiologo(Usuario usu, String tipoUsuario) throws SQLException{
        initComponents();

        /**Ponemos las etiquetas del usuario que ha entrado*/
        jLabelNombreUsuario.setText(usu.getNombre());
        jLabelTipoUsuario.setText(tipoUsuario);

        /**Mostramos el panel Principal*/
        mostrarPanel("Principal");
        mostrarDatosPerso(usu);
    

        /**Cargamos la foto de login*/
        jLabelTipoUsuarioIdentificado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Tipo-Usuario-Personal.png"))); // NOI18N

        /**Enlazamos grupo botones de GestionarPersonal y ConsultarTurno*/

        buttonGroup1.add(jRadioButtonManiana);
        buttonGroup1.add(jRadioButtonTarde1);
        buttonGroup1.add(jRadioButtonNoche);
        jRadioButtonManiana.setSelected(true);

        buttonGroup2.add(jRadioButtonAnalista);
        buttonGroup2.add(jRadioButtonFarmaceutico);
        buttonGroup2.add(jRadioButtonMedico);
        buttonGroup2.add(jRadioButtonRadiologo);
        jRadioButtonRadiologo.setSelected(true);

        buttonGroup3.add(jRadioButtonRadiologia);
        buttonGroup3.add(jRadioButtonResonancia);
        jRadioButtonRadiologia.setSelected(true);


        jLabelError.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabelCentroMedico = new javax.swing.JLabel();
        jLabelIconoInicio = new javax.swing.JLabel();
        jLabelInicio = new javax.swing.JLabel();
        jLabelIconoAyuda = new javax.swing.JLabel();
        jLabelIconoSalir = new javax.swing.JLabel();
        jLabelAyuda = new javax.swing.JLabel();
        jLabelSalir = new javax.swing.JLabel();
        jLabelIcono = new javax.swing.JLabel();
        ZonaTrabajo = new javax.swing.JLayeredPane();
        jPanelPrincipal = new javax.swing.JPanel();
        jButtonConsultarDatosPersonales = new javax.swing.JButton();
        jLabelGestionarPaciente3 = new javax.swing.JLabel();
        jLabelConsultarTurno = new javax.swing.JLabel();
        jButtonGestionarCita = new javax.swing.JButton();
        jButtonAlmacenarResultado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelConsultarDatosPersonales = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelGestionarPaciente4 = new javax.swing.JLabel();
        jTextFieldNombrePersonal = new javax.swing.JTextField();
        jLabelFotoPersonal = new javax.swing.JLabel();
        jTextFieldTelefonoPersonal = new javax.swing.JTextField();
        jLabelContraseniaPersonal = new javax.swing.JLabel();
        jTextFieldDNIPersonal = new javax.swing.JTextField();
        jLabelNombrePersonal = new javax.swing.JLabel();
        jLabelFotografiaersonal = new javax.swing.JLabel();
        jLabelDNIPersonal = new javax.swing.JLabel();
        jTextFieldLugarNacimientoPersonal = new javax.swing.JTextField();
        jLabelTelefonoPersonal = new javax.swing.JLabel();
        jLabelLugarNacimientoPersonal = new javax.swing.JLabel();
        jLabelDireccionPersonal = new javax.swing.JLabel();
        jLabelApellidosPersonal = new javax.swing.JLabel();
        jTextFieldApellidosPersonal = new javax.swing.JTextField();
        jLabelEmailPersonal = new javax.swing.JLabel();
        jTextFieldDireccionPersonal = new javax.swing.JTextField();
        jTextFieldEmailPersonal = new javax.swing.JTextField();
        jTextFieldContraseniaPersonal = new javax.swing.JTextField();
        jLabelFechaNacimientoPersonal = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jRadioButtonFarmaceutico = new javax.swing.JRadioButton();
        jRadioButtonAnalista = new javax.swing.JRadioButton();
        jRadioButtonRadiologo = new javax.swing.JRadioButton();
        jRadioButtonMedico = new javax.swing.JRadioButton();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();
        jPanelConsultarTurno = new javax.swing.JPanel();
        jLabelDNITurno = new javax.swing.JLabel();
        jTextFieldDNIGestionarTurno = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaInfoConsultaTurno = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaInfoTurno = new javax.swing.JTextArea();
        jLabelGestionarPaciente6 = new javax.swing.JLabel();
        jTextFieldInicioTurno = new javax.swing.JTextField();
        jLabelFechaInicioTurno = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldFinTurno = new javax.swing.JTextField();
        jLabelFechaFinTurno = new javax.swing.JLabel();
        jLabelTurnoTrabajo = new javax.swing.JLabel();
        jRadioButtonManiana = new javax.swing.JRadioButton();
        jRadioButtonTarde1 = new javax.swing.JRadioButton();
        jRadioButtonNoche = new javax.swing.JRadioButton();
        jPanelAlmacenarResultados = new javax.swing.JPanel();
        jLabelGestionarPaciente7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelAlmacenarDni = new javax.swing.JLabel();
        jTextFieldAlmacenarDni = new javax.swing.JTextField();
        jRadioButtonRadiologia = new javax.swing.JRadioButton();
        jRadioButtonResonancia = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelImagenes = new javax.swing.JLabel();
        scrollPaneImagenes = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListImagenes = new javax.swing.JList();
        jLabelComentarios = new javax.swing.JLabel();
        scrollPaneComentarios = new java.awt.ScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaComentario = new javax.swing.JTextArea();
        jButtonAnadirImagen = new javax.swing.JButton();
        jButtonAlmacenarResultadoRadiologo = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();
        jLabelErrorDNI = new javax.swing.JLabel();
        jPanelUsuario = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelTipoUsuario = new javax.swing.JLabel();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jLabelTipoUsuarioIdentificado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 102));
        setMinimumSize(new java.awt.Dimension(931, 715));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelCentroMedico.setText("Centro médico");
        getContentPane().add(jLabelCentroMedico);
        jLabelCentroMedico.setBounds(177, 68, 120, 14);

        jLabelIconoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Inicio-Desactivado.png"))); // NOI18N
        jLabelIconoInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconoInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIconoInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIconoInicioMouseExited(evt);
            }
        });
        getContentPane().add(jLabelIconoInicio);
        jLabelIconoInicio.setBounds(420, 70, 44, 47);

        jLabelInicio.setText("Inicio");
        getContentPane().add(jLabelInicio);
        jLabelInicio.setBounds(420, 120, 44, 14);

        jLabelIconoAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Ayuda-Desactivado.png"))); // NOI18N
        jLabelIconoAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconoAyudaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIconoAyudaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIconoAyudaMouseEntered(evt);
            }
        });
        getContentPane().add(jLabelIconoAyuda);
        jLabelIconoAyuda.setBounds(500, 70, 44, 47);

        jLabelIconoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Salir-Desactivado.png"))); // NOI18N
        jLabelIconoSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconoSalirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIconoSalirMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIconoSalirMouseEntered(evt);
            }
        });
        getContentPane().add(jLabelIconoSalir);
        jLabelIconoSalir.setBounds(580, 70, 43, 47);

        jLabelAyuda.setText("Ayuda");
        getContentPane().add(jLabelAyuda);
        jLabelAyuda.setBounds(500, 120, 44, 14);

        jLabelSalir.setText("Salir");
        getContentPane().add(jLabelSalir);
        jLabelSalir.setBounds(590, 120, 40, 14);

        jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Intro/Logo-Centro-Medico.png"))); // NOI18N
        getContentPane().add(jLabelIcono);
        jLabelIcono.setBounds(20, 17, 140, 150);

        ZonaTrabajo.setMinimumSize(new java.awt.Dimension(902, 520));
        ZonaTrabajo.setPreferredSize(new java.awt.Dimension(912, 530));

        jPanelPrincipal.setAlignmentX(1.0F);
        jPanelPrincipal.setAlignmentY(0.0F);
        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(901, 531));

        jButtonConsultarDatosPersonales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Tipo.png"))); // NOI18N
        jButtonConsultarDatosPersonales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConsultarDatosPersonalesMouseClicked(evt);
            }
        });
        jButtonConsultarDatosPersonales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarDatosPersonalesActionPerformed(evt);
            }
        });

        jLabelGestionarPaciente3.setText("Consultar datos personales");

        jLabelConsultarTurno.setText("Consultar turno");

        jButtonGestionarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Cita.png"))); // NOI18N
        jButtonGestionarCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGestionarCitaMouseClicked(evt);
            }
        });
        jButtonGestionarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionarCitaActionPerformed(evt);
            }
        });

        jButtonAlmacenarResultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/AlmacenarResultados.png"))); // NOI18N
        jButtonAlmacenarResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAlmacenarResultadoMouseClicked(evt);
            }
        });

        jLabel1.setText("Almacenar resultados");

        org.jdesktop.layout.GroupLayout jPanelPrincipalLayout = new org.jdesktop.layout.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelPrincipalLayout.createSequentialGroup()
                .add(jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelPrincipalLayout.createSequentialGroup()
                        .add(jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanelPrincipalLayout.createSequentialGroup()
                                .add(56, 56, 56)
                                .add(jLabelGestionarPaciente3))
                            .add(jPanelPrincipalLayout.createSequentialGroup()
                                .add(47, 47, 47)
                                .add(jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jButtonAlmacenarResultado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 193, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jButtonConsultarDatosPersonales, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 194, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanelPrincipalLayout.createSequentialGroup()
                                .add(121, 121, 121)
                                .add(jLabelConsultarTurno))
                            .add(jPanelPrincipalLayout.createSequentialGroup()
                                .add(95, 95, 95)
                                .add(jButtonGestionarCita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 194, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(jPanelPrincipalLayout.createSequentialGroup()
                        .add(67, 67, 67)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(380, Short.MAX_VALUE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                .add(29, 29, 29)
                .add(jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jButtonGestionarCita, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .add(jButtonConsultarDatosPersonales, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelGestionarPaciente3)
                    .add(jLabelConsultarTurno))
                .add(23, 23, 23)
                .add(jButtonAlmacenarResultado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(145, 145, 145))
        );

        jPanelPrincipal.setBounds(-9, 1, 910, 540);
        ZonaTrabajo.add(jPanelPrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanelConsultarDatosPersonales.setPreferredSize(new java.awt.Dimension(901, 531));
        jPanelConsultarDatosPersonales.setLayout(null);

        jLabel3.setText("___________________________________________________________________");
        jPanelConsultarDatosPersonales.add(jLabel3);
        jLabel3.setBounds(256, 59, 402, 14);

        jLabelGestionarPaciente4.setFont(new java.awt.Font("Lucida Grande", 1, 48));
        jLabelGestionarPaciente4.setText("Gestionar Personal");
        jPanelConsultarDatosPersonales.add(jLabelGestionarPaciente4);
        jLabelGestionarPaciente4.setBounds(257, 20, 440, 62);

        jTextFieldNombrePersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombrePersonalKeyTyped(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jTextFieldNombrePersonal);
        jTextFieldNombrePersonal.setBounds(157, 126, 210, 20);

        jLabelFotoPersonal.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFotoPersonal.setForeground(new java.awt.Color(255, 255, 255));
        jPanelConsultarDatosPersonales.add(jLabelFotoPersonal);
        jLabelFotoPersonal.setBounds(660, 360, 150, 150);

        jTextFieldTelefonoPersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelefonoPersonalKeyTyped(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jTextFieldTelefonoPersonal);
        jTextFieldTelefonoPersonal.setBounds(157, 270, 130, 20);

        jLabelContraseniaPersonal.setText("Contraseña");
        jPanelConsultarDatosPersonales.add(jLabelContraseniaPersonal);
        jLabelContraseniaPersonal.setBounds(729, 250, 100, 14);

        jTextFieldDNIPersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDNIPersonalKeyTyped(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jTextFieldDNIPersonal);
        jTextFieldDNIPersonal.setBounds(757, 126, 95, 20);

        jLabelNombrePersonal.setText("Nombre");
        jPanelConsultarDatosPersonales.add(jLabelNombrePersonal);
        jLabelNombrePersonal.setBounds(157, 96, 80, 14);

        jLabelFotografiaersonal.setText("Fotografía");
        jPanelConsultarDatosPersonales.add(jLabelFotografiaersonal);
        jLabelFotografiaersonal.setBounds(710, 330, 100, 14);

        jLabelDNIPersonal.setText("DNI");
        jPanelConsultarDatosPersonales.add(jLabelDNIPersonal);
        jLabelDNIPersonal.setBounds(757, 96, 40, 14);

        jTextFieldLugarNacimientoPersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLugarNacimientoPersonalKeyTyped(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jTextFieldLugarNacimientoPersonal);
        jTextFieldLugarNacimientoPersonal.setBounds(350, 270, 300, 20);

        jLabelTelefonoPersonal.setText("Teléfono");
        jPanelConsultarDatosPersonales.add(jLabelTelefonoPersonal);
        jLabelTelefonoPersonal.setBounds(157, 250, 70, 14);

        jLabelLugarNacimientoPersonal.setText("Lugar nacimiento");
        jPanelConsultarDatosPersonales.add(jLabelLugarNacimientoPersonal);
        jLabelLugarNacimientoPersonal.setBounds(350, 250, 140, 14);

        jLabelDireccionPersonal.setText("Dirección");
        jPanelConsultarDatosPersonales.add(jLabelDireccionPersonal);
        jLabelDireccionPersonal.setBounds(157, 172, 80, 14);

        jLabelApellidosPersonal.setText("Apellidos");
        jPanelConsultarDatosPersonales.add(jLabelApellidosPersonal);
        jLabelApellidosPersonal.setBounds(407, 96, 80, 14);

        jTextFieldApellidosPersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldApellidosPersonalKeyTyped(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jTextFieldApellidosPersonal);
        jTextFieldApellidosPersonal.setBounds(407, 126, 290, 20);

        jLabelEmailPersonal.setText("Email");
        jPanelConsultarDatosPersonales.add(jLabelEmailPersonal);
        jLabelEmailPersonal.setBounds(567, 172, 80, 14);

        jTextFieldDireccionPersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDireccionPersonalKeyTyped(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jTextFieldDireccionPersonal);
        jTextFieldDireccionPersonal.setBounds(157, 192, 370, 20);

        jTextFieldEmailPersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEmailPersonalKeyTyped(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jTextFieldEmailPersonal);
        jTextFieldEmailPersonal.setBounds(567, 192, 289, 20);

        jTextFieldContraseniaPersonal.setColumns(8);
        jPanelConsultarDatosPersonales.add(jTextFieldContraseniaPersonal);
        jTextFieldContraseniaPersonal.setBounds(729, 270, 70, 20);

        jLabelFechaNacimientoPersonal.setText("Fecha nacimiento");
        jPanelConsultarDatosPersonales.add(jLabelFechaNacimientoPersonal);
        jLabelFechaNacimientoPersonal.setBounds(157, 317, 140, 14);

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGuardarMouseClicked(evt);
            }
        });
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jButtonGuardar);
        jButtonGuardar.setBounds(430, 460, 130, 39);

        jLabel8.setText("Tipo personal");
        jPanelConsultarDatosPersonales.add(jLabel8);
        jLabel8.setBounds(390, 330, 110, 14);

        jRadioButtonFarmaceutico.setText("Farmacéutico");
        jRadioButtonFarmaceutico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFarmaceuticoActionPerformed(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jRadioButtonFarmaceutico);
        jRadioButtonFarmaceutico.setBounds(390, 370, 130, 23);

        jRadioButtonAnalista.setText("Analista");
        jPanelConsultarDatosPersonales.add(jRadioButtonAnalista);
        jRadioButtonAnalista.setBounds(390, 350, 100, 23);

        jRadioButtonRadiologo.setText("Radiólogo");
        jRadioButtonRadiologo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRadiologoActionPerformed(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jRadioButtonRadiologo);
        jRadioButtonRadiologo.setBounds(390, 410, 120, 23);

        jRadioButtonMedico.setText("Médico");
        jRadioButtonMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMedicoActionPerformed(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jRadioButtonMedico);
        jRadioButtonMedico.setBounds(390, 390, 110, 23);
        jPanelConsultarDatosPersonales.add(dateChooserCombo2);
        dateChooserCombo2.setBounds(160, 340, 155, 20);

        jPanelConsultarDatosPersonales.setBounds(-60, -15, 960, 830);
        ZonaTrabajo.add(jPanelConsultarDatosPersonales, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanelConsultarTurno.setMinimumSize(new java.awt.Dimension(901, 510));
        jPanelConsultarTurno.setPreferredSize(new java.awt.Dimension(901, 531));

        jLabelDNITurno.setText("DNI");

        jTextFieldDNIGestionarTurno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDNIGestionarTurnoKeyTyped(evt);
            }
        });

        jTextAreaInfoConsultaTurno.setBackground(new java.awt.Color(255, 204, 102));
        jTextAreaInfoConsultaTurno.setColumns(17);
        jTextAreaInfoConsultaTurno.setEditable(false);
        jTextAreaInfoConsultaTurno.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        jTextAreaInfoConsultaTurno.setRows(3);
        jTextAreaInfoConsultaTurno.setText("Introduce el DNI del personal, una fecha y las horas que trabaja el personal para guardar\nsu turno. Si introduces un DNI y pulsas consultar se sabe el turno del DNI.");
        jScrollPane4.setViewportView(jTextAreaInfoConsultaTurno);

        jTextAreaInfoTurno.setBackground(new java.awt.Color(255, 204, 102));
        jTextAreaInfoTurno.setColumns(17);
        jTextAreaInfoTurno.setEditable(false);
        jTextAreaInfoTurno.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        jTextAreaInfoTurno.setRows(3);
        jTextAreaInfoTurno.setText("Modifica la fecha y la shorts en trabajar del trabajador con el DNI del formulario,\nluego dale a \"Guardar\" y se actualizará su turno de trabajo. \nSi deseas consultar el turno de otro DNI, introdúcuelo y dale a \"Consultar\"");
        jScrollPane5.setViewportView(jTextAreaInfoTurno);

        jLabelGestionarPaciente6.setFont(new java.awt.Font("Lucida Grande", 1, 48));
        jLabelGestionarPaciente6.setText("Consultar Turno");

        jTextFieldInicioTurno.setEditable(false);
        jTextFieldInicioTurno.setText("1");

        jLabelFechaInicioTurno.setText("Fecha inicio");

        jLabel9.setText("_____________________________________________________________________________");

        jTextFieldFinTurno.setEditable(false);
        jTextFieldFinTurno.setText("1");

        jLabelFechaFinTurno.setText("Fecha fin");

        jLabelTurnoTrabajo.setText("Turno de trabajo");

        jRadioButtonManiana.setText("Mañana (8h-16h)");

        jRadioButtonTarde1.setText("Tarde (16h-24h)");
        jRadioButtonTarde1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTarde1ActionPerformed(evt);
            }
        });

        jRadioButtonNoche.setText("Noche (24h-8h)");

        org.jdesktop.layout.GroupLayout jPanelConsultarTurnoLayout = new org.jdesktop.layout.GroupLayout(jPanelConsultarTurno);
        jPanelConsultarTurno.setLayout(jPanelConsultarTurnoLayout);
        jPanelConsultarTurnoLayout.setHorizontalGroup(
            jPanelConsultarTurnoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelConsultarTurnoLayout.createSequentialGroup()
                .add(jPanelConsultarTurnoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelConsultarTurnoLayout.createSequentialGroup()
                        .add(273, 273, 273)
                        .add(jLabelGestionarPaciente6))
                    .add(jPanelConsultarTurnoLayout.createSequentialGroup()
                        .add(114, 114, 114)
                        .add(jTextFieldInicioTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 132, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(119, 119, 119)
                        .add(jTextFieldFinTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(255, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelConsultarTurnoLayout.createSequentialGroup()
                .add(149, 149, 149)
                .add(jLabelFechaInicioTurno)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 191, Short.MAX_VALUE)
                .add(jLabelFechaFinTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 74, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(143, 143, 143)
                .add(jLabelTurnoTrabajo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(179, 179, 179))
            .add(jPanelConsultarTurnoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanelConsultarTurnoLayout.createSequentialGroup()
                    .add(0, 60, Short.MAX_VALUE)
                    .add(jPanelConsultarTurnoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanelConsultarTurnoLayout.createSequentialGroup()
                            .add(120, 120, 120)
                            .add(jLabel9))
                        .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 780, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 780, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jPanelConsultarTurnoLayout.createSequentialGroup()
                            .add(290, 290, 290)
                            .add(jLabelDNITurno)
                            .add(16, 16, 16)
                            .add(jTextFieldDNIGestionarTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanelConsultarTurnoLayout.createSequentialGroup()
                            .add(540, 540, 540)
                            .add(jRadioButtonManiana, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanelConsultarTurnoLayout.createSequentialGroup()
                            .add(540, 540, 540)
                            .add(jRadioButtonTarde1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanelConsultarTurnoLayout.createSequentialGroup()
                            .add(540, 540, 540)
                            .add(jRadioButtonNoche, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(0, 61, Short.MAX_VALUE)))
        );
        jPanelConsultarTurnoLayout.setVerticalGroup(
            jPanelConsultarTurnoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelConsultarTurnoLayout.createSequentialGroup()
                .add(65, 65, 65)
                .add(jLabelGestionarPaciente6)
                .add(208, 208, 208)
                .add(jPanelConsultarTurnoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelTurnoTrabajo)
                    .add(jLabelFechaInicioTurno)
                    .add(jLabelFechaFinTurno))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 20, Short.MAX_VALUE)
                .add(jPanelConsultarTurnoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldInicioTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldFinTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(142, 142, 142))
            .add(jPanelConsultarTurnoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanelConsultarTurnoLayout.createSequentialGroup()
                    .add(50, 121, Short.MAX_VALUE)
                    .add(jLabel9)
                    .add(24, 24, 24)
                    .add(jPanelConsultarTurnoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(20, 20, 20)
                    .add(jPanelConsultarTurnoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanelConsultarTurnoLayout.createSequentialGroup()
                            .add(10, 10, 10)
                            .add(jLabelDNITurno))
                        .add(jTextFieldDNIGestionarTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(40, 40, 40)
                    .add(jRadioButtonManiana)
                    .add(7, 7, 7)
                    .add(jRadioButtonTarde1)
                    .add(2, 2, 2)
                    .add(jRadioButtonNoche)
                    .addContainerGap(90, Short.MAX_VALUE)))
        );

        jPanelConsultarTurno.setBounds(0, 0, 860, -1);
        ZonaTrabajo.add(jPanelConsultarTurno, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabelGestionarPaciente7.setFont(new java.awt.Font("Lucida Grande", 1, 36));
        jLabelGestionarPaciente7.setText("Almacenar Resultados Radiología");

        jLabel10.setText("_____________________________________________________________________________");

        jLabelAlmacenarDni.setText("Dni del paciente:");

        jTextFieldAlmacenarDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAlmacenarDniActionPerformed(evt);
            }
        });
        jTextFieldAlmacenarDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAlmacenarDniKeyTyped(evt);
            }
        });

        jRadioButtonRadiologia.setText("Radiografía");
        jRadioButtonRadiologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRadiologiaActionPerformed(evt);
            }
        });

        jRadioButtonResonancia.setText("Resonancia");

        jLabel2.setText("Tipo de Prueba");

        jLabelImagenes.setText("Imagenes");

        scrollPaneImagenes.setBackground(new java.awt.Color(254, 253, 253));

        jScrollPane1.setViewportView(jListImagenes);

        scrollPaneImagenes.add(jScrollPane1);

        jLabelComentarios.setText("Comentarios");

        scrollPaneComentarios.setBackground(new java.awt.Color(254, 254, 254));

        jTextAreaComentario.setColumns(20);
        jTextAreaComentario.setRows(5);
        jScrollPane2.setViewportView(jTextAreaComentario);

        scrollPaneComentarios.add(jScrollPane2);

        jButtonAnadirImagen.setText("Añadir Imagen");
        jButtonAnadirImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAnadirImagenMouseClicked(evt);
            }
        });
        jButtonAnadirImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirImagenActionPerformed(evt);
            }
        });

        jButtonAlmacenarResultadoRadiologo.setText("Guardar");
        jButtonAlmacenarResultadoRadiologo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAlmacenarResultadoRadiologoMouseClicked(evt);
            }
        });

        jLabelError.setForeground(new java.awt.Color(255, 0, 0));
        jLabelError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Intro/Error.png"))); // NOI18N
        jLabelError.setText("Debe rellenar todos los campos");

        jLabelErrorDNI.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorDNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Intro/Error.png"))); // NOI18N
        jLabelErrorDNI.setText("No existe paciente con este DNI");

        org.jdesktop.layout.GroupLayout jPanelAlmacenarResultadosLayout = new org.jdesktop.layout.GroupLayout(jPanelAlmacenarResultados);
        jPanelAlmacenarResultados.setLayout(jPanelAlmacenarResultadosLayout);
        jPanelAlmacenarResultadosLayout.setHorizontalGroup(
            jPanelAlmacenarResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelAlmacenarResultadosLayout.createSequentialGroup()
                .add(jPanelAlmacenarResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelAlmacenarResultadosLayout.createSequentialGroup()
                        .add(149, 149, 149)
                        .add(jPanelAlmacenarResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 809, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanelAlmacenarResultadosLayout.createSequentialGroup()
                                .add(jPanelAlmacenarResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jLabelImagenes)
                                    .add(jLabelComentarios)
                                    .add(scrollPaneImagenes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                                    .add(scrollPaneComentarios, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jPanelAlmacenarResultadosLayout.createSequentialGroup()
                                        .add(jPanelAlmacenarResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(jLabelErrorDNI, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 275, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jPanelAlmacenarResultadosLayout.createSequentialGroup()
                                                .add(jLabelAlmacenarDni)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(jTextFieldAlmacenarDni, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 185, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                                .add(jPanelAlmacenarResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanelAlmacenarResultadosLayout.createSequentialGroup()
                                        .add(86, 86, 86)
                                        .add(jPanelAlmacenarResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(jRadioButtonResonancia, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                            .add(jRadioButtonRadiologia, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .add(jPanelAlmacenarResultadosLayout.createSequentialGroup()
                                        .add(23, 23, 23)
                                        .add(jPanelAlmacenarResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabelError, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 263, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jButtonAnadirImagen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 181, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))))
                    .add(jPanelAlmacenarResultadosLayout.createSequentialGroup()
                        .add(107, 107, 107)
                        .add(jLabelGestionarPaciente7))
                    .add(jPanelAlmacenarResultadosLayout.createSequentialGroup()
                        .add(289, 289, 289)
                        .add(jButtonAlmacenarResultadoRadiologo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAlmacenarResultadosLayout.setVerticalGroup(
            jPanelAlmacenarResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelAlmacenarResultadosLayout.createSequentialGroup()
                .add(25, 25, 25)
                .add(jLabelGestionarPaciente7)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel10)
                .add(32, 32, 32)
                .add(jPanelAlmacenarResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelAlmacenarResultadosLayout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jRadioButtonRadiologia)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jRadioButtonResonancia))
                    .add(jPanelAlmacenarResultadosLayout.createSequentialGroup()
                        .add(jPanelAlmacenarResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabelAlmacenarDni)
                            .add(jTextFieldAlmacenarDni, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabelErrorDNI)
                        .add(8, 8, 8)
                        .add(jLabelImagenes)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelAlmacenarResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(scrollPaneImagenes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 84, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonAnadirImagen))
                .add(17, 17, 17)
                .add(jPanelAlmacenarResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanelAlmacenarResultadosLayout.createSequentialGroup()
                        .add(jLabelComentarios)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(scrollPaneComentarios, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLabelError))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonAlmacenarResultadoRadiologo)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jPanelAlmacenarResultados.setBounds(10, 30, 870, 510);
        ZonaTrabajo.add(jPanelAlmacenarResultados, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(ZonaTrabajo);
        ZonaTrabajo.setBounds(13, 185, 890, 550);

        jPanelUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelUsuario.setLayout(null);

        jLabelUsuario.setText("Usuario:");
        jPanelUsuario.add(jLabelUsuario);
        jLabelUsuario.setBounds(80, 10, 120, 14);

        jLabelTipoUsuario.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabelTipoUsuario.setText("Tipo Usuario");
        jPanelUsuario.add(jLabelTipoUsuario);
        jLabelTipoUsuario.setBounds(90, 40, 120, 18);

        jLabelNombreUsuario.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabelNombreUsuario.setText("Nombre");
        jPanelUsuario.add(jLabelNombreUsuario);
        jLabelNombreUsuario.setBounds(90, 60, 120, 18);
        jPanelUsuario.add(jLabelTipoUsuarioIdentificado);
        jLabelTipoUsuarioIdentificado.setBounds(10, 10, 70, 70);

        getContentPane().add(jPanelUsuario);
        jPanelUsuario.setBounds(665, 47, 220, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jLabelIconoInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoInicioMouseEntered
        // TODO add your handling code here:
        jLabelIconoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Inicio-Activado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoInicioMouseEntered

    private void jLabelIconoInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoInicioMouseExited
        // TODO add your handling code here:
        jLabelIconoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Inicio-Desactivado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoInicioMouseExited

    private void jLabelIconoAyudaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoAyudaMouseExited
        // TODO add your handling code here:
        jLabelIconoAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Ayuda-Desactivado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoAyudaMouseExited

    private void jLabelIconoAyudaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoAyudaMouseEntered
        // TODO add your handling code here:
        jLabelIconoAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Ayuda-Activado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoAyudaMouseEntered

    private void jLabelIconoSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoSalirMouseExited
        // TODO add your handling code here:
        jLabelIconoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Salir-Desactivado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoSalirMouseExited

    private void jLabelIconoSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoSalirMouseEntered
        // TODO add your handling code here:
        jLabelIconoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Salir-Activado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoSalirMouseEntered

    private void jLabelIconoSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelIconoSalirMouseClicked

    private void jLabelIconoAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoAyudaMouseClicked
        // TODO add your handling code here:
        new Ayuda().setVisible(true);
    }//GEN-LAST:event_jLabelIconoAyudaMouseClicked

    private void jButtonConsultarDatosPersonalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConsultarDatosPersonalesMouseClicked
        // TODO add your handling code here:
        mostrarPanel("GestionarPersonal");
    }//GEN-LAST:event_jButtonConsultarDatosPersonalesMouseClicked

    private void jButtonConsultarDatosPersonalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarDatosPersonalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsultarDatosPersonalesActionPerformed

    private void jLabelIconoInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoInicioMouseClicked
        // TODO add your handling code here:
        mostrarPanel("Principal");
    }//GEN-LAST:event_jLabelIconoInicioMouseClicked

    private void jButtonGestionarCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGestionarCitaMouseClicked
        // TODO add your handling code here:

        mostrarPanel("GestionarTurno");

        TurnoBD turbd = new TurnoBD();
        PersonalMedicoBD personalbd= new PersonalMedicoBD();
        PersonalMedico personal= new PersonalMedico();

            personal = personalbd.obtener(jTextFieldDNIGestionarTurno.getText());

            if ( personal!=null ){
                System.out.println("El DNI Es de un PersonalMedico");

                if(personal.getTurno() != null){
                    jTextFieldInicioTurno.setText(personal.getTurno().getHoraInicio().toString());
                    jTextFieldFinTurno.setText(personal.getTurno().getHoraFin().toString());
                    if(personal.getTurno().getTipo().equals("Maniana")){
                        jRadioButtonManiana.setSelected(true);
                    }else
                        if(personal.getTurno().getTipo().equals("Tarde")){
                            jRadioButtonTarde1.setSelected(true);
                        }else
                            if(personal.getTurno().getTipo().equals("Noche")){
                                jRadioButtonNoche.setSelected(true);
                            }

                    new InformacionExito().setVisible(true);
                }
                else{
                    System.out.println("Este personal medico no tiene turno asignado");
                    new InformacionError().setVisible(true);
                }
            }
            else{
                System.out.println("El DNI NO Es de un PersonalMedico");
                new InformacionError().setVisible(true);
            }
    }//GEN-LAST:event_jButtonGestionarCitaMouseClicked

    private void jTextFieldTelefonoPersonalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoPersonalKeyTyped
        // TODO add your handling code here:

        /**Comprobamos que no se teclee una letra*/
        char teclaPresionada = evt.getKeyChar();
        if(jTextFieldTelefonoPersonal.getText().length() < 9)
            if(Character.isDigit(teclaPresionada) == false)
                evt.consume();

        if(jTextFieldTelefonoPersonal.getText().length() >= 9)
            evt.consume();
    }//GEN-LAST:event_jTextFieldTelefonoPersonalKeyTyped

    private void jTextFieldNombrePersonalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombrePersonalKeyTyped
        // TODO add your handling code here:

        /**Comprobamos que no se teclee un número*/
        char teclaPresionada = evt.getKeyChar();
        if(Character.isDigit(teclaPresionada) == true)
            evt.consume();
}//GEN-LAST:event_jTextFieldNombrePersonalKeyTyped

    private void jTextFieldDNIPersonalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDNIPersonalKeyTyped
        // TODO add your handling code here:

        /**Limitamos a que el DNI siempre sea correcto sintácticamente*/
        char teclaPresionada = evt.getKeyChar();

        if(jTextFieldDNIPersonal.getText().length() < 8)
            if(Character.isDigit(teclaPresionada) == false)
                evt.consume();

        if(jTextFieldDNIPersonal.getText().length() == 8)
            if(Character.isDigit(teclaPresionada) == true){
                evt.consume();
            }else if(Character.isLowerCase(teclaPresionada)){
                jTextFieldDNIPersonal.setText(jTextFieldDNIPersonal.getText().toUpperCase());
            }

        if(jTextFieldDNIPersonal.getText().length() > 8)
            evt.consume();
}//GEN-LAST:event_jTextFieldDNIPersonalKeyTyped

    private void jTextFieldApellidosPersonalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidosPersonalKeyTyped
        // TODO add your handling code here:

        /**Comprobamos que no se teclee un número*/
        char teclaPresionada = evt.getKeyChar();
        if(Character.isDigit(teclaPresionada) == true)
            evt.consume();
}//GEN-LAST:event_jTextFieldApellidosPersonalKeyTyped

    private void jTextFieldDireccionPersonalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDireccionPersonalKeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldDireccionPersonalKeyTyped

    private void jTextFieldEmailPersonalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailPersonalKeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldEmailPersonalKeyTyped

    private void jTextFieldLugarNacimientoPersonalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLugarNacimientoPersonalKeyTyped
        // TODO add your handling code here:

        /**Comprobamos que no se teclee un número*/
        char teclaPresionada = evt.getKeyChar();
        if(Character.isDigit(teclaPresionada) == true)
            evt.consume();
}//GEN-LAST:event_jTextFieldLugarNacimientoPersonalKeyTyped

    private void jButtonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGuardarMouseClicked
        // TODO add your handling code here:
         if(compruebaFormulario("GestionarPersonal")){
           
            Date fechaNacimiento = null;                        //HAY QUE PROCESARLA LEYÉNDOLA DEL FORMULARIOOOO
            //byte[] urlFoto = null;                              //HAY QUE GUARDAR LA FOTO Y PASAR LA RUTA DE DONDE ESTA
            boolean exito;
            //String url=null;

            fechaNacimiento = dateChooserCombo2.getSelectedDate().getTime();
            String tipoPersonal = "Radiologo";

            try {
                exito = gesPer.modificarPersonal(jTextFieldDNIPersonal.getText(), jTextFieldNombrePersonal.getText(), jTextFieldApellidosPersonal.getText(), jTextFieldDireccionPersonal.getText(), jTextFieldEmailPersonal.getText(),jTextFieldContraseniaPersonal.getText(), jTextFieldTelefonoPersonal.getText(), fechaNacimiento, jTextFieldLugarNacimientoPersonal.getText(), sfotografia, tipoPersonal);
                if(exito){
                    new InformacionExito().setVisible(true);
                    limpiarFormulario("GestionarPersonal");
                    }
                else
                    new InformacionError().setVisible(true);

            } catch (SQLException ex) {
                Logger.getLogger(UI_Administrador.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
}//GEN-LAST:event_jButtonGuardarMouseClicked

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jRadioButtonFarmaceuticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFarmaceuticoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jRadioButtonFarmaceuticoActionPerformed

    private void jRadioButtonRadiologoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRadiologoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jRadioButtonRadiologoActionPerformed

    private void jRadioButtonMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMedicoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jRadioButtonMedicoActionPerformed

    private void jTextFieldDNIGestionarTurnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDNIGestionarTurnoKeyTyped
        // TODO add your handling code here:

        /**Limitamos a que el DNI siempre sea correcto sintácticamente*/
        char teclaPresionada = evt.getKeyChar();

        if(jTextFieldDNIGestionarTurno.getText().length() < 8)
            if(Character.isDigit(teclaPresionada) == false)
                evt.consume();

        if(jTextFieldDNIGestionarTurno.getText().length() == 8)
            if(Character.isDigit(teclaPresionada) == true){
                evt.consume();
            }else if(Character.isLowerCase(teclaPresionada)){
                jTextFieldDNIGestionarTurno.setText(jTextFieldDNIGestionarTurno.getText().toUpperCase());
            }

        if(jTextFieldDNIGestionarTurno.getText().length() > 8)
            evt.consume();
}//GEN-LAST:event_jTextFieldDNIGestionarTurnoKeyTyped

    private void jRadioButtonTarde1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTarde1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jRadioButtonTarde1ActionPerformed

    private void jButtonGestionarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionarCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGestionarCitaActionPerformed

    private void jButtonAlmacenarResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAlmacenarResultadoMouseClicked
        // TODO add your handling code here:
        mostrarPanel("AlmacenarResultados");
    }//GEN-LAST:event_jButtonAlmacenarResultadoMouseClicked

    private void jTextFieldAlmacenarDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAlmacenarDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlmacenarDniActionPerformed

    private void jRadioButtonRadiologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRadiologiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonRadiologiaActionPerformed

    private void jButtonAnadirImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAnadirImagenActionPerformed

    private void jButtonAnadirImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAnadirImagenMouseClicked
        // TODO add your handling code here:
        cargarFoto("almacenar");
    }//GEN-LAST:event_jButtonAnadirImagenMouseClicked

    private void jButtonAlmacenarResultadoRadiologoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAlmacenarResultadoRadiologoMouseClicked
        // TODO add your handling code here:
        System.out.println("fuera almacenar");

     if(compruebaFormulario("Almacenar")){
         System.out.println("dentro almacenar");
       jLabelError.setVisible(false);
       jLabelErrorDNI.setVisible(false);
       

       String tipo = null;
       boolean dev;
       ArrayList<Imagen> im = new ArrayList();
       Imagen imag = new Imagen();
       String ruta;

       if(jRadioButtonRadiologia.isSelected()){
           tipo = "Radiografia";
       }

       if(jRadioButtonResonancia.isSelected()){
           tipo = "Resonancia";
       }
       ruta = jListImagenes.getModel().getElementAt(0).toString();
       System.out.println(ruta);
       imag.setRuta(ruta);
       im.add(imag);
       String DNIRadiologo = jTextFieldDNIPersonal.getText();
       try{
           dev = gp.almacenarResultadoRadiologia(jTextFieldAlmacenarDni.getText(),im , jTextAreaComentario.getText(), tipo, DNIRadiologo);
           if(dev == true){
                 new InformacionExito().setVisible(true);
                 mostrarPanel("Principal");
           }
           else{
                new InformacionError().setVisible(true);
                jLabelErrorDNI.setVisible(true);
           }
       }
       catch (Exception ex)    {}
        }
         else
             jLabelError.setVisible(true);
    }//GEN-LAST:event_jButtonAlmacenarResultadoRadiologoMouseClicked

    private void jTextFieldAlmacenarDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAlmacenarDniKeyTyped
        // TODO add your handling code here:
        /**Limitamos a que el DNI siempre sea correcto sintácticamente*/
        char teclaPresionada = evt.getKeyChar();

        if(jTextFieldAlmacenarDni.getText().length() < 8)
            if(Character.isDigit(teclaPresionada) == false)
                evt.consume();

        if(jTextFieldAlmacenarDni.getText().length() == 8)
            if(Character.isDigit(teclaPresionada) == true){
                evt.consume();
                }else if(Character.isLowerCase(teclaPresionada)){
                    jTextFieldAlmacenarDni.setText(jTextFieldAlmacenarDni.getText().toUpperCase());
                }

        if(jTextFieldAlmacenarDni.getText().length() > 8)
            evt.consume();
    }//GEN-LAST:event_jTextFieldAlmacenarDniKeyTyped


    /*Comprueba que la fecha introducida es correcta
     * 
     *@param persona, string que indica si se trata del formulario de Paciente o Personal
     *@return booleano diciendo si es válido o no
     */
    private boolean compruebaFecha(String persona){
        
        int dia = 0;
        int mes = 0;
        int anio = 0;
        int diaActual;
        int mesActual;
        int anioActual;
 Calendar fecha;
        if(persona.equals("GestionarPersonal")){
           fecha=dateChooserCombo2.getSelectedDate();
           dia=fecha.get(Calendar.DATE);
           mes=fecha.get(Calendar.MONTH)+1;
           anio=fecha.get(Calendar.YEAR);
        }

         Date fechaa= new Date();
         diaActual=fechaa.getDate();
         mesActual=fechaa.getMonth()+1;
         anioActual=fechaa.getYear()+1901;


        /**Si se sale de los rangos*/
        if((dia <= 0)
                || (dia > 31)
                || (mes <= 0)
                || (mes > 12)
                || (anio < 1900)
                || (anio > anioActual) ){
            return false;
        }

        /**Si ha nacido en el año actual, hay que ver que el mes no sea mayor que el actual*/
        /**Si ha nacido en el año y mes actual, hay que comprobar que el dia sea menor que el actual*/
        if(anio == anioActual){
            if(mes > mesActual){
                return false;
            } else{
                if(dia > diaActual){
                    return false;
                }
            }
        }

        /**Si estamos en un mes que tiene 30 días o 29 en el caso de febrero, hay que comprobar que no se pase*/
        if(mes%2 == 0){
            if((mes == 2) && (dia >29)){
                return false;
            }else{
                if(dia > 30){
                    return false;
                }
            }
        }

        return true;

    }


     /*Borra el formulario elegido
     *
     *@param persona, string que indica si se trata del formulario de Paciente o Personal
     */
    private void limpiarFormulario(String persona){

        String diaActual;
        String mesActual;
        String anioActual;
        String horaActual;
        String minutoActual;

        Calendar fechaActual = Calendar.getInstance();
        diaActual = Integer.toString(fechaActual.get(Calendar.DATE));
        mesActual = Integer.toString(fechaActual.get(Calendar.MONTH));
        anioActual = Integer.toString(fechaActual.get(Calendar.YEAR));
        horaActual = Integer.toString(fechaActual.get(Calendar.HOUR_OF_DAY));
        minutoActual = Integer.toString(fechaActual.get(Calendar.MINUTE));


        if(persona.equals("GestionarPaciente")){
            jTextFieldNombrePersonal.setText("");
            jTextFieldApellidosPersonal.setText("");
            jTextFieldDNIPersonal.setText("");
            jTextFieldDireccionPersonal.setText("");
            jTextFieldEmailPersonal.setText("");
            jTextFieldTelefonoPersonal.setText("");
            jTextFieldContraseniaPersonal.setText("");
            jTextFieldLugarNacimientoPersonal.setText("");

            jLabelFotoPersonal.setIcon(null);
        }

        if(persona.equals("GestionarTurno")){
            jTextFieldInicioTurno.setText(diaActual);
            jTextFieldFinTurno.setText(diaActual);
        }

        if(persona.equals("Almacenar"))
        {
            jTextFieldAlmacenarDni.setText("");
            jTextAreaComentario.setText("");
            DefaultListModel modelo=new DefaultListModel();
           jListImagenes.setModel(modelo);
        }
    }

  
    /*Muestra el panel elegido en ZonaTrabajo
     *
     *@param panel, string que indica el panel a mostrar
     */
    private void mostrarPanel(String panel){

        if(panel.equals("Principal")){

            /**Hacemos visible el botón jLabelIconoInicio*/
            jLabelInicio.setVisible(false);
            jLabelIconoInicio.setVisible(false);
            jLabelError.setVisible(false);
            jLabelErrorDNI.setVisible(false);
            /**Hacemos visible el panel seleccionado*/
            jPanelPrincipal.setVisible(true);
            jPanelConsultarDatosPersonales.setVisible(false);
            jPanelConsultarTurno.setVisible(false);
            jPanelAlmacenarResultados.setVisible(false);

            /**Activamos el marco*/
            jPanelPrincipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
            jPanelConsultarDatosPersonales.setBorder(null);
            jPanelConsultarTurno.setBorder(null);
            jPanelAlmacenarResultados.setBorder(null);
        }

        if(panel.equals("GestionarPersonal")){

            /**Hacemos visible el botón jLabelIconoInicio*/
            jLabelInicio.setVisible(true);
            jLabelIconoInicio.setVisible(true);

             jRadioButtonAnalista.setEnabled(false);
             jRadioButtonRadiologo.setSelected(true);
             jRadioButtonFarmaceutico.setEnabled(false);
             jRadioButtonMedico.setEnabled(false);


            /**Insertamos icono de foto anónima*/
            //jLabelFotoPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Foto-Anonima.png"))); // NOI18N


            /**Hacemos visible el panel seleccionado*/
            jPanelPrincipal.setVisible(false);
            jPanelConsultarDatosPersonales.setVisible(true);
            jPanelConsultarTurno.setVisible(false);
            jPanelAlmacenarResultados.setVisible(false);


            /**Activamos el marco*/
            jPanelPrincipal.setBorder(null);
            jPanelConsultarDatosPersonales.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
            jPanelConsultarTurno.setBorder(null);
            jPanelAlmacenarResultados.setBorder(null);
        }


        if(panel.equals("GestionarTurno")){

            /**Limpiamos posibles datos introducidos anteriormente*/
            limpiarFormulario("GestionarTurno");

            /**Hacemos visible el botón jLabelIconoInicio*/
            jLabelInicio.setVisible(true);
            jLabelIconoInicio.setVisible(true);

            /**Hacemos visible el panel seleccionado*/
            jPanelPrincipal.setVisible(false);
            jPanelConsultarDatosPersonales.setVisible(false);
            jPanelConsultarTurno.setVisible(true);
            jPanelAlmacenarResultados.setVisible(false);

            /**Activamos el marco*/
            jPanelPrincipal.setBorder(null);
            jPanelConsultarDatosPersonales.setBorder(null);
            jPanelConsultarTurno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
            jPanelAlmacenarResultados.setBorder(null);
        }

         if(panel.equals("AlmacenarResultados")){

             limpiarFormulario("Almacenar");
             jLabelImagenes.setForeground(Color.black);
             jLabelAlmacenarDni.setForeground(Color.black);
             jLabelComentarios.setForeground(Color.black);
            /**Hacemos visible el botón jLabelIconoInicio*/
            jLabelInicio.setVisible(true);
            jLabelIconoInicio.setVisible(true);

            /**Hacemos visible el panel seleccionado*/
            jPanelPrincipal.setVisible(false);
            jPanelConsultarDatosPersonales.setVisible(false);
            jPanelConsultarTurno.setVisible(false);
            jPanelAlmacenarResultados.setVisible(true);


            /**Activamos el marco*/
            jPanelPrincipal.setBorder(null);
            jPanelConsultarDatosPersonales.setBorder(null);
            jPanelConsultarTurno.setBorder(null);
            jPanelAlmacenarResultados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        }




    }


     /*Carga la foto en el formulario pasado por parámetro
     *
     *@param formulario, string que indica el formulario donde cargar la foto
     */
    private void cargarFoto(String formulario){

        if(formulario.equals("GestionarPersonal")){
            JFileChooser dlg = new JFileChooser();
            int resp = dlg.showOpenDialog(this);
            if (resp == JFileChooser.APPROVE_OPTION){
                try{
                    ImageIcon icono = new ImageIcon(dlg.getSelectedFile().getCanonicalPath());
                    Image imagen = icono.getImage();
                    ImageIcon aescala = new ImageIcon(imagen.getScaledInstance(130,150,Image.SCALE_SMOOTH));
                    jLabelFotoPersonal.setIcon(aescala); // NOI18N

                }
                catch(Exception ex){
                    System.err.print("Error al leer el archivo");
                }
            }
        }
        if(formulario.equals("almacenar"))
        {
        JFileChooser dlg = new JFileChooser();
            int resp = dlg.showOpenDialog(this);
            if (resp == JFileChooser.APPROVE_OPTION){
                try{
                    String ruta = dlg.getSelectedFile().getAbsolutePath();
                    DefaultListModel aux=new DefaultListModel();
                    aux.addElement(ruta);
                    jListImagenes.setModel(aux);


                }
                catch(Exception ex){
                    System.err.print("Error al leer el archivo");
                }
            }





        }

    }
/* Comentado por Nicolás
    private void identificarPersonal( String nombreUsuario) throws SQLException{

        //trabajar con personal no se puede, ya que su BD está mal

        Usuario perso=null;
        usuarioBD usu_bd=new usuarioBD ();
        perso=usu_bd.obtenerUsuario(nombreUsuario);

        mostrarDatosPerso(perso);

    }
*/
    private void mostrarDatosPerso(Usuario usu) throws SQLException{

        Calendar calendar = Calendar.getInstance();
        calendar.setTime(usu.getFecNac());
        int dia = calendar.get(Calendar.DAY_OF_MONTH);   //dia del mes
        int mes = calendar.get(Calendar.MONTH);
        mes=mes+1;//mes, de 0 a 11
        int anio = calendar.get(Calendar.YEAR);  //año

        String num_dia= String.valueOf(dia);
        String num_mes= String.valueOf(mes);
        String num_anio= String.valueOf(anio);
        

        sfotografia=usu.getFoto();
        //Codigo para cargar la imagen del usuario en el formulario
        try{
            
            ImageIcon icono = new ImageIcon(usu.getFoto());
            Image imagen = icono.getImage();
            ImageIcon aescala = new ImageIcon(imagen.getScaledInstance(150,150,Image.SCALE_SMOOTH));
            jLabelFotoPersonal.setIcon(aescala); // NOI18N
        }
        catch(Exception ex){
            System.err.print("Error al leer el archivo");
        }

//        jTextFieldFechaNacimientoAnioPersonal.setText(num_anio);
  //      jTextFieldFechaNacimientoDiaPersonal.setText(num_dia);
    //    jTextFieldFechaNacimientoMesersonal.setText(num_mes);
        jTextFieldNombrePersonal.setText(usu.getNombre());
        jTextFieldContraseniaPersonal.setText(usu.getContrasenia());
        jTextFieldDNIPersonal.setText(usu.getDNI());
        jTextFieldApellidosPersonal.setText(usu.getApellidos());
        jTextFieldTelefonoPersonal.setText(usu.getTelefono());
        jTextFieldDireccionPersonal.setText(usu.getDireccion());
        jTextFieldEmailPersonal.setText(usu.getEmail());
        jTextFieldLugarNacimientoPersonal.setText(usu.getLugarNac());
        jTextFieldDNIPersonal.setEditable(false);
    }


    private boolean compruebaFormulario(String formulario){
        System.out.println("dentro de comprueba formulario");
        if(formulario.equals("GestionarPersonal")){

            if(!compruebaFecha("GestionarPersonal")){
                jLabelFechaNacimientoPersonal.setForeground(Color.red);
                return false;
                }else{
                jLabelFechaNacimientoPersonal.setForeground(Color.black);
                }

            if(jTextFieldNombrePersonal.getText().length() == 0){
                jLabelNombrePersonal.setForeground(Color.red);
                return false;
                }else{
                jLabelNombrePersonal.setForeground(Color.black);
            }

            if(jTextFieldApellidosPersonal.getText().length() == 0){
                jLabelApellidosPersonal.setForeground(Color.red);
                return false;
                }else{
                jLabelApellidosPersonal.setForeground(Color.black);
            }

            if(jTextFieldDNIPersonal.getText().length() != 9){
                jLabelDNIPersonal.setForeground(Color.red);
                return false;
                }else{
                jLabelDNIPersonal.setForeground(Color.black);
            }

            if(jTextFieldDireccionPersonal.getText().length() == 0){
                jLabelDireccionPersonal.setForeground(Color.red);
                return false;
                }else{
                jLabelDireccionPersonal.setForeground(Color.black);
            }

            if(jTextFieldEmailPersonal.getText().length() == 0){
                jLabelEmailPersonal.setForeground(Color.red);
                return false;
                }else{
                jLabelEmailPersonal.setForeground(Color.black);
            }

            if(jTextFieldTelefonoPersonal.getText().length() == 0){
                jLabelTelefonoPersonal.setForeground(Color.red);
                return false;
                }else{
                jLabelTelefonoPersonal.setForeground(Color.black);
            }

            if(jTextFieldLugarNacimientoPersonal.getText().length() == 0){
                jLabelLugarNacimientoPersonal.setForeground(Color.red);
                return false;
                }else{
                jLabelLugarNacimientoPersonal.setForeground(Color.black);
            }

            return true;

    }

        if(formulario.equals("Almacenar")){

            if(jTextFieldAlmacenarDni.getText().length() == 0){
                jLabelAlmacenarDni.setForeground(Color.red);
                return false;
                }else{
                jLabelAlmacenarDni.setForeground(Color.black);
                }
            if(jTextAreaComentario.getText().length() == 0){
                jLabelComentarios.setForeground(Color.red);
                return false;
                }else{
                jLabelComentarios.setForeground(Color.black);
                }
            if(jListImagenes.getModel().getSize() == 0){
                jLabelImagenes.setForeground(Color.red);
                return false;
                }else{
                  jLabelImagenes.setForeground(Color.black);
                 }

        }
        return true;
    }

    // @param args the command line arguments
    
/*    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Paciente("Paciente", "paciente").setVisible(true);
            }
        });
    }
*/
 
    byte[] sfotografia;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane ZonaTrabajo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private javax.swing.JButton jButtonAlmacenarResultado;
    private javax.swing.JButton jButtonAlmacenarResultadoRadiologo;
    private javax.swing.JButton jButtonAnadirImagen;
    private javax.swing.JButton jButtonConsultarDatosPersonales;
    private javax.swing.JButton jButtonGestionarCita;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAlmacenarDni;
    private javax.swing.JLabel jLabelApellidosPersonal;
    private javax.swing.JLabel jLabelAyuda;
    private javax.swing.JLabel jLabelCentroMedico;
    private javax.swing.JLabel jLabelComentarios;
    private javax.swing.JLabel jLabelConsultarTurno;
    private javax.swing.JLabel jLabelContraseniaPersonal;
    private javax.swing.JLabel jLabelDNIPersonal;
    private javax.swing.JLabel jLabelDNITurno;
    private javax.swing.JLabel jLabelDireccionPersonal;
    private javax.swing.JLabel jLabelEmailPersonal;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelErrorDNI;
    private javax.swing.JLabel jLabelFechaFinTurno;
    private javax.swing.JLabel jLabelFechaInicioTurno;
    private javax.swing.JLabel jLabelFechaNacimientoPersonal;
    private javax.swing.JLabel jLabelFotoPersonal;
    private javax.swing.JLabel jLabelFotografiaersonal;
    private javax.swing.JLabel jLabelGestionarPaciente3;
    private javax.swing.JLabel jLabelGestionarPaciente4;
    private javax.swing.JLabel jLabelGestionarPaciente6;
    private javax.swing.JLabel jLabelGestionarPaciente7;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JLabel jLabelIconoAyuda;
    private javax.swing.JLabel jLabelIconoInicio;
    private javax.swing.JLabel jLabelIconoSalir;
    private javax.swing.JLabel jLabelImagenes;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelLugarNacimientoPersonal;
    private javax.swing.JLabel jLabelNombrePersonal;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JLabel jLabelSalir;
    private javax.swing.JLabel jLabelTelefonoPersonal;
    private javax.swing.JLabel jLabelTipoUsuario;
    private javax.swing.JLabel jLabelTipoUsuarioIdentificado;
    private javax.swing.JLabel jLabelTurnoTrabajo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JList jListImagenes;
    private javax.swing.JPanel jPanelAlmacenarResultados;
    private javax.swing.JPanel jPanelConsultarDatosPersonales;
    private javax.swing.JPanel jPanelConsultarTurno;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelUsuario;
    private javax.swing.JRadioButton jRadioButtonAnalista;
    private javax.swing.JRadioButton jRadioButtonFarmaceutico;
    private javax.swing.JRadioButton jRadioButtonManiana;
    private javax.swing.JRadioButton jRadioButtonMedico;
    private javax.swing.JRadioButton jRadioButtonNoche;
    private javax.swing.JRadioButton jRadioButtonRadiologia;
    private javax.swing.JRadioButton jRadioButtonRadiologo;
    private javax.swing.JRadioButton jRadioButtonResonancia;
    private javax.swing.JRadioButton jRadioButtonTarde1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextAreaComentario;
    private javax.swing.JTextArea jTextAreaInfoConsultaTurno;
    private javax.swing.JTextArea jTextAreaInfoTurno;
    private javax.swing.JTextField jTextFieldAlmacenarDni;
    private javax.swing.JTextField jTextFieldApellidosPersonal;
    private javax.swing.JTextField jTextFieldContraseniaPersonal;
    private javax.swing.JTextField jTextFieldDNIGestionarTurno;
    private javax.swing.JTextField jTextFieldDNIPersonal;
    private javax.swing.JTextField jTextFieldDireccionPersonal;
    private javax.swing.JTextField jTextFieldEmailPersonal;
    private javax.swing.JTextField jTextFieldFinTurno;
    private javax.swing.JTextField jTextFieldInicioTurno;
    private javax.swing.JTextField jTextFieldLugarNacimientoPersonal;
    private javax.swing.JTextField jTextFieldNombrePersonal;
    private javax.swing.JTextField jTextFieldTelefonoPersonal;
    private java.awt.ScrollPane scrollPaneComentarios;
    private java.awt.ScrollPane scrollPaneImagenes;
    // End of variables declaration//GEN-END:variables

}
