/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal_Administrador.java
 *
 * Created on 16-mar-2011, 18:27:18
 */

package Interfaz;

import java.awt.Image;
import Controlador.*;
import CentroMedico.*;
import BaseDatos.*;
import java.util.Calendar.*;
import java.util.Calendar;

import java.sql.SQLException;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;


/**
 *
 * @author Nicolas_Sanchez
 */
public class UI_Paciente extends javax.swing.JFrame {

    /** Creates new form Principal_Administrador */
    public UI_Paciente() {
        initComponents();
    }

    public UI_Paciente(String nombreUsuario, String tipoUsuario) throws SQLException{
        initComponents();

        /**Ponemos las etiquetas del usuario que ha entrado*/
        jLabelNombreUsuario.setText(nombreUsuario);
        jLabelTipoUsuario.setText(tipoUsuario);

        /**Mostramos el panel Principal*/
        mostrarPanel("Principal");
        identificarPaciente(nombreUsuario);

        /** Conectamos con la BD y tomamos los datos del paciente*/
       
        /**Ponemos icono de paciente logueado*/
        jLabelTipoUsuarioIdentificado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Tipo-Usuario-Paciente.png"))); // NOI18N
    }

    private void identificarPaciente( String nombreUsuario) throws SQLException{

        //trabajar con paciente no se puede, ya que su BD está mal
       
        Usuario paci=null;
        usuarioBD usu_bd=new usuarioBD ();
        paci=usu_bd.obtenerUsuario(nombreUsuario);

        mostrarDatosPaciente(paci);
        cargarDatosCitaPaciente(paci);

    }
    
    private void mostrarDatosPaciente(Usuario usu) throws SQLException{

        Calendar calendar = Calendar.getInstance();
        calendar.setTime(usu.getFechaNacimiento());
        int dia = calendar.get(Calendar.DAY_OF_MONTH);   //dia del mes
        int mes = calendar.get(Calendar.MONTH);
        mes=mes+1;//mes, de 0 a 11
        int anio = calendar.get(Calendar.YEAR);  //año

        String num_dia= String.valueOf(dia);
        String num_mes= String.valueOf(mes);
        String num_anio= String.valueOf(anio);


        jTextFieldFechaNacimientoAnioPaciente.setText(num_anio);
        jTextFieldFechaNacimientoDiaPaciente.setText(num_dia);
        jTextFieldFechaNacimientoMesPaciente.setText(num_mes);
        jTextFieldNombrePaciente.setText(usu.getNombre());
        jTextFieldContraseniaPaciente.setText(usu.getContrasena());
        jTextFieldDNIPaciente.setText(usu.getDni());
        jTextFieldApellidosPaciente.setText(usu.getApellidos());
        jTextFieldTelefonoPaciente.setText(usu.getTelefono());
        jTextFieldDireccionPaciente.setText(usu.getDireccion());
        jTextFieldEmailPaciente.setText(usu.getEmail());
        jTextFieldLugarNacimientoPaciente.setText(usu.getLugarNacimiento());

        
      
       
       
        

    }

    private void cargarDatosCitaPaciente( Usuario usu )throws SQLException{

        citasBD cita_bd=new citasBD();
        Cita nueva_cita = null;
        boolean existe;

        existe=cita_bd.existeCita(usu.getDni());

        if(existe){

            nueva_cita = cita_bd.obtenerCita(usu.getDni());

            Calendar calendar = Calendar.getInstance();
            calendar.setTime(nueva_cita.getFecha());
            int dia = calendar.get(Calendar.DAY_OF_MONTH);   //dia del mes
            int mes = calendar.get(Calendar.MONTH);
            mes=mes+1;//mes, de 0 a 11
            int anio = calendar.get(Calendar.YEAR);  //año

            String num_dia= String.valueOf(dia);
            String num_mes= String.valueOf(mes);
            String num_anio= String.valueOf(anio);



            jTextFieldDNIMedico.setText(nueva_cita.getDniMedico());
            jTextFieldDNIPacienteCita.setText(nueva_cita.getDniPaciente());
            jTextFieldAnioCita.setText(num_anio);
            jTextFieldDiaCita.setText(num_dia);
            jTextFieldMesCita.setText(num_mes);


             //la hora de la cita no está implementada


        }
           



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCentroMedico = new javax.swing.JLabel();
        jLabelIconoInicio = new javax.swing.JLabel();
        jLabelInicio = new javax.swing.JLabel();
        jLabelIconoAyuda = new javax.swing.JLabel();
        jLabelIconoSalir = new javax.swing.JLabel();
        jLabelAyuda = new javax.swing.JLabel();
        jLabelSalir = new javax.swing.JLabel();
        jLabelIcono = new javax.swing.JLabel();
        ZonaTrabajo = new javax.swing.JLayeredPane();
        jPanelPrincipal = new javax.swing.JPanel();
        jButtonGestionarPaciente = new javax.swing.JButton();
        jLabelGestionarPaciente3 = new javax.swing.JLabel();
        jLabelGestionarCita1 = new javax.swing.JLabel();
        jButtonGestionarCita = new javax.swing.JButton();
        jPanelGestionarPaciente = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelGestionarPaciente4 = new javax.swing.JLabel();
        jTextFieldNombrePaciente = new javax.swing.JTextField();
        jLabelFotoPaciente = new javax.swing.JLabel();
        jTextFieldTelefonoPaciente = new javax.swing.JTextField();
        jLabelContraseniaPaciente = new javax.swing.JLabel();
        jTextFieldDNIPaciente = new javax.swing.JTextField();
        jLabelNombrePaciente = new javax.swing.JLabel();
        jLabelFotografiaPaciente = new javax.swing.JLabel();
        jLabelDNIPaciente = new javax.swing.JLabel();
        jTextFieldLugarNacimientoPaciente = new javax.swing.JTextField();
        jLabelTelefonoPaciente = new javax.swing.JLabel();
        jTextFieldFechaNacimientoMesPaciente = new javax.swing.JTextField();
        jLabelLugarNacimientoPaciente = new javax.swing.JLabel();
        jLabelDireccionPaciente = new javax.swing.JLabel();
        jButtonMenosAnioPaciente = new javax.swing.JButton();
        jLabelApellidosPaciente = new javax.swing.JLabel();
        jTextFieldApellidosPaciente = new javax.swing.JTextField();
        jButtonMasDiaPaciente = new javax.swing.JButton();
        jButtonMenosMesPaciente = new javax.swing.JButton();
        jButtonMenosDiaPaciente = new javax.swing.JButton();
        jLabelEmailPaciente = new javax.swing.JLabel();
        jTextFieldDireccionPaciente = new javax.swing.JTextField();
        jTextFieldFechaNacimientoDiaPaciente = new javax.swing.JTextField();
        jButtonMasAnioPaciente = new javax.swing.JButton();
        jTextFieldEmailPaciente = new javax.swing.JTextField();
        jTextFieldFechaNacimientoAnioPaciente = new javax.swing.JTextField();
        jTextFieldContraseniaPaciente = new javax.swing.JTextField();
        jButtonMasMesPaciente = new javax.swing.JButton();
        jLabelFechaNacimientoPaciente = new javax.swing.JLabel();
        jPanelConsultarCitaOnline = new javax.swing.JPanel();
        jTextFieldMesCita = new javax.swing.JTextField();
        jButtonMenosAnioPersonal = new javax.swing.JButton();
        jButtonMasAnioFecha = new javax.swing.JButton();
        jTextFieldAnioCita = new javax.swing.JTextField();
        jLabelFecha = new javax.swing.JLabel();
        jTextFieldDiaCita = new javax.swing.JTextField();
        jButtonMasMesFecha = new javax.swing.JButton();
        jButtonMasDiaFecha = new javax.swing.JButton();
        jButtonModificarCitaOnline = new javax.swing.JButton();
        jButtonMenosDiaFecha = new javax.swing.JButton();
        jButtonMenosMesFecha = new javax.swing.JButton();
        jLabelGestionarPaciente2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonLimpiarCita = new javax.swing.JButton();
        jButtonMasHora = new javax.swing.JButton();
        jButtonMasMinuto = new javax.swing.JButton();
        jTextFieldHoraCita = new javax.swing.JTextField();
        jTextFieldMinutoCita = new javax.swing.JTextField();
        jButtonMenosHora = new javax.swing.JButton();
        jButtonMenosMinuto = new javax.swing.JButton();
        jLabelHoraCita = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaInfo = new javax.swing.JTextArea();
        jButtonLimpiarCita1 = new javax.swing.JButton();
        jLabelFecha1 = new javax.swing.JLabel();
        jLabelFecha2 = new javax.swing.JLabel();
        jTextFieldDNIMedico = new javax.swing.JTextField();
        jTextFieldDNIPacienteCita = new javax.swing.JTextField();
        jPanelGestionarCitaOnline = new javax.swing.JPanel();
        jLabelGestionarPaciente5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaInfo1 = new javax.swing.JTextArea();
        jPanelAltaCita = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonAceptarCita = new javax.swing.JButton();
        jPanelBotones = new javax.swing.JPanel();
        jButtonCancelarCita = new javax.swing.JButton();
        jButtonModificarCita = new javax.swing.JButton();
        jButtonConsultarCita1 = new javax.swing.JButton();
        jButtonPedirAltaCita = new javax.swing.JButton();
        jPanelUsuario = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelTipoUsuario = new javax.swing.JLabel();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jLabelTipoUsuarioIdentificado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 102));
        setMinimumSize(new java.awt.Dimension(931, 715));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelCentroMedico.setText("Centro médico");
        getContentPane().add(jLabelCentroMedico);
        jLabelCentroMedico.setBounds(177, 68, 94, 17);

        jLabelIconoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Inicio-Desactivado.png"))); // NOI18N
        jLabelIconoInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconoInicioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIconoInicioMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIconoInicioMouseEntered(evt);
            }
        });
        getContentPane().add(jLabelIconoInicio);
        jLabelIconoInicio.setBounds(420, 70, 44, 47);

        jLabelInicio.setText("Inicio");
        getContentPane().add(jLabelInicio);
        jLabelInicio.setBounds(420, 120, 44, 17);

        jLabelIconoAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Ayuda-Desactivado.png"))); // NOI18N
        jLabelIconoAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconoAyudaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIconoAyudaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIconoAyudaMouseEntered(evt);
            }
        });
        getContentPane().add(jLabelIconoAyuda);
        jLabelIconoAyuda.setBounds(500, 70, 44, 47);

        jLabelIconoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Salir-Desactivado.png"))); // NOI18N
        jLabelIconoSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconoSalirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIconoSalirMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIconoSalirMouseEntered(evt);
            }
        });
        getContentPane().add(jLabelIconoSalir);
        jLabelIconoSalir.setBounds(580, 70, 43, 47);

        jLabelAyuda.setText("Ayuda");
        getContentPane().add(jLabelAyuda);
        jLabelAyuda.setBounds(500, 120, 44, 17);

        jLabelSalir.setText("Salir");
        getContentPane().add(jLabelSalir);
        jLabelSalir.setBounds(590, 120, 28, 17);

        jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Intro/Logo-Centro-Medico.png"))); // NOI18N
        getContentPane().add(jLabelIcono);
        jLabelIcono.setBounds(20, 17, 140, 150);

        ZonaTrabajo.setMinimumSize(new java.awt.Dimension(902, 520));
        ZonaTrabajo.setPreferredSize(new java.awt.Dimension(912, 530));

        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(901, 531));

        jButtonGestionarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Paciente.png"))); // NOI18N
        jButtonGestionarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGestionarPacienteMouseClicked(evt);
            }
        });
        jButtonGestionarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionarPacienteActionPerformed(evt);
            }
        });

        jLabelGestionarPaciente3.setText("Consultar Datos Personales");

        jLabelGestionarCita1.setText("Gestionar Cita Online");

        jButtonGestionarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Cita.png"))); // NOI18N
        jButtonGestionarCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGestionarCitaMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelPrincipalLayout = new org.jdesktop.layout.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelPrincipalLayout.createSequentialGroup()
                .add(47, 47, 47)
                .add(jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButtonGestionarPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 194, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanelPrincipalLayout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(jLabelGestionarPaciente3)))
                .add(25, 25, 25)
                .add(jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelPrincipalLayout.createSequentialGroup()
                        .add(53, 53, 53)
                        .add(jButtonGestionarCita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 194, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanelPrincipalLayout.createSequentialGroup()
                        .add(84, 84, 84)
                        .add(jLabelGestionarCita1)))
                .addContainerGap(388, Short.MAX_VALUE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelPrincipalLayout.createSequentialGroup()
                .add(29, 29, 29)
                .add(jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButtonGestionarCita, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButtonGestionarPaciente, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelGestionarCita1)
                    .add(jLabelGestionarPaciente3))
                .add(336, 336, 336))
        );

        jPanelPrincipal.setBounds(0, 0, 901, 530);
        ZonaTrabajo.add(jPanelPrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanelGestionarPaciente.setPreferredSize(new java.awt.Dimension(901, 531));

        jLabel3.setText("___________________________________________________________________");

        jLabelGestionarPaciente4.setFont(new java.awt.Font("Lucida Grande", 1, 48));
        jLabelGestionarPaciente4.setText("Gestionar Paciente");

        jTextFieldNombrePaciente.setEditable(false);
        jTextFieldNombrePaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombrePacienteKeyTyped(evt);
            }
        });

        jLabelFotoPaciente.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFotoPaciente.setForeground(new java.awt.Color(255, 255, 255));

        jTextFieldTelefonoPaciente.setEditable(false);
        jTextFieldTelefonoPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelefonoPacienteKeyTyped(evt);
            }
        });

        jLabelContraseniaPaciente.setText("Contraseña");

        jTextFieldDNIPaciente.setEditable(false);
        jTextFieldDNIPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDNIPacienteKeyTyped(evt);
            }
        });

        jLabelNombrePaciente.setText("Nombre");

        jLabelFotografiaPaciente.setText("Fotografía");

        jLabelDNIPaciente.setText("DNI");

        jTextFieldLugarNacimientoPaciente.setEditable(false);
        jTextFieldLugarNacimientoPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLugarNacimientoPacienteKeyTyped(evt);
            }
        });

        jLabelTelefonoPaciente.setText("Teléfono");

        jTextFieldFechaNacimientoMesPaciente.setEditable(false);
        jTextFieldFechaNacimientoMesPaciente.setText("1");
        jTextFieldFechaNacimientoMesPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaNacimientoMesPacienteActionPerformed(evt);
            }
        });

        jLabelLugarNacimientoPaciente.setText("Lugar nacimiento");

        jLabelDireccionPaciente.setText("Dirección");

        jButtonMenosAnioPaciente.setText("-");
        jButtonMenosAnioPaciente.setEnabled(false);
        jButtonMenosAnioPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosAnioPacienteMouseClicked(evt);
            }
        });
        jButtonMenosAnioPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosAnioPacienteActionPerformed(evt);
            }
        });

        jLabelApellidosPaciente.setText("Apellidos");

        jTextFieldApellidosPaciente.setEditable(false);
        jTextFieldApellidosPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldApellidosPacienteKeyTyped(evt);
            }
        });

        jButtonMasDiaPaciente.setText("+");
        jButtonMasDiaPaciente.setEnabled(false);
        jButtonMasDiaPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasDiaPacienteMouseClicked(evt);
            }
        });
        jButtonMasDiaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasDiaPacienteActionPerformed(evt);
            }
        });

        jButtonMenosMesPaciente.setText("-");
        jButtonMenosMesPaciente.setEnabled(false);
        jButtonMenosMesPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosMesPacienteMouseClicked(evt);
            }
        });
        jButtonMenosMesPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosMesPacienteActionPerformed(evt);
            }
        });

        jButtonMenosDiaPaciente.setText("-");
        jButtonMenosDiaPaciente.setEnabled(false);
        jButtonMenosDiaPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosDiaPacienteMouseClicked(evt);
            }
        });
        jButtonMenosDiaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosDiaPacienteActionPerformed(evt);
            }
        });

        jLabelEmailPaciente.setText("Email");

        jTextFieldDireccionPaciente.setEditable(false);
        jTextFieldDireccionPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDireccionPacienteKeyTyped(evt);
            }
        });

        jTextFieldFechaNacimientoDiaPaciente.setEditable(false);
        jTextFieldFechaNacimientoDiaPaciente.setText("1");

        jButtonMasAnioPaciente.setText("+");
        jButtonMasAnioPaciente.setEnabled(false);
        jButtonMasAnioPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasAnioPacienteMouseClicked(evt);
            }
        });
        jButtonMasAnioPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasAnioPacienteActionPerformed(evt);
            }
        });

        jTextFieldEmailPaciente.setEditable(false);
        jTextFieldEmailPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEmailPacienteKeyTyped(evt);
            }
        });

        jTextFieldFechaNacimientoAnioPaciente.setEditable(false);
        jTextFieldFechaNacimientoAnioPaciente.setText("1950");
        jTextFieldFechaNacimientoAnioPaciente.setEnabled(false);

        jTextFieldContraseniaPaciente.setColumns(8);
        jTextFieldContraseniaPaciente.setEditable(false);

        jButtonMasMesPaciente.setText("+");
        jButtonMasMesPaciente.setEnabled(false);
        jButtonMasMesPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasMesPacienteMouseClicked(evt);
            }
        });
        jButtonMasMesPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasMesPacienteActionPerformed(evt);
            }
        });

        jLabelFechaNacimientoPaciente.setText("Fecha nacimiento");

        org.jdesktop.layout.GroupLayout jPanelGestionarPacienteLayout = new org.jdesktop.layout.GroupLayout(jPanelGestionarPaciente);
        jPanelGestionarPaciente.setLayout(jPanelGestionarPacienteLayout);
        jPanelGestionarPacienteLayout.setHorizontalGroup(
            jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelGestionarPacienteLayout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelGestionarPacienteLayout.createSequentialGroup()
                        .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                                .add(99, 99, 99)
                                .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel3)
                                    .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                                        .add(1, 1, 1)
                                        .add(jLabelGestionarPaciente4))))
                            .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                                .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabelFechaNacimientoPaciente)
                                    .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                                        .add(jButtonMasDiaPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jButtonMasMesPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jButtonMasAnioPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                                        .add(10, 10, 10)
                                        .add(jTextFieldFechaNacimientoDiaPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(17, 17, 17)
                                        .add(jTextFieldFechaNacimientoMesPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(7, 7, 7)
                                        .add(jTextFieldFechaNacimientoAnioPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                                        .add(jButtonMenosDiaPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jButtonMenosMesPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jButtonMenosAnioPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(215, 215, 215)
                                .add(jLabelFotografiaPaciente)
                                .add(34, 34, 34)
                                .add(jLabelFotoPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                                .add(jTextFieldDireccionPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 370, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(40, 40, 40)
                                .add(jTextFieldEmailPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 289, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                                .add(jLabelDireccionPaciente)
                                .add(350, 350, 350)
                                .add(jLabelEmailPaciente))
                            .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                                .add(jLabelNombrePaciente)
                                .add(200, 200, 200)
                                .add(jLabelApellidosPaciente)
                                .add(291, 291, 291)
                                .add(jLabelDNIPaciente))
                            .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                                .add(jTextFieldNombrePaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 210, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(40, 40, 40)
                                .add(jTextFieldApellidosPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 290, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(60, 60, 60)
                                .add(jTextFieldDNIPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(90, 90, 90))
                    .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                        .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelTelefonoPaciente)
                            .add(jTextFieldTelefonoPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(63, 63, 63)
                        .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelLugarNacimientoPaciente)
                            .add(jTextFieldLugarNacimientoPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 300, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTextFieldContraseniaPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabelContraseniaPaciente))
                        .add(107, 107, 107))))
        );
        jPanelGestionarPacienteLayout.setVerticalGroup(
            jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                        .add(39, 39, 39)
                        .add(jLabel3))
                    .add(jLabelGestionarPaciente4))
                .add(18, 18, 18)
                .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelNombrePaciente)
                    .add(jLabelApellidosPaciente)
                    .add(jLabelDNIPaciente))
                .add(14, 14, 14)
                .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextFieldNombrePaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldApellidosPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldDNIPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelDireccionPaciente)
                    .add(jLabelEmailPaciente))
                .add(4, 4, 4)
                .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextFieldDireccionPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldEmailPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                        .add(jLabelTelefonoPaciente)
                        .add(4, 4, 4)
                        .add(jTextFieldTelefonoPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                        .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabelLugarNacimientoPaciente)
                            .add(jLabelContraseniaPaciente))
                        .add(4, 4, 4)
                        .add(jTextFieldLugarNacimientoPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jTextFieldContraseniaPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                        .add(19, 19, 19)
                        .add(jLabelFechaNacimientoPaciente)
                        .add(4, 4, 4)
                        .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jButtonMasDiaPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonMasMesPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonMasAnioPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTextFieldFechaNacimientoDiaPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextFieldFechaNacimientoMesPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextFieldFechaNacimientoAnioPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(2, 2, 2)
                        .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jButtonMenosDiaPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonMenosMesPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonMenosAnioPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanelGestionarPacienteLayout.createSequentialGroup()
                        .add(30, 30, 30)
                        .add(jPanelGestionarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelFotoPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabelFotografiaPaciente))))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jPanelGestionarPaciente.setBounds(1, 0, 900, 530);
        ZonaTrabajo.add(jPanelGestionarPaciente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanelConsultarCitaOnline.setMinimumSize(new java.awt.Dimension(901, 510));
        jPanelConsultarCitaOnline.setPreferredSize(new java.awt.Dimension(901, 531));
        jPanelConsultarCitaOnline.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldMesCita.setEditable(false);
        jTextFieldMesCita.setText("1");
        jTextFieldMesCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMesCitaActionPerformed(evt);
            }
        });
        jPanelConsultarCitaOnline.add(jTextFieldMesCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 33, -1));

        jButtonMenosAnioPersonal.setText("-");
        jButtonMenosAnioPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosAnioPersonalMouseClicked(evt);
            }
        });
        jButtonMenosAnioPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosAnioPersonalActionPerformed(evt);
            }
        });
        jPanelConsultarCitaOnline.add(jButtonMenosAnioPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 50, 40));

        jButtonMasAnioFecha.setText("+");
        jButtonMasAnioFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasAnioFechaMouseClicked(evt);
            }
        });
        jButtonMasAnioFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasAnioFechaActionPerformed(evt);
            }
        });
        jPanelConsultarCitaOnline.add(jButtonMasAnioFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 50, 40));

        jTextFieldAnioCita.setText("1950");
        jTextFieldAnioCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnioCitaActionPerformed(evt);
            }
        });
        jPanelConsultarCitaOnline.add(jTextFieldAnioCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 50, -1));

        jLabelFecha.setText("Fecha cita");
        jPanelConsultarCitaOnline.add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        jTextFieldDiaCita.setEditable(false);
        jTextFieldDiaCita.setText("1");
        jPanelConsultarCitaOnline.add(jTextFieldDiaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 33, -1));

        jButtonMasMesFecha.setText("+");
        jButtonMasMesFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasMesFechaMouseClicked(evt);
            }
        });
        jButtonMasMesFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasMesFechaActionPerformed(evt);
            }
        });
        jPanelConsultarCitaOnline.add(jButtonMasMesFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 50, 40));

        jButtonMasDiaFecha.setText("+");
        jButtonMasDiaFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasDiaFechaMouseClicked(evt);
            }
        });
        jButtonMasDiaFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasDiaFechaActionPerformed(evt);
            }
        });
        jPanelConsultarCitaOnline.add(jButtonMasDiaFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 50, 40));

        jButtonModificarCitaOnline.setText("Modificar");
        jPanelConsultarCitaOnline.add(jButtonModificarCitaOnline, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 93, 39));

        jButtonMenosDiaFecha.setText("-");
        jButtonMenosDiaFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosDiaFechaMouseClicked(evt);
            }
        });
        jButtonMenosDiaFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosDiaFechaActionPerformed(evt);
            }
        });
        jPanelConsultarCitaOnline.add(jButtonMenosDiaFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 50, 40));

        jButtonMenosMesFecha.setText("-");
        jButtonMenosMesFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosMesFechaMouseClicked(evt);
            }
        });
        jButtonMenosMesFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosMesFechaActionPerformed(evt);
            }
        });
        jPanelConsultarCitaOnline.add(jButtonMenosMesFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 50, 40));

        jLabelGestionarPaciente2.setFont(new java.awt.Font("Lucida Grande", 1, 48));
        jLabelGestionarPaciente2.setText("Gestionar Cita Online");
        jPanelConsultarCitaOnline.add(jLabelGestionarPaciente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel2.setText("_____________________________________________________________________________");
        jPanelConsultarCitaOnline.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jButtonLimpiarCita.setText("Limpiar");
        jButtonLimpiarCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLimpiarCitaMouseClicked(evt);
            }
        });
        jButtonLimpiarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarCitaActionPerformed(evt);
            }
        });
        jPanelConsultarCitaOnline.add(jButtonLimpiarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, -1, 39));

        jButtonMasHora.setText("+");
        jButtonMasHora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasHoraMouseClicked(evt);
            }
        });
        jButtonMasHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasHoraActionPerformed(evt);
            }
        });
        jPanelConsultarCitaOnline.add(jButtonMasHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 50, 40));

        jButtonMasMinuto.setText("+");
        jButtonMasMinuto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasMinutoMouseClicked(evt);
            }
        });
        jButtonMasMinuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasMinutoActionPerformed(evt);
            }
        });
        jPanelConsultarCitaOnline.add(jButtonMasMinuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 50, 40));

        jTextFieldHoraCita.setEditable(false);
        jTextFieldHoraCita.setText("1");
        jPanelConsultarCitaOnline.add(jTextFieldHoraCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 33, -1));

        jTextFieldMinutoCita.setEditable(false);
        jTextFieldMinutoCita.setText("1");
        jTextFieldMinutoCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMinutoCitaActionPerformed(evt);
            }
        });
        jPanelConsultarCitaOnline.add(jTextFieldMinutoCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 33, -1));

        jButtonMenosHora.setText("-");
        jButtonMenosHora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosHoraMouseClicked(evt);
            }
        });
        jButtonMenosHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosHoraActionPerformed(evt);
            }
        });
        jPanelConsultarCitaOnline.add(jButtonMenosHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 50, 40));

        jButtonMenosMinuto.setText("-");
        jButtonMenosMinuto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosMinutoMouseClicked(evt);
            }
        });
        jButtonMenosMinuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosMinutoActionPerformed(evt);
            }
        });
        jPanelConsultarCitaOnline.add(jButtonMenosMinuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 50, 40));

        jLabelHoraCita.setText("Hora cita");
        jPanelConsultarCitaOnline.add(jLabelHoraCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, -1, -1));

        jTextAreaInfo.setBackground(new java.awt.Color(255, 204, 102));
        jTextAreaInfo.setColumns(17);
        jTextAreaInfo.setEditable(false);
        jTextAreaInfo.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        jTextAreaInfo.setRows(3);
        jTextAreaInfo.setText("Estás consultando una cita online, si modificas algún campo dale a \"Guardar\" \nSi deseas cancelar dicha cita dale a \"Cancelar\"");
        jScrollPane1.setViewportView(jTextAreaInfo);

        jPanelConsultarCitaOnline.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 780, 120));

        jButtonLimpiarCita1.setText("Cancelar");
        jButtonLimpiarCita1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLimpiarCita1MouseClicked(evt);
            }
        });
        jButtonLimpiarCita1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarCita1ActionPerformed(evt);
            }
        });
        jPanelConsultarCitaOnline.add(jButtonLimpiarCita1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, -1, 39));

        jLabelFecha1.setText("DNI Paciente");
        jPanelConsultarCitaOnline.add(jLabelFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        jLabelFecha2.setText("DNI Médico");
        jPanelConsultarCitaOnline.add(jLabelFecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, -1, -1));

        jTextFieldDNIMedico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDNIMedicoKeyTyped(evt);
            }
        });
        jPanelConsultarCitaOnline.add(jTextFieldDNIMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 90, -1));

        jTextFieldDNIPacienteCita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDNIPacienteCitaKeyTyped(evt);
            }
        });
        jPanelConsultarCitaOnline.add(jTextFieldDNIPacienteCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 90, -1));

        jPanelConsultarCitaOnline.setBounds(0, 0, 901, 531);
        ZonaTrabajo.add(jPanelConsultarCitaOnline, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanelGestionarCitaOnline.setMinimumSize(new java.awt.Dimension(901, 510));
        jPanelGestionarCitaOnline.setPreferredSize(new java.awt.Dimension(901, 531));
        jPanelGestionarCitaOnline.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelGestionarPaciente5.setFont(new java.awt.Font("Lucida Grande", 1, 48));
        jLabelGestionarPaciente5.setText("Gestionar Cita Online");
        jPanelGestionarCitaOnline.add(jLabelGestionarPaciente5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel4.setText("_____________________________________________________________________________");
        jPanelGestionarCitaOnline.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jTextAreaInfo1.setBackground(new java.awt.Color(255, 204, 102));
        jTextAreaInfo1.setColumns(17);
        jTextAreaInfo1.setEditable(false);
        jTextAreaInfo1.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        jTextAreaInfo1.setRows(3);
        jTextAreaInfo1.setText("Tiene 4 opciones para realizar con la cita online: \nSi desea pedir una cita, dale a \"Alta\". \nEn cambio, si desea ver la cita que tiene, dale a \"Consultar\". \nPor otro lado, si desea modificar la cita que tiene, dale a \"Modificar\". \nPor último, si desea cancelar la cita que tiene asignada, dale a \"Cancelar\".");
        jScrollPane2.setViewportView(jTextAreaInfo1);

        jPanelGestionarCitaOnline.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 780, 120));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        jLabel1.setText("Fecha");

        jLabel5.setText("Hora");

        jLabel6.setText("DNI Médico");

        jLabel7.setText("DNI Paciente");

        jButtonAceptarCita.setText("Aceptar");
        jButtonAceptarCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAceptarCitaMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelAltaCitaLayout = new org.jdesktop.layout.GroupLayout(jPanelAltaCita);
        jPanelAltaCita.setLayout(jPanelAltaCitaLayout);
        jPanelAltaCitaLayout.setHorizontalGroup(
            jPanelAltaCitaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelAltaCitaLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelAltaCitaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelAltaCitaLayout.createSequentialGroup()
                        .add(jPanelAltaCitaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                            .add(jPanelAltaCitaLayout.createSequentialGroup()
                                .add(jLabel1)
                                .add(81, 81, 81)
                                .add(jLabel5)
                                .add(94, 94, 94)
                                .add(jLabel6)
                                .add(78, 78, 78)
                                .add(jLabel7)))
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelAltaCitaLayout.createSequentialGroup()
                        .add(jButtonAceptarCita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(222, 222, 222))))
        );
        jPanelAltaCitaLayout.setVerticalGroup(
            jPanelAltaCitaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelAltaCitaLayout.createSequentialGroup()
                .add(jPanelAltaCitaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jLabel6)
                    .add(jLabel5)
                    .add(jLabel7))
                .add(4, 4, 4)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 121, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButtonAceptarCita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelGestionarCitaOnline.add(jPanelAltaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 540, 200));

        jButtonCancelarCita.setText("Cancelar");

        jButtonModificarCita.setText("Modificar");
        jButtonModificarCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonModificarCitaMouseClicked(evt);
            }
        });

        jButtonConsultarCita1.setText("Consultar");
        jButtonConsultarCita1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConsultarCita1MouseClicked(evt);
            }
        });

        jButtonPedirAltaCita.setText("Alta");
        jButtonPedirAltaCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPedirAltaCitaMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelBotonesLayout = new org.jdesktop.layout.GroupLayout(jPanelBotones);
        jPanelBotones.setLayout(jPanelBotonesLayout);
        jPanelBotonesLayout.setHorizontalGroup(
            jPanelBotonesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelBotonesLayout.createSequentialGroup()
                .add(36, 36, 36)
                .add(jButtonPedirAltaCita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(54, 54, 54)
                .add(jButtonConsultarCita1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 62, Short.MAX_VALUE)
                .add(jButtonModificarCita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(56, 56, 56)
                .add(jButtonCancelarCita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanelBotonesLayout.setVerticalGroup(
            jPanelBotonesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelBotonesLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanelBotonesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonCancelarCita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonPedirAltaCita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonConsultarCita1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonModificarCita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelGestionarCitaOnline.add(jPanelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 580, 60));

        jPanelGestionarCitaOnline.setBounds(0, 0, 901, 531);
        ZonaTrabajo.add(jPanelGestionarCitaOnline, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(ZonaTrabajo);
        ZonaTrabajo.setBounds(13, 185, 920, 550);

        jPanelUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelUsuario.setLayout(null);

        jLabelUsuario.setText("Usuario:");
        jPanelUsuario.add(jLabelUsuario);
        jLabelUsuario.setBounds(90, 0, 53, 17);

        jLabelTipoUsuario.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabelTipoUsuario.setText("Tipo Usuario");
        jPanelUsuario.add(jLabelTipoUsuario);
        jLabelTipoUsuario.setBounds(90, 30, 120, 17);

        jLabelNombreUsuario.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabelNombreUsuario.setText("Nombre");
        jPanelUsuario.add(jLabelNombreUsuario);
        jLabelNombreUsuario.setBounds(90, 60, 120, 17);
        jPanelUsuario.add(jLabelTipoUsuarioIdentificado);
        jLabelTipoUsuarioIdentificado.setBounds(10, 10, 70, 70);

        getContentPane().add(jPanelUsuario);
        jPanelUsuario.setBounds(665, 47, 220, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jLabelIconoInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoInicioMouseEntered
        // TODO add your handling code here:
        jLabelIconoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Inicio-Activado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoInicioMouseEntered

    private void jLabelIconoInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoInicioMouseExited
        // TODO add your handling code here:
        jLabelIconoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Inicio-Desactivado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoInicioMouseExited

    private void jLabelIconoAyudaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoAyudaMouseExited
        // TODO add your handling code here:
        jLabelIconoAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Ayuda-Desactivado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoAyudaMouseExited

    private void jLabelIconoAyudaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoAyudaMouseEntered
        // TODO add your handling code here:
        jLabelIconoAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Ayuda-Activado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoAyudaMouseEntered

    private void jLabelIconoSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoSalirMouseExited
        // TODO add your handling code here:
        jLabelIconoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Salir-Desactivado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoSalirMouseExited

    private void jLabelIconoSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoSalirMouseEntered
        // TODO add your handling code here:
        jLabelIconoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Salir-Activado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoSalirMouseEntered

    private void jLabelIconoSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelIconoSalirMouseClicked

    private void jLabelIconoAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoAyudaMouseClicked
        // TODO add your handling code here:
        new Ayuda().setVisible(true);
    }//GEN-LAST:event_jLabelIconoAyudaMouseClicked

    private void jButtonGestionarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGestionarPacienteMouseClicked
        // TODO add your handling code here:
        mostrarPanel("GestionarPaciente");
    }//GEN-LAST:event_jButtonGestionarPacienteMouseClicked

    private void jButtonGestionarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGestionarPacienteActionPerformed

    private void jLabelIconoInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoInicioMouseClicked
        // TODO add your handling code here:
        mostrarPanel("Principal");
    }//GEN-LAST:event_jLabelIconoInicioMouseClicked

    private void jButtonLimpiarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarCitaActionPerformed
        // TODO add your handling code here:
        limpiarFormulario("GestionarCitaOnlineAlta");
}//GEN-LAST:event_jButtonLimpiarCitaActionPerformed

    private void jButtonMasMesFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasMesFechaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonMasMesFechaActionPerformed

    private void jButtonMasAnioFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasAnioFechaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonMasAnioFechaActionPerformed

    private void jButtonMenosDiaFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosDiaFechaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonMenosDiaFechaActionPerformed

    private void jButtonMenosMesFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosMesFechaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonMenosMesFechaActionPerformed

    private void jButtonMasDiaFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasDiaFechaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonMasDiaFechaActionPerformed

    private void jButtonMenosAnioPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosAnioPersonalActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonMenosAnioPersonalActionPerformed

    private void jTextFieldMesCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMesCitaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldMesCitaActionPerformed

    private void jTextFieldFechaNacimientoMesPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaNacimientoMesPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaNacimientoMesPacienteActionPerformed

    private void jButtonMenosAnioPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosAnioPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenosAnioPacienteActionPerformed

    private void jButtonMasDiaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasDiaPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMasDiaPacienteActionPerformed

    private void jButtonMenosMesPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosMesPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenosMesPacienteActionPerformed

    private void jButtonMenosDiaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosDiaPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenosDiaPacienteActionPerformed

    private void jButtonMasAnioPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasAnioPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMasAnioPacienteActionPerformed

    private void jButtonMasMesPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasMesPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMasMesPacienteActionPerformed

    private void jButtonLimpiarCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLimpiarCitaMouseClicked
        // TODO add your handling code here:
        limpiarFormulario("GestionarCitaOnline");
    }//GEN-LAST:event_jButtonLimpiarCitaMouseClicked

    private void jButtonMasDiaPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasDiaPacienteMouseClicked
        // TODO add your handling code here:
        int num = 0;
        
        num = Integer.parseInt(jTextFieldFechaNacimientoDiaPaciente.getText());

        if(num < 31)
            num ++;
        
        String numString;
        numString = String.valueOf(num);
        jTextFieldFechaNacimientoDiaPaciente.setText(numString);
    }//GEN-LAST:event_jButtonMasDiaPacienteMouseClicked

    private void jButtonMenosDiaPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosDiaPacienteMouseClicked
        // TODO add your handling code here:
        int num = 0;

        num = Integer.parseInt(jTextFieldFechaNacimientoDiaPaciente.getText());

        if(num > 1)
            num --;

        String numString;
        numString = String.valueOf(num);
        jTextFieldFechaNacimientoDiaPaciente.setText(numString);
    }//GEN-LAST:event_jButtonMenosDiaPacienteMouseClicked

    private void jButtonMasMesPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasMesPacienteMouseClicked
        // TODO add your handling code here:
        int num = 0;

        num = Integer.parseInt(jTextFieldFechaNacimientoMesPaciente.getText());

        if(num < 12)
            num ++;

        String numString;
        numString = String.valueOf(num);
        jTextFieldFechaNacimientoMesPaciente.setText(numString);
    }//GEN-LAST:event_jButtonMasMesPacienteMouseClicked

    private void jButtonMenosMesPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosMesPacienteMouseClicked
        // TODO add your handling code here:
        int num = 0;

        num = Integer.parseInt(jTextFieldFechaNacimientoMesPaciente.getText());

        if(num > 1)
            num --;

        String numString;
        numString = String.valueOf(num);
        jTextFieldFechaNacimientoMesPaciente.setText(numString);
    }//GEN-LAST:event_jButtonMenosMesPacienteMouseClicked

    private void jButtonMasAnioPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasAnioPacienteMouseClicked
        // TODO add your handling code here:
        int num = 0;
        int anioActual = 0;

        num = Integer.parseInt(jTextFieldFechaNacimientoAnioPaciente.getText());

        Calendar fechaActual = Calendar.getInstance();
        anioActual = fechaActual.get(Calendar.YEAR);

        if(num < anioActual)
            num ++;

        String numString;
        numString = String.valueOf(num);
        jTextFieldFechaNacimientoAnioPaciente.setText(numString);
    }//GEN-LAST:event_jButtonMasAnioPacienteMouseClicked

    private void jButtonMenosAnioPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosAnioPacienteMouseClicked
        // TODO add your handling code here:
        int num = 0;

        num = Integer.parseInt(jTextFieldFechaNacimientoAnioPaciente.getText());

        if(num > 1900)
            num --;

        String numString;
        numString = String.valueOf(num);
        jTextFieldFechaNacimientoAnioPaciente.setText(numString);
    }//GEN-LAST:event_jButtonMenosAnioPacienteMouseClicked

    private void jButtonMasDiaFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasDiaFechaMouseClicked
        // TODO add your handling code here:
        int num = 0;

        num = Integer.parseInt(jTextFieldDiaCita.getText());

        if(num < 31)
            num ++;

        String numString;
        numString = String.valueOf(num);
        jTextFieldDiaCita.setText(numString);
    }//GEN-LAST:event_jButtonMasDiaFechaMouseClicked

    private void jButtonMenosDiaFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosDiaFechaMouseClicked
        // TODO add your handling code here:
        int num = 0;

        num = Integer.parseInt(jTextFieldDiaCita.getText());

        if(num > 1)
            num --;

        String numString;
        numString = String.valueOf(num);
        jTextFieldDiaCita.setText(numString);
    }//GEN-LAST:event_jButtonMenosDiaFechaMouseClicked

    private void jButtonMasMesFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasMesFechaMouseClicked
        // TODO add your handling code here:
        int num = 0;

        num = Integer.parseInt(jTextFieldMesCita.getText());

        if(num < 12)
            num ++;

        String numString;
        numString = String.valueOf(num);
        jTextFieldMesCita.setText(numString);
    }//GEN-LAST:event_jButtonMasMesFechaMouseClicked

    private void jButtonMenosMesFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosMesFechaMouseClicked
        // TODO add your handling code here:
        int num = 0;

        num = Integer.parseInt(jTextFieldMesCita.getText());

        if(num > 1)
            num --;

        String numString;
        numString = String.valueOf(num);
        jTextFieldMesCita.setText(numString);
    }//GEN-LAST:event_jButtonMenosMesFechaMouseClicked

    private void jButtonMasAnioFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasAnioFechaMouseClicked
        // TODO add your handling code here:
        int num = 0;
        int anioActual = 0;

        num = Integer.parseInt(jTextFieldAnioCita.getText());

        Calendar fechaActual = Calendar.getInstance();
        anioActual = fechaActual.get(Calendar.YEAR);

        if(num < anioActual)
            num ++;

        String numString;
        numString = String.valueOf(num);
        jTextFieldAnioCita.setText(numString);
    }//GEN-LAST:event_jButtonMasAnioFechaMouseClicked

    private void jButtonMenosAnioPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosAnioPersonalMouseClicked
        // TODO add your handling code here:
        int num = 0;
        num = Integer.parseInt(jTextFieldAnioCita.getText());

        if(num > 1900)
            num --;

        String numString;
        numString = String.valueOf(num);
        jTextFieldAnioCita.setText(numString);
    }//GEN-LAST:event_jButtonMenosAnioPersonalMouseClicked

    private void jButtonGestionarCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGestionarCitaMouseClicked
        // TODO add your handling code here:
        mostrarPanel("GestionarCitaOnline");
    }//GEN-LAST:event_jButtonGestionarCitaMouseClicked

    private void jButtonMasHoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasHoraMouseClicked
        // TODO add your handling code here:
        int hora = 0;

        hora = Integer.parseInt(jTextFieldHoraCita.getText());

        if(hora < 24){
            hora ++;
            }else{
                hora = 0;
            }

        String numString;
        numString = String.valueOf(hora);
        jTextFieldHoraCita.setText(numString);
    }//GEN-LAST:event_jButtonMasHoraMouseClicked

    private void jButtonMasHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMasHoraActionPerformed

    private void jButtonMasMinutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasMinutoMouseClicked
        // TODO add your handling code here:
        int minuto = 0;

        minuto = Integer.parseInt(jTextFieldMinutoCita.getText());

        if(minuto < 60)
            minuto ++;

        String numString;
        numString = String.valueOf(minuto);
        jTextFieldMinutoCita.setText(numString);
    }//GEN-LAST:event_jButtonMasMinutoMouseClicked

    private void jButtonMasMinutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasMinutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMasMinutoActionPerformed

    private void jTextFieldMinutoCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMinutoCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMinutoCitaActionPerformed

    private void jButtonMenosHoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosHoraMouseClicked
        // TODO add your handling code here:
        int hora = 0;

        hora = Integer.parseInt(jTextFieldHoraCita.getText());

        if(hora > 0){
            hora --;
            }else{
                hora = 24;
            }

        String numString;
        numString = String.valueOf(hora);
        jTextFieldHoraCita.setText(numString);
    }//GEN-LAST:event_jButtonMenosHoraMouseClicked

    private void jButtonMenosHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenosHoraActionPerformed

    private void jButtonMenosMinutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosMinutoMouseClicked
        // TODO add your handling code here:
        int minuto = 0;

        minuto = Integer.parseInt(jTextFieldMinutoCita.getText());

        if(minuto > 0)
            minuto --;

        String numString;
        numString = String.valueOf(minuto);
        jTextFieldMinutoCita.setText(numString);
    }//GEN-LAST:event_jButtonMenosMinutoMouseClicked

    private void jButtonMenosMinutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosMinutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenosMinutoActionPerformed

    private void jTextFieldAnioCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnioCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAnioCitaActionPerformed

    private void jButtonPedirAltaCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPedirAltaCitaMouseClicked
        // TODO add your handling code here:
        jPanelAltaCita.setVisible(true);
        jPanelBotones.setVisible(false);

    }//GEN-LAST:event_jButtonPedirAltaCitaMouseClicked

    private void jTextFieldTelefonoPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoPacienteKeyTyped
        // TODO add your handling code here:

        /**Comprobamos que no se teclee una letra*/
        char teclaPresionada = evt.getKeyChar();
        if(Character.isDigit(teclaPresionada) == false)
            evt.consume();
    }//GEN-LAST:event_jTextFieldTelefonoPacienteKeyTyped

    private void jTextFieldNombrePacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombrePacienteKeyTyped
        // TODO add your handling code here:

        /**Comprobamos que no se teclee un número*/
        char teclaPresionada = evt.getKeyChar();
        if(Character.isDigit(teclaPresionada) == true)
            evt.consume();
}//GEN-LAST:event_jTextFieldNombrePacienteKeyTyped

    private void jTextFieldDNIPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDNIPacienteKeyTyped
        // TODO add your handling code here:

        /**Limitamos a que el DNI siempre sea correcto sintácticamente*/
        char teclaPresionada = evt.getKeyChar();

        if(jTextFieldDNIPaciente.getText().length() < 8)
            if(Character.isDigit(teclaPresionada) == false)
                evt.consume();

        if(jTextFieldDNIPaciente.getText().length() == 8)
            if(Character.isDigit(teclaPresionada) == true){
                evt.consume();
            }else if(Character.isLowerCase(teclaPresionada)){
                jTextFieldDNIPaciente.setText(jTextFieldDNIPaciente.getText().toUpperCase());
            }

        if(jTextFieldDNIPaciente.getText().length() > 8)
            evt.consume();
}//GEN-LAST:event_jTextFieldDNIPacienteKeyTyped

    private void jTextFieldApellidosPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidosPacienteKeyTyped
        // TODO add your handling code here:

        /**Comprobamos que no se teclee un número*/
        char teclaPresionada = evt.getKeyChar();
        if(Character.isDigit(teclaPresionada) == true)
            evt.consume();
}//GEN-LAST:event_jTextFieldApellidosPacienteKeyTyped

    private void jTextFieldDireccionPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDireccionPacienteKeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldDireccionPacienteKeyTyped

    private void jTextFieldEmailPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailPacienteKeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldEmailPacienteKeyTyped

    private void jTextFieldLugarNacimientoPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLugarNacimientoPacienteKeyTyped
        // TODO add your handling code here:

        /**Comprobamos que no se teclee un número*/
        char teclaPresionada = evt.getKeyChar();
        if(Character.isDigit(teclaPresionada) == true)
            evt.consume();
}//GEN-LAST:event_jTextFieldLugarNacimientoPacienteKeyTyped

    private void jButtonLimpiarCita1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLimpiarCita1MouseClicked





        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimpiarCita1MouseClicked

    private void jButtonLimpiarCita1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarCita1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimpiarCita1ActionPerformed

    private void jTextFieldDNIPacienteCitaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDNIPacienteCitaKeyTyped
        // TODO add your handling code here:

        /**Limitamos a que el DNI siempre sea correcto sintácticamente*/
        char teclaPresionada = evt.getKeyChar();

        if(jTextFieldDNIPacienteCita.getText().length() < 8)
            if(Character.isDigit(teclaPresionada) == false)
                evt.consume();

        if(jTextFieldDNIPacienteCita.getText().length() == 8)
            if(Character.isDigit(teclaPresionada) == true){
                evt.consume();
            }else if(Character.isLowerCase(teclaPresionada)){
                jTextFieldDNIPacienteCita.setText(jTextFieldDNIPacienteCita.getText().toUpperCase());
            }

        if(jTextFieldDNIPacienteCita.getText().length() > 8)
            evt.consume();
    }//GEN-LAST:event_jTextFieldDNIPacienteCitaKeyTyped

    private void jTextFieldDNIMedicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDNIMedicoKeyTyped
        // TODO add your handling code here:

        /**Limitamos a que el DNI siempre sea correcto sintácticamente*/
        char teclaPresionada = evt.getKeyChar();

        if(jTextFieldDNIMedico.getText().length() < 8)
            if(Character.isDigit(teclaPresionada) == false)
                evt.consume();

        if(jTextFieldDNIMedico.getText().length() == 8)
            if(Character.isDigit(teclaPresionada) == true){
                evt.consume();
            }else if(Character.isLowerCase(teclaPresionada)){
                jTextFieldDNIMedico.setText(jTextFieldDNIMedico.getText().toUpperCase());
            }

        if(jTextFieldDNIMedico.getText().length() > 8)
            evt.consume();
    }//GEN-LAST:event_jTextFieldDNIMedicoKeyTyped

    private void jButtonAceptarCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAceptarCitaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAceptarCitaMouseClicked

    private void jButtonConsultarCita1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConsultarCita1MouseClicked
        // TODO add your handling code here:
        mostrarPanel("ConsultarCitaOnline");
    }//GEN-LAST:event_jButtonConsultarCita1MouseClicked

    private void jButtonModificarCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonModificarCitaMouseClicked
        // TODO add your handling code here:
        mostrarPanel("ConsultarCitaOnline");
    }//GEN-LAST:event_jButtonModificarCitaMouseClicked


    /*Comprueba que la fecha introducida es correcta
     * 
     *@param persona, string que indica si se trata del formulario de Paciente o Personal
     *@return booleano diciendo si es válido o no
     */
    private boolean compruebaFecha(String persona){
        
        int dia = 0;
        int mes = 0;
        int anio = 0;
        int diaActual;
        int mesActual;
        int anioActual;

        if(persona.equals("GestionarPaciente")){
            dia = Integer.parseInt(jTextFieldFechaNacimientoDiaPaciente.getText());
            mes = Integer.parseInt(jTextFieldFechaNacimientoMesPaciente.getText());
            anio = Integer.parseInt(jTextFieldFechaNacimientoAnioPaciente.getText());
        }

        if(persona.equals("GestionarCitaOnline")){
            dia = Integer.parseInt(jTextFieldDiaCita.getText());
            mes = Integer.parseInt(jTextFieldMesCita.getText());
            anio = Integer.parseInt(jTextFieldAnioCita.getText());
        }

        Calendar fechaActual = Calendar.getInstance();
        diaActual = fechaActual.get(Calendar.DATE);
        mesActual = fechaActual.get(Calendar.MONTH);
        anioActual = fechaActual.get(Calendar.YEAR);


        /**Si se sale de los rangos*/
        if((dia <= 0)
                || (dia > 31)
                || (mes <= 0)
                || (mes > 12)
                || (anio < 1900)
                || (anio > anioActual) ){
            return false;
        }

        /**Si ha nacido en el año actual, hay que ver que el mes no sea mayor que el actual*/
        /**Si ha nacido en el año y mes actual, hay que comprobar que el dia sea menor que el actual*/
        if(anio == anioActual){
            if(mes > mesActual){
                return false;
            } else{
                if(dia > diaActual){
                    return false;
                }
            }
        }

        /**Si estamos en un mes que tiene 30 días o 29 en el caso de febrero, hay que comprobar que no se pase*/
        if(mes%2 == 0){
            if((mes == 2) && (dia >29)){
                return false;
            }else{
                if(dia > 30){
                    return false;
                }
            }
        }

        return true;

    }


     /*Borra el formulario elegido
     *
     *@param persona, string que indica si se trata del formulario de Paciente o Personal
     */
    private void limpiarFormulario(String persona){

        String diaActual;
        String mesActual;
        String anioActual;
        String horaActual;
        String minutoActual;

        Calendar fechaActual = Calendar.getInstance();
        diaActual = Integer.toString(fechaActual.get(Calendar.DATE));
        mesActual = Integer.toString(fechaActual.get(Calendar.MONTH));
        anioActual = Integer.toString(fechaActual.get(Calendar.YEAR));
        horaActual = Integer.toString(fechaActual.get(Calendar.HOUR_OF_DAY));
        minutoActual = Integer.toString(fechaActual.get(Calendar.MINUTE));


        if(persona.equals("GestionarPaciente")){
            jTextFieldNombrePaciente.setText("");
            jTextFieldApellidosPaciente.setText("");
            jTextFieldDNIPaciente.setText("");
            jTextFieldDireccionPaciente.setText("");
            jTextFieldEmailPaciente.setText("");
            jTextFieldTelefonoPaciente.setText("");
            jTextFieldContraseniaPaciente.setText("");
            jTextFieldLugarNacimientoPaciente.setText("");

            jLabelFotoPaciente.setIcon(null);
        }

        if(persona.equals("GestionarCitaOnlineAlta")){
            jTextFieldDiaCita.setText(diaActual);
            jTextFieldMesCita.setText(mesActual);
            jTextFieldAnioCita.setText(anioActual);
            jTextFieldHoraCita.setText(horaActual);
            jTextFieldMinutoCita.setText(minutoActual);        }
    }

  
    /*Muestra el panel elegido en ZonaTrabajo
     *
     *@param panel, string que indica el panel a mostrar
     */
    private void mostrarPanel(String panel){


        if(panel.equals("Principal")){

            /**Hacemos visible el botón jLabelIconoInicio*/
            jLabelInicio.setVisible(false);
            jLabelIconoInicio.setVisible(false);

            /**Hacemos visible el panel seleccionado*/
            jPanelPrincipal.setVisible(true);
            jPanelGestionarPaciente.setVisible(false);
            jPanelGestionarCitaOnline.setVisible(false);
            jPanelConsultarCitaOnline.setVisible(false);


            /**Activamos el marco*/
            jPanelPrincipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
            jPanelGestionarPaciente.setBorder(null);
            jPanelGestionarCitaOnline.setBorder(null);
            jPanelConsultarCitaOnline.setBorder(null);
        }

        if(panel.equals("GestionarPaciente")){

            /**Hacemos visible el botón jLabelIconoInicio*/
            jLabelInicio.setVisible(true);
            jLabelIconoInicio.setVisible(true);

            /**Insertamos icono de foto anónima*/
            jLabelFotoPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Foto-Anonima.png"))); // NOI18N


            /**Hacemos visible el panel seleccionado*/
            jPanelPrincipal.setVisible(false);
            jPanelGestionarPaciente.setVisible(true);
            jPanelGestionarCitaOnline.setVisible(false);
            jPanelConsultarCitaOnline.setVisible(false);


            /**Activamos el marco*/
            jPanelPrincipal.setBorder(null);
            jPanelGestionarPaciente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
            jPanelGestionarCitaOnline.setBorder(null);
            jPanelConsultarCitaOnline.setBorder(null);
        }

        if(panel.equals("GestionarCitaOnline")){

            /**Hacemos visible el botón jLabelIconoInicio*/
            jLabelInicio.setVisible(true);
            jLabelIconoInicio.setVisible(true);
            jPanelAltaCita.setVisible(false);
            jPanelBotones.setVisible(true);


            /**Hacemos visible el panel seleccionado*/
            jPanelPrincipal.setVisible(false);
            jPanelGestionarPaciente.setVisible(false);
            jPanelGestionarCitaOnline.setVisible(true);
            jPanelConsultarCitaOnline.setVisible(false);


            /**Activamos el marco*/
            jPanelPrincipal.setBorder(null);
            jPanelGestionarPaciente.setBorder(null);
            jPanelGestionarCitaOnline.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
            jPanelConsultarCitaOnline.setBorder(null);
        }

        if(panel.equals("ConsultarCitaOnline")){

            /**Limpiamos posibles datos introducidos anteriormente*/
            limpiarFormulario("ConsultarCitaOnline");

            /**Hacemos visible el botón jLabelIconoInicio*/
            jLabelInicio.setVisible(true);
            jLabelIconoInicio.setVisible(true);

            /**Hacemos visible el panel seleccionado*/
            jPanelPrincipal.setVisible(false);
            jPanelGestionarPaciente.setVisible(false);
            jPanelGestionarCitaOnline.setVisible(false);
            jPanelConsultarCitaOnline.setVisible(true);


            /**Activamos el marco*/
            jPanelPrincipal.setBorder(null);
            jPanelGestionarPaciente.setBorder(null);
            jPanelGestionarCitaOnline.setBorder(null);
            jPanelConsultarCitaOnline.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        }



    }


     /*Carga la foto en el formulario pasado por parámetro
     *
     *@param formulario, string que indica el formulario donde cargar la foto
     */
    private void cargarFoto(String formulario){

        if(formulario.equals("GestionarPaciente")){
            JFileChooser dlg = new JFileChooser();
            int resp = dlg.showOpenDialog(this);
            if (resp == JFileChooser.APPROVE_OPTION){
                try{
                    ImageIcon icono = new ImageIcon(dlg.getSelectedFile().getCanonicalPath());
                    Image imagen = icono.getImage();
                    ImageIcon aescala = new ImageIcon(imagen.getScaledInstance(130,150,Image.SCALE_SMOOTH));
                    jLabelFotoPaciente.setIcon(aescala); // NOI18N
                }
                catch(Exception ex){
                    System.err.print("Error al leer el archivo");
                }
            }
        }

    }


    
    // @param args the command line arguments
    
/*    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Paciente("Paciente", "paciente").setVisible(true);
            }
        });
    }
*/
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane ZonaTrabajo;
    private javax.swing.JButton jButtonAceptarCita;
    private javax.swing.JButton jButtonCancelarCita;
    private javax.swing.JButton jButtonConsultarCita1;
    private javax.swing.JButton jButtonGestionarCita;
    private javax.swing.JButton jButtonGestionarPaciente;
    private javax.swing.JButton jButtonLimpiarCita;
    private javax.swing.JButton jButtonLimpiarCita1;
    private javax.swing.JButton jButtonMasAnioFecha;
    private javax.swing.JButton jButtonMasAnioPaciente;
    private javax.swing.JButton jButtonMasDiaFecha;
    private javax.swing.JButton jButtonMasDiaPaciente;
    private javax.swing.JButton jButtonMasHora;
    private javax.swing.JButton jButtonMasMesFecha;
    private javax.swing.JButton jButtonMasMesPaciente;
    private javax.swing.JButton jButtonMasMinuto;
    private javax.swing.JButton jButtonMenosAnioPaciente;
    private javax.swing.JButton jButtonMenosAnioPersonal;
    private javax.swing.JButton jButtonMenosDiaFecha;
    private javax.swing.JButton jButtonMenosDiaPaciente;
    private javax.swing.JButton jButtonMenosHora;
    private javax.swing.JButton jButtonMenosMesFecha;
    private javax.swing.JButton jButtonMenosMesPaciente;
    private javax.swing.JButton jButtonMenosMinuto;
    private javax.swing.JButton jButtonModificarCita;
    private javax.swing.JButton jButtonModificarCitaOnline;
    private javax.swing.JButton jButtonPedirAltaCita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelApellidosPaciente;
    private javax.swing.JLabel jLabelAyuda;
    private javax.swing.JLabel jLabelCentroMedico;
    private javax.swing.JLabel jLabelContraseniaPaciente;
    private javax.swing.JLabel jLabelDNIPaciente;
    private javax.swing.JLabel jLabelDireccionPaciente;
    private javax.swing.JLabel jLabelEmailPaciente;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelFecha1;
    private javax.swing.JLabel jLabelFecha2;
    private javax.swing.JLabel jLabelFechaNacimientoPaciente;
    private javax.swing.JLabel jLabelFotoPaciente;
    private javax.swing.JLabel jLabelFotografiaPaciente;
    private javax.swing.JLabel jLabelGestionarCita1;
    private javax.swing.JLabel jLabelGestionarPaciente2;
    private javax.swing.JLabel jLabelGestionarPaciente3;
    private javax.swing.JLabel jLabelGestionarPaciente4;
    private javax.swing.JLabel jLabelGestionarPaciente5;
    private javax.swing.JLabel jLabelHoraCita;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JLabel jLabelIconoAyuda;
    private javax.swing.JLabel jLabelIconoInicio;
    private javax.swing.JLabel jLabelIconoSalir;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelLugarNacimientoPaciente;
    private javax.swing.JLabel jLabelNombrePaciente;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JLabel jLabelSalir;
    private javax.swing.JLabel jLabelTelefonoPaciente;
    private javax.swing.JLabel jLabelTipoUsuario;
    private javax.swing.JLabel jLabelTipoUsuarioIdentificado;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanelAltaCita;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelConsultarCitaOnline;
    private javax.swing.JPanel jPanelGestionarCitaOnline;
    private javax.swing.JPanel jPanelGestionarPaciente;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaInfo;
    private javax.swing.JTextArea jTextAreaInfo1;
    private javax.swing.JTextField jTextFieldAnioCita;
    private javax.swing.JTextField jTextFieldApellidosPaciente;
    private javax.swing.JTextField jTextFieldContraseniaPaciente;
    private javax.swing.JTextField jTextFieldDNIMedico;
    private javax.swing.JTextField jTextFieldDNIPaciente;
    private javax.swing.JTextField jTextFieldDNIPacienteCita;
    private javax.swing.JTextField jTextFieldDiaCita;
    private javax.swing.JTextField jTextFieldDireccionPaciente;
    private javax.swing.JTextField jTextFieldEmailPaciente;
    private javax.swing.JTextField jTextFieldFechaNacimientoAnioPaciente;
    private javax.swing.JTextField jTextFieldFechaNacimientoDiaPaciente;
    private javax.swing.JTextField jTextFieldFechaNacimientoMesPaciente;
    private javax.swing.JTextField jTextFieldHoraCita;
    private javax.swing.JTextField jTextFieldLugarNacimientoPaciente;
    private javax.swing.JTextField jTextFieldMesCita;
    private javax.swing.JTextField jTextFieldMinutoCita;
    private javax.swing.JTextField jTextFieldNombrePaciente;
    private javax.swing.JTextField jTextFieldTelefonoPaciente;
    // End of variables declaration//GEN-END:variables

}
