/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal_Administrador.java
 *
 * Created on 16-mar-2011, 18:27:18
 */

package Interfaz;

import java.awt.Image;
import CentroMedico.*;
import BaseDatos.*;
import java.util.Calendar.*;
import java.util.Calendar;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;



/**
 *
 * @author fran_gestion
 */
public class UI_Personal extends javax.swing.JFrame {

    /** Creates new form Principal_Administrador */
    public UI_Personal() {
        initComponents();
    }

    public UI_Personal(String nombreUsuario, String tipoUsuario) throws SQLException{
        initComponents();

        /**Ponemos las etiquetas del usuario que ha entrado*/
        jLabelNombreUsuario.setText(nombreUsuario);
        jLabelTipoUsuario.setText(tipoUsuario);

        /**Mostramos el panel Principal*/
        mostrarPanel("Principal");
        try {
            identificarPersonal(nombreUsuario);
        } catch (SQLException ex) {
            Logger.getLogger(UI_Personal.class.getName()).log(Level.SEVERE, null, ex);
        }

        /**Cargamos la foto de login*/
        jLabelTipoUsuarioIdentificado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Tipo-Usuario-Personal.png"))); // NOI18N

        /**Enlazamos grupo botones de GestionarPersonal y ConsultarTurno*/

        buttonGroup1.add(jRadioButtonManiana);
        buttonGroup1.add(jRadioButtonTarde1);
        buttonGroup1.add(jRadioButtonNoche);
        jRadioButtonManiana.setSelected(true);

        buttonGroup2.add(jRadioButtonAnalista);
        buttonGroup2.add(jRadioButtonFarmaceutico);
        buttonGroup2.add(jRadioButtonMedico);
        buttonGroup2.add(jRadioButtonRadiologo);
        jRadioButtonAnalista.setSelected(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabelCentroMedico = new javax.swing.JLabel();
        jLabelIconoInicio = new javax.swing.JLabel();
        jLabelInicio = new javax.swing.JLabel();
        jLabelIconoAyuda = new javax.swing.JLabel();
        jLabelIconoSalir = new javax.swing.JLabel();
        jLabelAyuda = new javax.swing.JLabel();
        jLabelSalir = new javax.swing.JLabel();
        jLabelIcono = new javax.swing.JLabel();
        ZonaTrabajo = new javax.swing.JLayeredPane();
        jPanelPrincipal = new javax.swing.JPanel();
        jButtonConsultarDatosPersonales = new javax.swing.JButton();
        jLabelGestionarPaciente3 = new javax.swing.JLabel();
        jLabelConsultarTurno = new javax.swing.JLabel();
        jButtonGestionarCita = new javax.swing.JButton();
        jPanelConsultarDatosPersonales = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelGestionarPaciente4 = new javax.swing.JLabel();
        jTextFieldNombrePersonal = new javax.swing.JTextField();
        jLabelFotoPersonal = new javax.swing.JLabel();
        jTextFieldTelefonoPersonal = new javax.swing.JTextField();
        jLabelContraseniaPersonal = new javax.swing.JLabel();
        jTextFieldDNIPersonal = new javax.swing.JTextField();
        jLabelNombrePersonal = new javax.swing.JLabel();
        jLabelFotografiaersonal = new javax.swing.JLabel();
        jLabelDNIPersonal = new javax.swing.JLabel();
        jTextFieldLugarNacimientoPersonal = new javax.swing.JTextField();
        jLabelTelefonoPersonal = new javax.swing.JLabel();
        jTextFieldFechaNacimientoMesersonal = new javax.swing.JTextField();
        jLabelLugarNacimientoPersonal = new javax.swing.JLabel();
        jLabelDireccionPersonal = new javax.swing.JLabel();
        jButtonMenosAnioPersona = new javax.swing.JButton();
        jLabelApellidosPersonal = new javax.swing.JLabel();
        jTextFieldApellidosPersonal = new javax.swing.JTextField();
        jButtonMasDiaPersonal = new javax.swing.JButton();
        jButtonMenosMesPersonal = new javax.swing.JButton();
        jButtonMenosDiaPersonal = new javax.swing.JButton();
        jLabelEmailPersonal = new javax.swing.JLabel();
        jTextFieldDireccionPersonal = new javax.swing.JTextField();
        jTextFieldFechaNacimientoDiaPersonal = new javax.swing.JTextField();
        jButtonMasAnioPersonal = new javax.swing.JButton();
        jTextFieldEmailPersonal = new javax.swing.JTextField();
        jTextFieldFechaNacimientoAnioPersonal = new javax.swing.JTextField();
        jTextFieldContraseniaPersonal = new javax.swing.JTextField();
        jButtonMasMesPersonal = new javax.swing.JButton();
        jLabelFechaNacimientoPersonal = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonFotoPersonal = new javax.swing.JButton();
        jLabelInfoFotoPersonal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButtonFarmaceutico = new javax.swing.JRadioButton();
        jRadioButtonAnalista = new javax.swing.JRadioButton();
        jRadioButtonRadiologo = new javax.swing.JRadioButton();
        jRadioButtonMedico = new javax.swing.JRadioButton();
        jPanelConsultarTurno = new javax.swing.JPanel();
        jButtonMenosDiaFechaInicioTurno = new javax.swing.JButton();
        jButtonMenosMesFechaInicioTurno = new javax.swing.JButton();
        jLabelDNITurno = new javax.swing.JLabel();
        jTextFieldDNIGestionarTurno = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaInfoConsultaTurno = new javax.swing.JTextArea();
        jButtonMenosAnioFechaInicioTurno = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaInfoTurno = new javax.swing.JTextArea();
        jTextFieldMesInicioTurno = new javax.swing.JTextField();
        jTextFieldAnioInicioTurno = new javax.swing.JTextField();
        jButtonMasAnioFechaInicioTurno = new javax.swing.JButton();
        jLabelGestionarPaciente6 = new javax.swing.JLabel();
        jTextFieldDiaInicioTurno = new javax.swing.JTextField();
        jLabelFechaInicioTurno = new javax.swing.JLabel();
        jButtonMasDiaFechaInicioTurno = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonMasMesFechaInicioTurno = new javax.swing.JButton();
        jButtonMenosDiaFechaFinTurno = new javax.swing.JButton();
        jButtonMenosMesFechaFinTurno = new javax.swing.JButton();
        jButtonMenosAnioFechaFinTurno = new javax.swing.JButton();
        jTextFieldMesFinTurno = new javax.swing.JTextField();
        jTextFieldAnioFinTurno = new javax.swing.JTextField();
        jButtonMasAnioFechaFinTurno = new javax.swing.JButton();
        jTextFieldDiaFinTurno = new javax.swing.JTextField();
        jLabelFechaFinTurno = new javax.swing.JLabel();
        jButtonMasDiaFechaFinTurno = new javax.swing.JButton();
        jButtonMasMesFechaFinTurno = new javax.swing.JButton();
        jLabelTurnoTrabajo = new javax.swing.JLabel();
        jRadioButtonManiana = new javax.swing.JRadioButton();
        jRadioButtonTarde1 = new javax.swing.JRadioButton();
        jRadioButtonNoche = new javax.swing.JRadioButton();
        jPanelUsuario = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelTipoUsuario = new javax.swing.JLabel();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jLabelTipoUsuarioIdentificado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 102));
        setMinimumSize(new java.awt.Dimension(931, 715));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelCentroMedico.setText("Centro médico");
        getContentPane().add(jLabelCentroMedico);
        jLabelCentroMedico.setBounds(177, 68, 104, 18);

        jLabelIconoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Inicio-Desactivado.png"))); // NOI18N
        jLabelIconoInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconoInicioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIconoInicioMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIconoInicioMouseEntered(evt);
            }
        });
        getContentPane().add(jLabelIconoInicio);
        jLabelIconoInicio.setBounds(420, 70, 44, 47);

        jLabelInicio.setText("Inicio");
        getContentPane().add(jLabelInicio);
        jLabelInicio.setBounds(420, 120, 44, 18);

        jLabelIconoAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Ayuda-Desactivado.png"))); // NOI18N
        jLabelIconoAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconoAyudaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIconoAyudaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIconoAyudaMouseEntered(evt);
            }
        });
        getContentPane().add(jLabelIconoAyuda);
        jLabelIconoAyuda.setBounds(500, 70, 44, 47);

        jLabelIconoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Salir-Desactivado.png"))); // NOI18N
        jLabelIconoSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconoSalirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIconoSalirMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIconoSalirMouseEntered(evt);
            }
        });
        getContentPane().add(jLabelIconoSalir);
        jLabelIconoSalir.setBounds(580, 70, 43, 47);

        jLabelAyuda.setText("Ayuda");
        getContentPane().add(jLabelAyuda);
        jLabelAyuda.setBounds(500, 120, 44, 18);

        jLabelSalir.setText("Salir");
        getContentPane().add(jLabelSalir);
        jLabelSalir.setBounds(590, 120, 29, 18);

        jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Intro/Logo-Centro-Medico.png"))); // NOI18N
        getContentPane().add(jLabelIcono);
        jLabelIcono.setBounds(20, 17, 140, 150);

        ZonaTrabajo.setMinimumSize(new java.awt.Dimension(902, 520));
        ZonaTrabajo.setPreferredSize(new java.awt.Dimension(912, 530));

        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(901, 531));

        jButtonConsultarDatosPersonales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Tipo.png"))); // NOI18N
        jButtonConsultarDatosPersonales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConsultarDatosPersonalesMouseClicked(evt);
            }
        });
        jButtonConsultarDatosPersonales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarDatosPersonalesActionPerformed(evt);
            }
        });

        jLabelGestionarPaciente3.setText("Consultar datos personales");

        jLabelConsultarTurno.setText("Consultar turno");

        jButtonGestionarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Cita.png"))); // NOI18N
        jButtonGestionarCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGestionarCitaMouseClicked(evt);
            }
        });
        jButtonGestionarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionarCitaActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelPrincipalLayout = new org.jdesktop.layout.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelPrincipalLayout.createSequentialGroup()
                .add(jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelPrincipalLayout.createSequentialGroup()
                        .add(47, 47, 47)
                        .add(jButtonConsultarDatosPersonales, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 194, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanelPrincipalLayout.createSequentialGroup()
                        .add(56, 56, 56)
                        .add(jLabelGestionarPaciente3)))
                .add(jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelPrincipalLayout.createSequentialGroup()
                        .add(73, 73, 73)
                        .add(jButtonGestionarCita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 194, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanelPrincipalLayout.createSequentialGroup()
                        .add(121, 121, 121)
                        .add(jLabelConsultarTurno)))
                .addContainerGap(405, Short.MAX_VALUE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelPrincipalLayout.createSequentialGroup()
                .add(29, 29, 29)
                .add(jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButtonGestionarCita, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButtonConsultarDatosPersonales, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelGestionarPaciente3)
                    .add(jLabelConsultarTurno))
                .add(450, 450, 450))
        );

        jPanelPrincipal.setBounds(-19, 0, 920, 531);
        ZonaTrabajo.add(jPanelPrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanelConsultarDatosPersonales.setPreferredSize(new java.awt.Dimension(901, 531));
        jPanelConsultarDatosPersonales.setLayout(null);

        jLabel3.setText("___________________________________________________________________");
        jPanelConsultarDatosPersonales.add(jLabel3);
        jLabel3.setBounds(256, 59, 469, 18);

        jLabelGestionarPaciente4.setFont(new java.awt.Font("Lucida Grande", 1, 48));
        jLabelGestionarPaciente4.setText("Gestionar Personal");
        jPanelConsultarDatosPersonales.add(jLabelGestionarPaciente4);
        jLabelGestionarPaciente4.setBounds(257, 20, 516, 57);

        jTextFieldNombrePersonal.setEditable(false);
        jTextFieldNombrePersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombrePersonalKeyTyped(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jTextFieldNombrePersonal);
        jTextFieldNombrePersonal.setBounds(157, 126, 210, 28);

        jLabelFotoPersonal.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFotoPersonal.setForeground(new java.awt.Color(255, 255, 255));
        jPanelConsultarDatosPersonales.add(jLabelFotoPersonal);
        jLabelFotoPersonal.setBounds(720, 330, 130, 150);

        jTextFieldTelefonoPersonal.setEditable(false);
        jTextFieldTelefonoPersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelefonoPersonalKeyTyped(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jTextFieldTelefonoPersonal);
        jTextFieldTelefonoPersonal.setBounds(157, 270, 130, 28);

        jLabelContraseniaPersonal.setText("Contraseña");
        jPanelConsultarDatosPersonales.add(jLabelContraseniaPersonal);
        jLabelContraseniaPersonal.setBounds(729, 250, 81, 18);

        jTextFieldDNIPersonal.setEditable(false);
        jTextFieldDNIPersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDNIPersonalKeyTyped(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jTextFieldDNIPersonal);
        jTextFieldDNIPersonal.setBounds(757, 126, 95, 28);

        jLabelNombrePersonal.setText("Nombre");
        jPanelConsultarDatosPersonales.add(jLabelNombrePersonal);
        jLabelNombrePersonal.setBounds(157, 96, 57, 18);

        jLabelFotografiaersonal.setText("Fotografía");
        jPanelConsultarDatosPersonales.add(jLabelFotografiaersonal);
        jLabelFotografiaersonal.setBounds(610, 330, 72, 18);

        jLabelDNIPersonal.setText("DNI");
        jPanelConsultarDatosPersonales.add(jLabelDNIPersonal);
        jLabelDNIPersonal.setBounds(757, 96, 25, 18);

        jTextFieldLugarNacimientoPersonal.setEditable(false);
        jTextFieldLugarNacimientoPersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLugarNacimientoPersonalKeyTyped(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jTextFieldLugarNacimientoPersonal);
        jTextFieldLugarNacimientoPersonal.setBounds(350, 270, 300, 28);

        jLabelTelefonoPersonal.setText("Teléfono");
        jPanelConsultarDatosPersonales.add(jLabelTelefonoPersonal);
        jLabelTelefonoPersonal.setBounds(157, 250, 64, 18);

        jTextFieldFechaNacimientoMesersonal.setEditable(false);
        jTextFieldFechaNacimientoMesersonal.setText("1");
        jTextFieldFechaNacimientoMesersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaNacimientoMesersonalActionPerformed(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jTextFieldFechaNacimientoMesersonal);
        jTextFieldFechaNacimientoMesersonal.setBounds(217, 377, 33, 28);

        jLabelLugarNacimientoPersonal.setText("Lugar nacimiento");
        jPanelConsultarDatosPersonales.add(jLabelLugarNacimientoPersonal);
        jLabelLugarNacimientoPersonal.setBounds(350, 250, 121, 18);

        jLabelDireccionPersonal.setText("Dirección");
        jPanelConsultarDatosPersonales.add(jLabelDireccionPersonal);
        jLabelDireccionPersonal.setBounds(157, 172, 66, 18);

        jButtonMenosAnioPersona.setText("-");
        jButtonMenosAnioPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosAnioPersonaMouseClicked(evt);
            }
        });
        jButtonMenosAnioPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosAnioPersonaActionPerformed(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jButtonMenosAnioPersona);
        jButtonMenosAnioPersona.setBounds(257, 407, 50, 40);

        jLabelApellidosPersonal.setText("Apellidos");
        jPanelConsultarDatosPersonales.add(jLabelApellidosPersonal);
        jLabelApellidosPersonal.setBounds(407, 96, 63, 18);

        jTextFieldApellidosPersonal.setEditable(false);
        jTextFieldApellidosPersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldApellidosPersonalKeyTyped(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jTextFieldApellidosPersonal);
        jTextFieldApellidosPersonal.setBounds(407, 126, 290, 28);

        jButtonMasDiaPersonal.setText("+");
        jButtonMasDiaPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasDiaPersonalMouseClicked(evt);
            }
        });
        jButtonMasDiaPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasDiaPersonalActionPerformed(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jButtonMasDiaPersonal);
        jButtonMasDiaPersonal.setBounds(157, 337, 50, 40);

        jButtonMenosMesPersonal.setText("-");
        jButtonMenosMesPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosMesPersonalMouseClicked(evt);
            }
        });
        jButtonMenosMesPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosMesPersonalActionPerformed(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jButtonMenosMesPersonal);
        jButtonMenosMesPersonal.setBounds(207, 407, 50, 40);

        jButtonMenosDiaPersonal.setText("-");
        jButtonMenosDiaPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosDiaPersonalMouseClicked(evt);
            }
        });
        jButtonMenosDiaPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosDiaPersonalActionPerformed(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jButtonMenosDiaPersonal);
        jButtonMenosDiaPersonal.setBounds(157, 407, 50, 40);

        jLabelEmailPersonal.setText("Email");
        jPanelConsultarDatosPersonales.add(jLabelEmailPersonal);
        jLabelEmailPersonal.setBounds(567, 172, 37, 18);

        jTextFieldDireccionPersonal.setEditable(false);
        jTextFieldDireccionPersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDireccionPersonalKeyTyped(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jTextFieldDireccionPersonal);
        jTextFieldDireccionPersonal.setBounds(157, 192, 370, 28);

        jTextFieldFechaNacimientoDiaPersonal.setEditable(false);
        jTextFieldFechaNacimientoDiaPersonal.setText("1");
        jPanelConsultarDatosPersonales.add(jTextFieldFechaNacimientoDiaPersonal);
        jTextFieldFechaNacimientoDiaPersonal.setBounds(167, 377, 33, 28);

        jButtonMasAnioPersonal.setText("+");
        jButtonMasAnioPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasAnioPersonalMouseClicked(evt);
            }
        });
        jButtonMasAnioPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasAnioPersonalActionPerformed(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jButtonMasAnioPersonal);
        jButtonMasAnioPersonal.setBounds(257, 337, 50, 40);

        jTextFieldEmailPersonal.setEditable(false);
        jTextFieldEmailPersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEmailPersonalKeyTyped(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jTextFieldEmailPersonal);
        jTextFieldEmailPersonal.setBounds(567, 192, 289, 28);

        jTextFieldFechaNacimientoAnioPersonal.setEditable(false);
        jTextFieldFechaNacimientoAnioPersonal.setText("1950");
        jPanelConsultarDatosPersonales.add(jTextFieldFechaNacimientoAnioPersonal);
        jTextFieldFechaNacimientoAnioPersonal.setBounds(257, 377, 50, 28);

        jTextFieldContraseniaPersonal.setColumns(8);
        jTextFieldContraseniaPersonal.setEditable(false);
        jPanelConsultarDatosPersonales.add(jTextFieldContraseniaPersonal);
        jTextFieldContraseniaPersonal.setBounds(729, 270, 114, 28);

        jButtonMasMesPersonal.setText("+");
        jButtonMasMesPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasMesPersonalMouseClicked(evt);
            }
        });
        jButtonMasMesPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasMesPersonalActionPerformed(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jButtonMasMesPersonal);
        jButtonMasMesPersonal.setBounds(207, 337, 50, 40);

        jLabelFechaNacimientoPersonal.setText("Fecha nacimiento");
        jPanelConsultarDatosPersonales.add(jLabelFechaNacimientoPersonal);
        jLabelFechaNacimientoPersonal.setBounds(157, 317, 123, 18);

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGuardarMouseClicked(evt);
            }
        });
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jButtonGuardar);
        jButtonGuardar.setBounds(430, 460, 68, 39);

        jButtonFotoPersonal.setText("Añadir foto");
        jButtonFotoPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFotoPersonalMouseClicked(evt);
            }
        });
        jButtonFotoPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFotoPersonalActionPerformed(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jButtonFotoPersonal);
        jButtonFotoPersonal.setBounds(590, 350, 90, 30);

        jLabelInfoFotoPersonal.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabelInfoFotoPersonal.setText("Tam max 130x150 pix");
        jPanelConsultarDatosPersonales.add(jLabelInfoFotoPersonal);
        jLabelInfoFotoPersonal.setBounds(600, 380, 108, 13);

        jLabel8.setText("Tipo personal");
        jPanelConsultarDatosPersonales.add(jLabel8);
        jLabel8.setBounds(440, 330, 95, 18);

        jRadioButtonFarmaceutico.setText("Farmacéutico");
        jRadioButtonFarmaceutico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFarmaceuticoActionPerformed(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jRadioButtonFarmaceutico);
        jRadioButtonFarmaceutico.setBounds(440, 370, 121, 24);

        jRadioButtonAnalista.setText("Analista");
        jPanelConsultarDatosPersonales.add(jRadioButtonAnalista);
        jRadioButtonAnalista.setBounds(440, 350, 80, 24);

        jRadioButtonRadiologo.setText("Radiólogo");
        jRadioButtonRadiologo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRadiologoActionPerformed(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jRadioButtonRadiologo);
        jRadioButtonRadiologo.setBounds(440, 410, 95, 24);

        jRadioButtonMedico.setText("Médico");
        jRadioButtonMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMedicoActionPerformed(evt);
            }
        });
        jPanelConsultarDatosPersonales.add(jRadioButtonMedico);
        jRadioButtonMedico.setBounds(440, 390, 77, 24);

        jPanelConsultarDatosPersonales.setBounds(1, -240, 900, 770);
        ZonaTrabajo.add(jPanelConsultarDatosPersonales, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanelConsultarTurno.setMinimumSize(new java.awt.Dimension(901, 510));
        jPanelConsultarTurno.setPreferredSize(new java.awt.Dimension(901, 531));

        jButtonMenosDiaFechaInicioTurno.setText("-");
        jButtonMenosDiaFechaInicioTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosDiaFechaInicioTurnoMouseClicked(evt);
            }
        });
        jButtonMenosDiaFechaInicioTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosDiaFechaInicioTurnoActionPerformed(evt);
            }
        });

        jButtonMenosMesFechaInicioTurno.setText("-");
        jButtonMenosMesFechaInicioTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosMesFechaInicioTurnoMouseClicked(evt);
            }
        });
        jButtonMenosMesFechaInicioTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosMesFechaInicioTurnoActionPerformed(evt);
            }
        });

        jLabelDNITurno.setText("DNI");

        jTextFieldDNIGestionarTurno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDNIGestionarTurnoKeyTyped(evt);
            }
        });

        jTextAreaInfoConsultaTurno.setBackground(new java.awt.Color(255, 204, 102));
        jTextAreaInfoConsultaTurno.setColumns(17);
        jTextAreaInfoConsultaTurno.setEditable(false);
        jTextAreaInfoConsultaTurno.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        jTextAreaInfoConsultaTurno.setRows(3);
        jTextAreaInfoConsultaTurno.setText("Introduce el DNI del personal, una fecha y las horas que trabaja el personal para guardar\nsu turno. Si introduces un DNI y pulsas consultar se sabe el turno del DNI.");
        jScrollPane4.setViewportView(jTextAreaInfoConsultaTurno);

        jButtonMenosAnioFechaInicioTurno.setText("-");
        jButtonMenosAnioFechaInicioTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosAnioFechaInicioTurnoMouseClicked(evt);
            }
        });
        jButtonMenosAnioFechaInicioTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosAnioFechaInicioTurnoActionPerformed(evt);
            }
        });

        jTextAreaInfoTurno.setBackground(new java.awt.Color(255, 204, 102));
        jTextAreaInfoTurno.setColumns(17);
        jTextAreaInfoTurno.setEditable(false);
        jTextAreaInfoTurno.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        jTextAreaInfoTurno.setRows(3);
        jTextAreaInfoTurno.setText("Modifica la fecha y la shorts en trabajar del trabajador con el DNI del formulario,\nluego dale a \"Guardar\" y se actualizará su turno de trabajo. \nSi deseas consultar el turno de otro DNI, introdúcuelo y dale a \"Consultar\"");
        jScrollPane5.setViewportView(jTextAreaInfoTurno);

        jTextFieldMesInicioTurno.setEditable(false);
        jTextFieldMesInicioTurno.setText("1");
        jTextFieldMesInicioTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMesInicioTurnoActionPerformed(evt);
            }
        });

        jTextFieldAnioInicioTurno.setEditable(false);
        jTextFieldAnioInicioTurno.setText("1950");
        jTextFieldAnioInicioTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnioInicioTurnoActionPerformed(evt);
            }
        });

        jButtonMasAnioFechaInicioTurno.setText("+");
        jButtonMasAnioFechaInicioTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasAnioFechaInicioTurnoMouseClicked(evt);
            }
        });
        jButtonMasAnioFechaInicioTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasAnioFechaInicioTurnoActionPerformed(evt);
            }
        });

        jLabelGestionarPaciente6.setFont(new java.awt.Font("Lucida Grande", 1, 48));
        jLabelGestionarPaciente6.setText("Consultar Turno");

        jTextFieldDiaInicioTurno.setEditable(false);
        jTextFieldDiaInicioTurno.setText("1");

        jLabelFechaInicioTurno.setText("Fecha inicio");

        jButtonMasDiaFechaInicioTurno.setText("+");
        jButtonMasDiaFechaInicioTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasDiaFechaInicioTurnoMouseClicked(evt);
            }
        });
        jButtonMasDiaFechaInicioTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasDiaFechaInicioTurnoActionPerformed(evt);
            }
        });

        jLabel9.setText("_____________________________________________________________________________");

        jButtonMasMesFechaInicioTurno.setText("+");
        jButtonMasMesFechaInicioTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasMesFechaInicioTurnoMouseClicked(evt);
            }
        });
        jButtonMasMesFechaInicioTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasMesFechaInicioTurnoActionPerformed(evt);
            }
        });

        jButtonMenosDiaFechaFinTurno.setText("-");
        jButtonMenosDiaFechaFinTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosDiaFechaFinTurnoMouseClicked(evt);
            }
        });
        jButtonMenosDiaFechaFinTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosDiaFechaFinTurnoActionPerformed(evt);
            }
        });

        jButtonMenosMesFechaFinTurno.setText("-");
        jButtonMenosMesFechaFinTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosMesFechaFinTurnoMouseClicked(evt);
            }
        });
        jButtonMenosMesFechaFinTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosMesFechaFinTurnoActionPerformed(evt);
            }
        });

        jButtonMenosAnioFechaFinTurno.setText("-");
        jButtonMenosAnioFechaFinTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenosAnioFechaFinTurnoMouseClicked(evt);
            }
        });
        jButtonMenosAnioFechaFinTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosAnioFechaFinTurnoActionPerformed(evt);
            }
        });

        jTextFieldMesFinTurno.setEditable(false);
        jTextFieldMesFinTurno.setText("1");
        jTextFieldMesFinTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMesFinTurnoActionPerformed(evt);
            }
        });

        jTextFieldAnioFinTurno.setEditable(false);
        jTextFieldAnioFinTurno.setText("1950");
        jTextFieldAnioFinTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnioFinTurnoActionPerformed(evt);
            }
        });

        jButtonMasAnioFechaFinTurno.setText("+");
        jButtonMasAnioFechaFinTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasAnioFechaFinTurnoMouseClicked(evt);
            }
        });
        jButtonMasAnioFechaFinTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasAnioFechaFinTurnoActionPerformed(evt);
            }
        });

        jTextFieldDiaFinTurno.setEditable(false);
        jTextFieldDiaFinTurno.setText("1");

        jLabelFechaFinTurno.setText("Fecha fin");

        jButtonMasDiaFechaFinTurno.setText("+");
        jButtonMasDiaFechaFinTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasDiaFechaFinTurnoMouseClicked(evt);
            }
        });
        jButtonMasDiaFechaFinTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasDiaFechaFinTurnoActionPerformed(evt);
            }
        });

        jButtonMasMesFechaFinTurno.setText("+");
        jButtonMasMesFechaFinTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMasMesFechaFinTurnoMouseClicked(evt);
            }
        });
        jButtonMasMesFechaFinTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasMesFechaFinTurnoActionPerformed(evt);
            }
        });

        jLabelTurnoTrabajo.setText("Turno de trabajo");

        jRadioButtonManiana.setText("Mañana (8h-16h)");

        jRadioButtonTarde1.setText("Tarde (16h-24h)");
        jRadioButtonTarde1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTarde1ActionPerformed(evt);
            }
        });

        jRadioButtonNoche.setText("Noche (24h-8h)");

        org.jdesktop.layout.GroupLayout jPanelConsultarTurnoLayout = new org.jdesktop.layout.GroupLayout(jPanelConsultarTurno);
        jPanelConsultarTurno.setLayout(jPanelConsultarTurnoLayout);
        jPanelConsultarTurnoLayout.setHorizontalGroup(
            jPanelConsultarTurnoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelConsultarTurnoLayout.createSequentialGroup()
                .add(250, 250, 250)
                .add(jLabelGestionarPaciente6)
                .addContainerGap(216, Short.MAX_VALUE))
            .add(jPanelConsultarTurnoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanelConsultarTurnoLayout.createSequentialGroup()
                    .add(0, 60, Short.MAX_VALUE)
                    .add(jPanelConsultarTurnoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanelConsultarTurnoLayout.createSequentialGroup()
                            .add(120, 120, 120)
                            .add(jLabel9))
                        .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 780, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 780, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jPanelConsultarTurnoLayout.createSequentialGroup()
                            .add(290, 290, 290)
                            .add(jLabelDNITurno)
                            .add(16, 16, 16)
                            .add(jTextFieldDNIGestionarTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanelConsultarTurnoLayout.createSequentialGroup()
                            .add(80, 80, 80)
                            .add(jLabelFechaInicioTurno)
                            .add(185, 185, 185)
                            .add(jLabelFechaFinTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 74, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(136, 136, 136)
                            .add(jLabelTurnoTrabajo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanelConsultarTurnoLayout.createSequentialGroup()
                            .add(40, 40, 40)
                            .add(jButtonMasDiaFechaInicioTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonMasMesFechaInicioTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonMasAnioFechaInicioTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(110, 110, 110)
                            .add(jButtonMasDiaFechaFinTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonMasMesFechaFinTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonMasAnioFechaFinTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(90, 90, 90)
                            .add(jRadioButtonManiana, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanelConsultarTurnoLayout.createSequentialGroup()
                            .add(50, 50, 50)
                            .add(jTextFieldDiaInicioTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(17, 17, 17)
                            .add(jTextFieldMesInicioTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(7, 7, 7)
                            .add(jTextFieldAnioInicioTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(120, 120, 120)
                            .add(jTextFieldDiaFinTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(17, 17, 17)
                            .add(jTextFieldMesFinTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(7, 7, 7)
                            .add(jTextFieldAnioFinTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(90, 90, 90)
                            .add(jRadioButtonTarde1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanelConsultarTurnoLayout.createSequentialGroup()
                            .add(40, 40, 40)
                            .add(jButtonMenosDiaFechaInicioTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonMenosMesFechaInicioTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonMenosAnioFechaInicioTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(110, 110, 110)
                            .add(jButtonMenosDiaFechaFinTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonMenosMesFechaFinTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonMenosAnioFechaFinTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(90, 90, 90)
                            .add(jRadioButtonNoche, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(0, 61, Short.MAX_VALUE)))
        );
        jPanelConsultarTurnoLayout.setVerticalGroup(
            jPanelConsultarTurnoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelConsultarTurnoLayout.createSequentialGroup()
                .add(65, 65, 65)
                .add(jLabelGestionarPaciente6)
                .addContainerGap(409, Short.MAX_VALUE))
            .add(jPanelConsultarTurnoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanelConsultarTurnoLayout.createSequentialGroup()
                    .add(50, 113, Short.MAX_VALUE)
                    .add(jLabel9)
                    .add(24, 24, 24)
                    .add(jPanelConsultarTurnoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(20, 20, 20)
                    .add(jPanelConsultarTurnoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanelConsultarTurnoLayout.createSequentialGroup()
                            .add(10, 10, 10)
                            .add(jLabelDNITurno))
                        .add(jTextFieldDNIGestionarTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(12, 12, 12)
                    .add(jPanelConsultarTurnoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jLabelFechaInicioTurno)
                        .add(jLabelFechaFinTurno)
                        .add(jLabelTurnoTrabajo))
                    .add(4, 4, 4)
                    .add(jPanelConsultarTurnoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jButtonMasDiaFechaInicioTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButtonMasMesFechaInicioTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButtonMasAnioFechaInicioTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButtonMasDiaFechaFinTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButtonMasMesFechaFinTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButtonMasAnioFechaFinTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jPanelConsultarTurnoLayout.createSequentialGroup()
                            .add(10, 10, 10)
                            .add(jRadioButtonManiana)))
                    .add(jPanelConsultarTurnoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jTextFieldDiaInicioTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jTextFieldMesInicioTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jTextFieldAnioInicioTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jTextFieldDiaFinTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jTextFieldMesFinTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jTextFieldAnioFinTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jRadioButtonTarde1))
                    .add(2, 2, 2)
                    .add(jPanelConsultarTurnoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jButtonMenosDiaFechaInicioTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButtonMenosMesFechaInicioTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButtonMenosAnioFechaInicioTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButtonMenosDiaFechaFinTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButtonMenosMesFechaFinTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButtonMenosAnioFechaFinTurno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jRadioButtonNoche))
                    .add(0, 64, Short.MAX_VALUE)))
        );

        jPanelConsultarTurno.setBounds(0, 0, 901, 531);
        ZonaTrabajo.add(jPanelConsultarTurno, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(ZonaTrabajo);
        ZonaTrabajo.setBounds(13, 185, 920, 550);

        jPanelUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelUsuario.setLayout(null);

        jLabelUsuario.setText("Usuario:");
        jPanelUsuario.add(jLabelUsuario);
        jLabelUsuario.setBounds(90, 0, 56, 18);

        jLabelTipoUsuario.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabelTipoUsuario.setText("Tipo Usuario");
        jPanelUsuario.add(jLabelTipoUsuario);
        jLabelTipoUsuario.setBounds(90, 30, 120, 17);

        jLabelNombreUsuario.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabelNombreUsuario.setText("Nombre");
        jPanelUsuario.add(jLabelNombreUsuario);
        jLabelNombreUsuario.setBounds(90, 60, 120, 17);
        jPanelUsuario.add(jLabelTipoUsuarioIdentificado);
        jLabelTipoUsuarioIdentificado.setBounds(10, 10, 70, 70);

        getContentPane().add(jPanelUsuario);
        jPanelUsuario.setBounds(665, 47, 220, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jLabelIconoInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoInicioMouseEntered
        // TODO add your handling code here:
        jLabelIconoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Inicio-Activado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoInicioMouseEntered

    private void jLabelIconoInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoInicioMouseExited
        // TODO add your handling code here:
        jLabelIconoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Inicio-Desactivado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoInicioMouseExited

    private void jLabelIconoAyudaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoAyudaMouseExited
        // TODO add your handling code here:
        jLabelIconoAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Ayuda-Desactivado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoAyudaMouseExited

    private void jLabelIconoAyudaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoAyudaMouseEntered
        // TODO add your handling code here:
        jLabelIconoAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Ayuda-Activado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoAyudaMouseEntered

    private void jLabelIconoSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoSalirMouseExited
        // TODO add your handling code here:
        jLabelIconoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Salir-Desactivado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoSalirMouseExited

    private void jLabelIconoSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoSalirMouseEntered
        // TODO add your handling code here:
        jLabelIconoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Salir-Activado.png"))); // NOI18N
    }//GEN-LAST:event_jLabelIconoSalirMouseEntered

    private void jLabelIconoSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelIconoSalirMouseClicked

    private void jLabelIconoAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoAyudaMouseClicked
        // TODO add your handling code here:
        new Ayuda().setVisible(true);
    }//GEN-LAST:event_jLabelIconoAyudaMouseClicked

    private void jButtonConsultarDatosPersonalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConsultarDatosPersonalesMouseClicked
        // TODO add your handling code here:
        mostrarPanel("GestionarPersonal");
    }//GEN-LAST:event_jButtonConsultarDatosPersonalesMouseClicked

    private void jButtonConsultarDatosPersonalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarDatosPersonalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsultarDatosPersonalesActionPerformed

    private void jLabelIconoInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoInicioMouseClicked
        // TODO add your handling code here:
        mostrarPanel("Principal");
    }//GEN-LAST:event_jLabelIconoInicioMouseClicked

    private void jTextFieldFechaNacimientoMesersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaNacimientoMesersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaNacimientoMesersonalActionPerformed

    private void jButtonMenosAnioPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosAnioPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenosAnioPersonaActionPerformed

    private void jButtonMasDiaPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasDiaPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMasDiaPersonalActionPerformed

    private void jButtonMenosMesPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosMesPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenosMesPersonalActionPerformed

    private void jButtonMenosDiaPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosDiaPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenosDiaPersonalActionPerformed

    private void jButtonMasAnioPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasAnioPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMasAnioPersonalActionPerformed

    private void jButtonMasMesPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasMesPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMasMesPersonalActionPerformed

    private void jButtonMasDiaPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasDiaPersonalMouseClicked
        // TODO add your handling code here:
        int num = 0;
        
        num = Integer.parseInt(jTextFieldFechaNacimientoDiaPersonal.getText());

        if(num < 31)
            num ++;
        
        String numString;
        numString = String.valueOf(num);
        jTextFieldFechaNacimientoDiaPersonal.setText(numString);
    }//GEN-LAST:event_jButtonMasDiaPersonalMouseClicked

    private void jButtonMenosDiaPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosDiaPersonalMouseClicked
        // TODO add your handling code here:
        int num = 0;

        num = Integer.parseInt(jTextFieldFechaNacimientoDiaPersonal.getText());

        if(num > 1)
            num --;

        String numString;
        numString = String.valueOf(num);
        jTextFieldFechaNacimientoDiaPersonal.setText(numString);
    }//GEN-LAST:event_jButtonMenosDiaPersonalMouseClicked

    private void jButtonMasMesPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasMesPersonalMouseClicked
        // TODO add your handling code here:
        int num = 0;

        num = Integer.parseInt(jTextFieldFechaNacimientoMesersonal.getText());

        if(num < 12)
            num ++;

        String numString;
        numString = String.valueOf(num);
        jTextFieldFechaNacimientoMesersonal.setText(numString);
    }//GEN-LAST:event_jButtonMasMesPersonalMouseClicked

    private void jButtonMenosMesPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosMesPersonalMouseClicked
        // TODO add your handling code here:
        int num = 0;

        num = Integer.parseInt(jTextFieldFechaNacimientoMesersonal.getText());

        if(num > 1)
            num --;

        String numString;
        numString = String.valueOf(num);
        jTextFieldFechaNacimientoMesersonal.setText(numString);
    }//GEN-LAST:event_jButtonMenosMesPersonalMouseClicked

    private void jButtonMasAnioPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasAnioPersonalMouseClicked
        // TODO add your handling code here:
        int num = 0;
        int anioActual = 0;

        num = Integer.parseInt(jTextFieldFechaNacimientoAnioPersonal.getText());

        Calendar fechaActual = Calendar.getInstance();
        anioActual = fechaActual.get(Calendar.YEAR);

        if(num < anioActual)
            num ++;

        String numString;
        numString = String.valueOf(num);
        jTextFieldFechaNacimientoAnioPersonal.setText(numString);
    }//GEN-LAST:event_jButtonMasAnioPersonalMouseClicked

    private void jButtonMenosAnioPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosAnioPersonaMouseClicked
        // TODO add your handling code here:
        int num = 0;

        num = Integer.parseInt(jTextFieldFechaNacimientoAnioPersonal.getText());

        if(num > 1900)
            num --;

        String numString;
        numString = String.valueOf(num);
        jTextFieldFechaNacimientoAnioPersonal.setText(numString);
    }//GEN-LAST:event_jButtonMenosAnioPersonaMouseClicked

    private void jButtonGestionarCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGestionarCitaMouseClicked
        // TODO add your handling code here:
        mostrarPanel("GestionarTurno");
    }//GEN-LAST:event_jButtonGestionarCitaMouseClicked

    private void jTextFieldTelefonoPersonalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoPersonalKeyTyped
        // TODO add your handling code here:

        /**Comprobamos que no se teclee una letra*/
        char teclaPresionada = evt.getKeyChar();
        if(Character.isDigit(teclaPresionada) == false)
            evt.consume();
    }//GEN-LAST:event_jTextFieldTelefonoPersonalKeyTyped

    private void jTextFieldNombrePersonalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombrePersonalKeyTyped
        // TODO add your handling code here:

        /**Comprobamos que no se teclee un número*/
        char teclaPresionada = evt.getKeyChar();
        if(Character.isDigit(teclaPresionada) == true)
            evt.consume();
}//GEN-LAST:event_jTextFieldNombrePersonalKeyTyped

    private void jTextFieldDNIPersonalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDNIPersonalKeyTyped
        // TODO add your handling code here:

        /**Limitamos a que el DNI siempre sea correcto sintácticamente*/
        char teclaPresionada = evt.getKeyChar();

        if(jTextFieldDNIPersonal.getText().length() < 8)
            if(Character.isDigit(teclaPresionada) == false)
                evt.consume();

        if(jTextFieldDNIPersonal.getText().length() == 8)
            if(Character.isDigit(teclaPresionada) == true){
                evt.consume();
            }else if(Character.isLowerCase(teclaPresionada)){
                jTextFieldDNIPersonal.setText(jTextFieldDNIPersonal.getText().toUpperCase());
            }

        if(jTextFieldDNIPersonal.getText().length() > 8)
            evt.consume();
}//GEN-LAST:event_jTextFieldDNIPersonalKeyTyped

    private void jTextFieldApellidosPersonalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidosPersonalKeyTyped
        // TODO add your handling code here:

        /**Comprobamos que no se teclee un número*/
        char teclaPresionada = evt.getKeyChar();
        if(Character.isDigit(teclaPresionada) == true)
            evt.consume();
}//GEN-LAST:event_jTextFieldApellidosPersonalKeyTyped

    private void jTextFieldDireccionPersonalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDireccionPersonalKeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldDireccionPersonalKeyTyped

    private void jTextFieldEmailPersonalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailPersonalKeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldEmailPersonalKeyTyped

    private void jTextFieldLugarNacimientoPersonalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLugarNacimientoPersonalKeyTyped
        // TODO add your handling code here:

        /**Comprobamos que no se teclee un número*/
        char teclaPresionada = evt.getKeyChar();
        if(Character.isDigit(teclaPresionada) == true)
            evt.consume();
}//GEN-LAST:event_jTextFieldLugarNacimientoPersonalKeyTyped

    private void jButtonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGuardarMouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonGuardarMouseClicked

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonFotoPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFotoPersonalMouseClicked
        // TODO add your handling code here:
        cargarFoto("GestionarPersonal");
}//GEN-LAST:event_jButtonFotoPersonalMouseClicked

    private void jButtonFotoPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFotoPersonalActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonFotoPersonalActionPerformed

    private void jRadioButtonFarmaceuticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFarmaceuticoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jRadioButtonFarmaceuticoActionPerformed

    private void jRadioButtonRadiologoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRadiologoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jRadioButtonRadiologoActionPerformed

    private void jRadioButtonMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMedicoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jRadioButtonMedicoActionPerformed

    private void jButtonMenosDiaFechaInicioTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosDiaFechaInicioTurnoMouseClicked
        // TODO add your handling code here:

        int num = 0;

        num = Integer.parseInt(jTextFieldDiaInicioTurno.getText());

        if(num > 1)
            num --;

        String numString;
        numString = String.valueOf(num);
        jTextFieldDiaInicioTurno.setText(numString);
}//GEN-LAST:event_jButtonMenosDiaFechaInicioTurnoMouseClicked

    private void jButtonMenosDiaFechaInicioTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosDiaFechaInicioTurnoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonMenosDiaFechaInicioTurnoActionPerformed

    private void jButtonMenosMesFechaInicioTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosMesFechaInicioTurnoMouseClicked
        // TODO add your handling code here:

        int num = 0;

        num = Integer.parseInt(jTextFieldMesInicioTurno.getText());

        if(num > 1)
            num --;

        String numString;
        numString = String.valueOf(num);
        jTextFieldMesInicioTurno.setText(numString);
}//GEN-LAST:event_jButtonMenosMesFechaInicioTurnoMouseClicked

    private void jButtonMenosMesFechaInicioTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosMesFechaInicioTurnoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonMenosMesFechaInicioTurnoActionPerformed

    private void jTextFieldDNIGestionarTurnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDNIGestionarTurnoKeyTyped
        // TODO add your handling code here:

        /**Limitamos a que el DNI siempre sea correcto sintácticamente*/
        char teclaPresionada = evt.getKeyChar();

        if(jTextFieldDNIGestionarTurno.getText().length() < 8)
            if(Character.isDigit(teclaPresionada) == false)
                evt.consume();

        if(jTextFieldDNIGestionarTurno.getText().length() == 8)
            if(Character.isDigit(teclaPresionada) == true){
                evt.consume();
            }else if(Character.isLowerCase(teclaPresionada)){
                jTextFieldDNIGestionarTurno.setText(jTextFieldDNIGestionarTurno.getText().toUpperCase());
            }

        if(jTextFieldDNIGestionarTurno.getText().length() > 8)
            evt.consume();
}//GEN-LAST:event_jTextFieldDNIGestionarTurnoKeyTyped

    private void jButtonMenosAnioFechaInicioTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosAnioFechaInicioTurnoMouseClicked
        // TODO add your handling code here:

        int num = 0;
        num = Integer.parseInt(jTextFieldAnioInicioTurno.getText());

        if(num > 1900)
            num --;

        String numString;
        numString = String.valueOf(num);
        jTextFieldAnioInicioTurno.setText(numString);
}//GEN-LAST:event_jButtonMenosAnioFechaInicioTurnoMouseClicked

    private void jButtonMenosAnioFechaInicioTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosAnioFechaInicioTurnoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonMenosAnioFechaInicioTurnoActionPerformed

    private void jTextFieldMesInicioTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMesInicioTurnoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldMesInicioTurnoActionPerformed

    private void jTextFieldAnioInicioTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnioInicioTurnoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldAnioInicioTurnoActionPerformed

    private void jButtonMasAnioFechaInicioTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasAnioFechaInicioTurnoMouseClicked
        // TODO add your handling code here:

        int num = 0;
        int anioActual = 0;

        num = Integer.parseInt(jTextFieldAnioInicioTurno.getText());

        Calendar fechaActual = Calendar.getInstance();
        anioActual = fechaActual.get(Calendar.YEAR);

        if(num < anioActual)
            num ++;

        String numString;
        numString = String.valueOf(num);
        jTextFieldAnioInicioTurno.setText(numString);
}//GEN-LAST:event_jButtonMasAnioFechaInicioTurnoMouseClicked

    private void jButtonMasAnioFechaInicioTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasAnioFechaInicioTurnoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonMasAnioFechaInicioTurnoActionPerformed

    private void jButtonMasDiaFechaInicioTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasDiaFechaInicioTurnoMouseClicked
        // TODO add your handling code here:

        int num = 0;

        num = Integer.parseInt(jTextFieldDiaInicioTurno.getText());

        if(num < 31)
            num ++;

        String numString;
        numString = String.valueOf(num);
        jTextFieldDiaInicioTurno.setText(numString);
}//GEN-LAST:event_jButtonMasDiaFechaInicioTurnoMouseClicked

    private void jButtonMasDiaFechaInicioTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasDiaFechaInicioTurnoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonMasDiaFechaInicioTurnoActionPerformed

    private void jButtonMasMesFechaInicioTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasMesFechaInicioTurnoMouseClicked
        // TODO add your handling code here:

        int num = 0;

        num = Integer.parseInt(jTextFieldMesInicioTurno.getText());

        if(num < 12)
            num ++;

        String numString;
        numString = String.valueOf(num);
        jTextFieldMesInicioTurno.setText(numString);
}//GEN-LAST:event_jButtonMasMesFechaInicioTurnoMouseClicked

    private void jButtonMasMesFechaInicioTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasMesFechaInicioTurnoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonMasMesFechaInicioTurnoActionPerformed

    private void jButtonMenosDiaFechaFinTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosDiaFechaFinTurnoMouseClicked
        // TODO add your handling code here:

        int num = 0;

        num = Integer.parseInt(jTextFieldDiaFinTurno.getText());

        if(num > 1)
            num --;

        String numString;
        numString = String.valueOf(num);
        jTextFieldDiaFinTurno.setText(numString);
}//GEN-LAST:event_jButtonMenosDiaFechaFinTurnoMouseClicked

    private void jButtonMenosDiaFechaFinTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosDiaFechaFinTurnoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonMenosDiaFechaFinTurnoActionPerformed

    private void jButtonMenosMesFechaFinTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosMesFechaFinTurnoMouseClicked
        // TODO add your handling code here:

        int num = 0;

        num = Integer.parseInt(jTextFieldMesFinTurno.getText());

        if(num > 1)
            num --;

        String numString;
        numString = String.valueOf(num);
        jTextFieldMesFinTurno.setText(numString);
}//GEN-LAST:event_jButtonMenosMesFechaFinTurnoMouseClicked

    private void jButtonMenosMesFechaFinTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosMesFechaFinTurnoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonMenosMesFechaFinTurnoActionPerformed

    private void jButtonMenosAnioFechaFinTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenosAnioFechaFinTurnoMouseClicked
        // TODO add your handling code here:

        int num = 0;
        int anioActual = 0;

        num = Integer.parseInt(jTextFieldAnioFinTurno.getText());

        Calendar fechaActual = Calendar.getInstance();
        anioActual = fechaActual.get(Calendar.YEAR);

        if(num > 1900)
            num --;

        String numString;
        numString = String.valueOf(num);
        jTextFieldAnioFinTurno.setText(numString);
}//GEN-LAST:event_jButtonMenosAnioFechaFinTurnoMouseClicked

    private void jButtonMenosAnioFechaFinTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosAnioFechaFinTurnoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonMenosAnioFechaFinTurnoActionPerformed

    private void jTextFieldMesFinTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMesFinTurnoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldMesFinTurnoActionPerformed

    private void jTextFieldAnioFinTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnioFinTurnoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldAnioFinTurnoActionPerformed

    private void jButtonMasAnioFechaFinTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasAnioFechaFinTurnoMouseClicked
        // TODO add your handling code here:
        
        int num = 0;
        int anioActual = 0;

        num = Integer.parseInt(jTextFieldAnioFinTurno.getText());

        Calendar fechaActual = Calendar.getInstance();
        anioActual = fechaActual.get(Calendar.YEAR);

        if(num < anioActual)
            num ++;

        String numString;
        numString = String.valueOf(num);
        jTextFieldAnioFinTurno.setText(numString);

}//GEN-LAST:event_jButtonMasAnioFechaFinTurnoMouseClicked

    private void jButtonMasAnioFechaFinTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasAnioFechaFinTurnoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonMasAnioFechaFinTurnoActionPerformed

    private void jButtonMasDiaFechaFinTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasDiaFechaFinTurnoMouseClicked
        // TODO add your handling code here:

        int num = 0;

        num = Integer.parseInt(jTextFieldDiaFinTurno.getText());

        if(num < 31)
            num ++;

        String numString;
        numString = String.valueOf(num);
        jTextFieldDiaFinTurno.setText(numString);
}//GEN-LAST:event_jButtonMasDiaFechaFinTurnoMouseClicked

    private void jButtonMasDiaFechaFinTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasDiaFechaFinTurnoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonMasDiaFechaFinTurnoActionPerformed

    private void jButtonMasMesFechaFinTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMasMesFechaFinTurnoMouseClicked
        // TODO add your handling code here:

        int num = 0;

        num = Integer.parseInt(jTextFieldMesFinTurno.getText());

        if(num < 12)
            num ++;

        String numString;
        numString = String.valueOf(num);
        jTextFieldMesFinTurno.setText(numString);
}//GEN-LAST:event_jButtonMasMesFechaFinTurnoMouseClicked

    private void jButtonMasMesFechaFinTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasMesFechaFinTurnoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonMasMesFechaFinTurnoActionPerformed

    private void jRadioButtonTarde1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTarde1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jRadioButtonTarde1ActionPerformed

    private void jButtonGestionarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionarCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGestionarCitaActionPerformed


    /*Comprueba que la fecha introducida es correcta
     * 
     *@param persona, string que indica si se trata del formulario de Paciente o Personal
     *@return booleano diciendo si es válido o no
     */
    private boolean compruebaFecha(String persona){
        
        int dia = 0;
        int mes = 0;
        int anio = 0;
        int diaActual;
        int mesActual;
        int anioActual;

        if(persona.equals("GestionarPaciente")){
            dia = Integer.parseInt(jTextFieldFechaNacimientoDiaPersonal.getText());
            mes = Integer.parseInt(jTextFieldFechaNacimientoMesersonal.getText());
            anio = Integer.parseInt(jTextFieldFechaNacimientoAnioPersonal.getText());
        }


        Calendar fechaActual = Calendar.getInstance();
        diaActual = fechaActual.get(Calendar.DATE);
        mesActual = fechaActual.get(Calendar.MONTH);
        anioActual = fechaActual.get(Calendar.YEAR);


        /**Si se sale de los rangos*/
        if((dia <= 0)
                || (dia > 31)
                || (mes <= 0)
                || (mes > 12)
                || (anio < 1900)
                || (anio > anioActual) ){
            return false;
        }

        /**Si ha nacido en el año actual, hay que ver que el mes no sea mayor que el actual*/
        /**Si ha nacido en el año y mes actual, hay que comprobar que el dia sea menor que el actual*/
        if(anio == anioActual){
            if(mes > mesActual){
                return false;
            } else{
                if(dia > diaActual){
                    return false;
                }
            }
        }

        /**Si estamos en un mes que tiene 30 días o 29 en el caso de febrero, hay que comprobar que no se pase*/
        if(mes%2 == 0){
            if((mes == 2) && (dia >29)){
                return false;
            }else{
                if(dia > 30){
                    return false;
                }
            }
        }

        return true;

    }


     /*Borra el formulario elegido
     *
     *@param persona, string que indica si se trata del formulario de Paciente o Personal
     */
    private void limpiarFormulario(String persona){

        String diaActual;
        String mesActual;
        String anioActual;
        String horaActual;
        String minutoActual;

        Calendar fechaActual = Calendar.getInstance();
        diaActual = Integer.toString(fechaActual.get(Calendar.DATE));
        mesActual = Integer.toString(fechaActual.get(Calendar.MONTH));
        anioActual = Integer.toString(fechaActual.get(Calendar.YEAR));
        horaActual = Integer.toString(fechaActual.get(Calendar.HOUR_OF_DAY));
        minutoActual = Integer.toString(fechaActual.get(Calendar.MINUTE));


        if(persona.equals("GestionarPaciente")){
            jTextFieldNombrePersonal.setText("");
            jTextFieldApellidosPersonal.setText("");
            jTextFieldDNIPersonal.setText("");
            jTextFieldDireccionPersonal.setText("");
            jTextFieldEmailPersonal.setText("");
            jTextFieldTelefonoPersonal.setText("");
            jTextFieldContraseniaPersonal.setText("");
            jTextFieldLugarNacimientoPersonal.setText("");

            jLabelFotoPersonal.setIcon(null);
        }

        if(persona.equals("GestionarTurno")){
            jTextFieldDiaInicioTurno.setText(diaActual);
            jTextFieldMesInicioTurno.setText(mesActual);
            jTextFieldAnioInicioTurno.setText(anioActual);
            jTextFieldDiaFinTurno.setText(diaActual);
            jTextFieldMesFinTurno.setText(mesActual);
            jTextFieldAnioFinTurno.setText(anioActual);
        }
    }

  
    /*Muestra el panel elegido en ZonaTrabajo
     *
     *@param panel, string que indica el panel a mostrar
     */
    private void mostrarPanel(String panel){

        if(panel.equals("Principal")){

            /**Hacemos visible el botón jLabelIconoInicio*/
            jLabelInicio.setVisible(false);
            jLabelIconoInicio.setVisible(false);

            /**Hacemos visible el panel seleccionado*/
            jPanelPrincipal.setVisible(true);
            jPanelConsultarDatosPersonales.setVisible(false);
            jPanelConsultarTurno.setVisible(false);


            /**Activamos el marco*/
            jPanelPrincipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
            jPanelConsultarDatosPersonales.setBorder(null);
            jPanelConsultarTurno.setBorder(null);
        }

        if(panel.equals("GestionarPersonal")){

            /**Hacemos visible el botón jLabelIconoInicio*/
            jLabelInicio.setVisible(true);
            jLabelIconoInicio.setVisible(true);

            /**Insertamos icono de foto anónima*/
            jLabelFotoPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal/Foto-Anonima.png"))); // NOI18N


            /**Hacemos visible el panel seleccionado*/
            jPanelPrincipal.setVisible(false);
            jPanelConsultarDatosPersonales.setVisible(true);
            jPanelConsultarTurno.setVisible(false);


            /**Activamos el marco*/
            jPanelPrincipal.setBorder(null);
            jPanelConsultarDatosPersonales.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
            jPanelConsultarTurno.setBorder(null);
        }


        if(panel.equals("GestionarTurno")){

            /**Limpiamos posibles datos introducidos anteriormente*/
            limpiarFormulario("GestionarTurno");

            /**Hacemos visible el botón jLabelIconoInicio*/
            jLabelInicio.setVisible(true);
            jLabelIconoInicio.setVisible(true);

            /**Hacemos visible el panel seleccionado*/
            jPanelPrincipal.setVisible(false);
            jPanelConsultarDatosPersonales.setVisible(false);
            jPanelConsultarTurno.setVisible(true);


            /**Activamos el marco*/
            jPanelPrincipal.setBorder(null);
            jPanelConsultarDatosPersonales.setBorder(null);
            jPanelConsultarTurno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        }



    }


     /*Carga la foto en el formulario pasado por parámetro
     *
     *@param formulario, string que indica el formulario donde cargar la foto
     */
    private void cargarFoto(String formulario){

        if(formulario.equals("GestionarPersonal")){
            JFileChooser dlg = new JFileChooser();
            int resp = dlg.showOpenDialog(this);
            if (resp == JFileChooser.APPROVE_OPTION){
                try{
                    ImageIcon icono = new ImageIcon(dlg.getSelectedFile().getCanonicalPath());
                    Image imagen = icono.getImage();
                    ImageIcon aescala = new ImageIcon(imagen.getScaledInstance(130,150,Image.SCALE_SMOOTH));
                    jLabelFotoPersonal.setIcon(aescala); // NOI18N
                }
                catch(Exception ex){
                    System.err.print("Error al leer el archivo");
                }
            }
        }

    }

    private void identificarPersonal( String nombreUsuario) throws SQLException{

        //trabajar con personal no se puede, ya que su BD está mal

        Usuario perso=null;
        usuarioBD usu_bd=new usuarioBD ();
        perso=usu_bd.obtenerUsuario(nombreUsuario);

        mostrarDatosPerso(perso);

    }

    private void mostrarDatosPerso(Usuario usu) throws SQLException{

        Calendar calendar = Calendar.getInstance();
        calendar.setTime(usu.getFechaNacimiento());
        int dia = calendar.get(Calendar.DAY_OF_MONTH);   //dia del mes
        int mes = calendar.get(Calendar.MONTH);
        mes=mes+1;//mes, de 0 a 11
        int anio = calendar.get(Calendar.YEAR);  //año

        String num_dia= String.valueOf(dia);
        String num_mes= String.valueOf(mes);
        String num_anio= String.valueOf(anio);


        jTextFieldFechaNacimientoAnioPersonal.setText(num_anio);
        jTextFieldFechaNacimientoDiaPersonal.setText(num_dia);
        jTextFieldFechaNacimientoMesersonal.setText(num_mes);
        jTextFieldNombrePersonal.setText(usu.getNombre());
        jTextFieldContraseniaPersonal.setText(usu.getContrasena());
        jTextFieldDNIPersonal.setText(usu.getDni());
        jTextFieldApellidosPersonal.setText(usu.getApellidos());
        jTextFieldTelefonoPersonal.setText(usu.getTelefono());
        jTextFieldDireccionPersonal.setText(usu.getDireccion());
        jTextFieldEmailPersonal.setText(usu.getEmail());
        jTextFieldLugarNacimientoPersonal.setText(usu.getLugarNacimiento());
    }
    
    // @param args the command line arguments
    
/*    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Paciente("Paciente", "paciente").setVisible(true);
            }
        });
    }
*/
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane ZonaTrabajo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonConsultarDatosPersonales;
    private javax.swing.JButton jButtonFotoPersonal;
    private javax.swing.JButton jButtonGestionarCita;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonMasAnioFechaFinTurno;
    private javax.swing.JButton jButtonMasAnioFechaInicioTurno;
    private javax.swing.JButton jButtonMasAnioPersonal;
    private javax.swing.JButton jButtonMasDiaFechaFinTurno;
    private javax.swing.JButton jButtonMasDiaFechaInicioTurno;
    private javax.swing.JButton jButtonMasDiaPersonal;
    private javax.swing.JButton jButtonMasMesFechaFinTurno;
    private javax.swing.JButton jButtonMasMesFechaInicioTurno;
    private javax.swing.JButton jButtonMasMesPersonal;
    private javax.swing.JButton jButtonMenosAnioFechaFinTurno;
    private javax.swing.JButton jButtonMenosAnioFechaInicioTurno;
    private javax.swing.JButton jButtonMenosAnioPersona;
    private javax.swing.JButton jButtonMenosDiaFechaFinTurno;
    private javax.swing.JButton jButtonMenosDiaFechaInicioTurno;
    private javax.swing.JButton jButtonMenosDiaPersonal;
    private javax.swing.JButton jButtonMenosMesFechaFinTurno;
    private javax.swing.JButton jButtonMenosMesFechaInicioTurno;
    private javax.swing.JButton jButtonMenosMesPersonal;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelApellidosPersonal;
    private javax.swing.JLabel jLabelAyuda;
    private javax.swing.JLabel jLabelCentroMedico;
    private javax.swing.JLabel jLabelConsultarTurno;
    private javax.swing.JLabel jLabelContraseniaPersonal;
    private javax.swing.JLabel jLabelDNIPersonal;
    private javax.swing.JLabel jLabelDNITurno;
    private javax.swing.JLabel jLabelDireccionPersonal;
    private javax.swing.JLabel jLabelEmailPersonal;
    private javax.swing.JLabel jLabelFechaFinTurno;
    private javax.swing.JLabel jLabelFechaInicioTurno;
    private javax.swing.JLabel jLabelFechaNacimientoPersonal;
    private javax.swing.JLabel jLabelFotoPersonal;
    private javax.swing.JLabel jLabelFotografiaersonal;
    private javax.swing.JLabel jLabelGestionarPaciente3;
    private javax.swing.JLabel jLabelGestionarPaciente4;
    private javax.swing.JLabel jLabelGestionarPaciente6;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JLabel jLabelIconoAyuda;
    private javax.swing.JLabel jLabelIconoInicio;
    private javax.swing.JLabel jLabelIconoSalir;
    private javax.swing.JLabel jLabelInfoFotoPersonal;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelLugarNacimientoPersonal;
    private javax.swing.JLabel jLabelNombrePersonal;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JLabel jLabelSalir;
    private javax.swing.JLabel jLabelTelefonoPersonal;
    private javax.swing.JLabel jLabelTipoUsuario;
    private javax.swing.JLabel jLabelTipoUsuarioIdentificado;
    private javax.swing.JLabel jLabelTurnoTrabajo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanelConsultarDatosPersonales;
    private javax.swing.JPanel jPanelConsultarTurno;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelUsuario;
    private javax.swing.JRadioButton jRadioButtonAnalista;
    private javax.swing.JRadioButton jRadioButtonFarmaceutico;
    private javax.swing.JRadioButton jRadioButtonManiana;
    private javax.swing.JRadioButton jRadioButtonMedico;
    private javax.swing.JRadioButton jRadioButtonNoche;
    private javax.swing.JRadioButton jRadioButtonRadiologo;
    private javax.swing.JRadioButton jRadioButtonTarde1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextAreaInfoConsultaTurno;
    private javax.swing.JTextArea jTextAreaInfoTurno;
    private javax.swing.JTextField jTextFieldAnioFinTurno;
    private javax.swing.JTextField jTextFieldAnioInicioTurno;
    private javax.swing.JTextField jTextFieldApellidosPersonal;
    private javax.swing.JTextField jTextFieldContraseniaPersonal;
    private javax.swing.JTextField jTextFieldDNIGestionarTurno;
    private javax.swing.JTextField jTextFieldDNIPersonal;
    private javax.swing.JTextField jTextFieldDiaFinTurno;
    private javax.swing.JTextField jTextFieldDiaInicioTurno;
    private javax.swing.JTextField jTextFieldDireccionPersonal;
    private javax.swing.JTextField jTextFieldEmailPersonal;
    private javax.swing.JTextField jTextFieldFechaNacimientoAnioPersonal;
    private javax.swing.JTextField jTextFieldFechaNacimientoDiaPersonal;
    private javax.swing.JTextField jTextFieldFechaNacimientoMesersonal;
    private javax.swing.JTextField jTextFieldLugarNacimientoPersonal;
    private javax.swing.JTextField jTextFieldMesFinTurno;
    private javax.swing.JTextField jTextFieldMesInicioTurno;
    private javax.swing.JTextField jTextFieldNombrePersonal;
    private javax.swing.JTextField jTextFieldTelefonoPersonal;
    // End of variables declaration//GEN-END:variables

}
